window.aayn = [
  { "word": "עב", "interpretation": "ענן, נשיא." },
  { "word": "עב בשר", "interpretation": "שמן, כבד גוף." },
  { "word": "עבדקן", "interpretation": "בעל זקן עבה." },
  { "word": "עבודה זרה", "interpretation": "עבודת אלילים." },
  { "word": "עבודה סיזיפית", "interpretation": "עבודה קשה שאין בה תועלת." },
  { "word": "עבוט", "interpretation": "ערבות, משכון." },
  { "word": "עבורה של עיר", "interpretation": "שכונות בקצה העיר, פרברי העיר, פאתי העיר." },
  { "word": "עבות", "interpretation": "חבל עבה, כבל." },
  { "word": "עבות", "interpretation": "צפוף." },
  { "word": "עבותות", "interpretation": "חבלים עבים, כבלים." },
  { "word": "עביט", "interpretation": "כלי קיבול לנוזלים." },
  { "word": "עבר זמנו בטל קורבנו", "interpretation": "אינו חשוב עוד." },
  { "word": "עברה", "interpretation": "זעם, כעס, חימה, חרי אף." },
  { "word": "עברי פי פחת", "interpretation": "מקום מסוכן." },
  { "word": "עג", "interpretation": "סבב, חג." },
  { "word": "עגה", "interpretation": "סלנג, דיאלקט, ניב." },
  { "word": "עגום", "interpretation": "עצוב, נוגה, מלנכולי, מדוכא." },
  { "word": "עגונה", "interpretation": "אישה שבעלה נעלם ולא נתן לה גט." },
  { "word": "עגורן", "interpretation": "מכשיר המשמש להרמת משאות כבדים, מעין מנוף." },
  { "word": "עד בוש", "interpretation": "זמן רב." },
  { "word": "עד זרא", "interpretation": "עד כדי גועל." },
  { "word": "עד חורמה", "interpretation": "עד הקץ." },
  { "word": "עדי", "interpretation": "תכשיט, משכית." },
  { "word": "עדנה", "interpretation": "רכות." },
  { "word": "עוד היד נטויה", "interpretation": "עדיין נמשך." },
  { "word": "עוד חזון למועד", "interpretation": "עדיין לא הגיעה השעה." },
  { "word": "עוול", "interpretation": "חוסר צדק, הפרת חוק, עוולה." },
  { "word": "עוון", "interpretation": "פשע, חטא, עברה." },
  { "word": "עוטה", "interpretation": "לובש." },
  { "word": "עוין", "interpretation": "שונא." },
  { "word": "עוכר", "interpretation": "1. מזהם 2. מחבל, משחית." },
  { "word": "עול", "interpretation": "1. כלי רתמה לבקר 2. נטל, מעמסה." },
  { "word": "עול ימים", "interpretation": "צעיר, זאטוט, דרדק." },
  { "word": "עולה", "interpretation": "קורבן זבח." },
  { "word": "עולה בקנה אחד", "interpretation": "מתאים, מסתדר." },
  { "word": "עולל", "interpretation": "תינוק." },
  { "word": "עוללה", "interpretation": "פרי שנשאר על העץ לאחר הבציר או המסיק." },
  { "word": "עולם כמנהגו נוהג", "interpretation": "הכל כרגיל." },
  { "word": "עומד אחר כותלנו", "interpretation": "יגיע בקרוב." },
  { "word": "עומד בדיבורו", "interpretation": "מקיים את הבטחתו." },
  { "word": "עומד במריו", "interpretation": "אינו נכנע." },
  { "word": "עומד בעינו", "interpretation": "נשאר כפי שהוא." },
  { "word": "עומד בפני שוקת שבורה", "interpretation": "המציאות טפחה על פניו." },
  { "word": "עומד בפתח", "interpretation": "שזמנו קרב." },
  { "word": "עומד על תילו", "interpretation": "שאינו הרוס." },
  { "word": "עומר", "interpretation": "אגודת שיבולים, עמיר, אלומה." },
  { "word": "עופל", "interpretation": "מקום גבוה ומבוצר, מבצר." },
  { "word": "עופרה", "interpretation": "איילה צעירה." },
  { "word": "עוצר", "interpretation": "שליט זמני." },
  { "word": "עוקר הרים", "interpretation": "אדם חכם וחריף." },
  { "word": "עורבא פרח", "interpretation": "דברים חסרי שחר, דברי הבאי והבל, קש וגבבה." },
  { "word": "עז מצח", "interpretation": "חצוף, עז פנים, גס רוח." },
  { "word": "עזב אותו לאנחות", "interpretation": "השאיר אותו לבד בעת צרה." },
  { "word": "עזבון", "interpretation": "ירושה." },
  { "word": "עזובה", "interpretation": "מקום מוזנח." },
  { "word": "עזוז", "interpretation": "עוז, כוח, גבורה, תעצומה, חוסן." },
  { "word": "עזקה", "interpretation": "שדה שנעדר כדי להכשירו לנטיעה." },
  { "word": "עזר כנגדו", "interpretation": "אישה, בת זוג." },
  { "word": "עזרה", "interpretation": "מקום מגודר, קרפיף." },
  { "word": "עט", "interpretation": "הסתער." },
  { "word": "עטה שק ואפר", "interpretation": "התאבל." },
  { "word": "עטוי", "interpretation": "מכוסה." },
  { "word": "עטי", "interpretation": "עצה רעה, עצת אחיתופל." },
  { "word": "עטרה", "interpretation": "כתר, נזר." },
  { "word": "עי", "interpretation": "מקום הרוס, תל חורבות." },
  { "word": "עיבוי", "interpretation": "הפיכת דבר לעבה וסמיך." },
  { "word": "עידית", "interpretation": "1. אדמה פורייה 2. סחורה משובחת." },
  { "word": "עידן ועידנים", "interpretation": "זמן רב." },
  { "word": "עידנא דריתחא", "interpretation": "שעת כעס." },
  { "word": "עיור", "interpretation": "הפיכה לעיר, אורבניזציה." },
  { "word": "עילאי", "interpretation": "עליון, נעלה, נאצל." },
  { "word": "עילג", "interpretation": "מגמגם, כבד פה, כבד לשון." },
  { "word": "עילה", "interpretation": "סיבה, תרוץ, תואנה, אמתלה." },
  { "word": "עילית", "interpretation": "הטובים והמובחרים ביותר." },
  { "word": "עין הסערה", "interpretation": "במרכז העניינים." },
  { "word": "עין טובה", "interpretation": "נדיבות, רוחב לב, עין יפה." },
  { "word": "עין לא שזפתהו", "interpretation": "איש לא רעה אותו." },
  { "word": "עיניו טחו מראות", "interpretation": "סירב לראות את הדברים." },
  { "word": "עיניים טרוטות", "interpretation": "עיניים חלשות ורכות." },
  { "word": "עיניים עששות", "interpretation": "עיניים חלושות." },
  { "word": "עיקול", "interpretation": "עיקום, פיתול." },
  { "word": "עיר", "interpretation": "בן החמור." },
  { "word": "עיר פרזות", "interpretation": "עיר ללא חומה או צבא." },
  { "word": "עיר רפאים", "interpretation": "מקום נטוש." },
  { "word": "עיר שדה", "interpretation": "עיר קטנה בסמיכות לעיר גדולה." },
  { "word": "עישוב", "interpretation": "עקירת עשבים שוטים." },
  { "word": "עכבה", "interpretation": "מניעה, עיכוב, מעצור." },
  { "word": "עכו\"ם", "interpretation": "ראשי תיבות של עובד אלילים ומזלות." },
  { "word": "עכור", "interpretation": "בלתי צלול, מלוכלך, דלוח, קודר." },
  { "word": "על אחת כמה וכמה", "interpretation": "ודאי וודאי, אדרבא, לא כל שכן." },
  { "word": "על אפו ועל חמתו", "interpretation": "נגד רצונו." },
  { "word": "על בוריו", "interpretation": "כראוי, כהלכה, בשלמותו." },
  { "word": "על כורחו", "interpretation": "נגד רצונו." },
  { "word": "על כרעי תרנגולת", "interpretation": "לא יציב." },
  { "word": "על כרעיו ועל קרבו", "interpretation": "בשלמותו, כולו." },
  { "word": "על מי מנוחות", "interpretation": "בשלווה, בניחותא." },
  { "word": "על נקלה", "interpretation": "בקלות, בלא קושי." },
  { "word": "על ערש דווי", "interpretation": "גוסס." },
  { "word": "על פיו ישק דבר", "interpretation": "אין לסור מדבריו." },
  { "word": "על פניו", "interpretation": "לכאורה, במבט ראשון." },
  { "word": "על קצה המזלג", "interpretation": "כמות קטנה." },
  { "word": "על קרן הצבי", "interpretation": "מתוך סיכון רב." },
  { "word": "עלה בקנה אחד", "interpretation": "התאים." },
  { "word": "עלה בתוהו", "interpretation": "נכשל." },
  { "word": "עלה על יצועו", "interpretation": "שכב במיטתו." },
  { "word": "עלה על שרטון", "interpretation": "נתקל במכשולים." },
  { "word": "עלה תאנה", "interpretation": "דבר המשמש כסות או הסוואה למשהו." },
  { "word": "עלווה", "interpretation": "כלל העלים המכסים עץ." },
  { "word": "עלום", "interpretation": "נסתר, נעלם, צפון, גנוז." },
  { "word": "עלומים", "interpretation": "נעורים, תשחורת." },
  { "word": "עלטה", "interpretation": "חושך, אפלה." },
  { "word": "עלי", "interpretation": "מוט קצר המשמש לכתישה במכתש." },
  { "word": "עליצות", "interpretation": "שמחה, ששון, חדווה." },
  { "word": "עלם", "interpretation": "בחור צעיר." },
  { "word": "עלתה קרנו", "interpretation": "זכה להערכה." },
  { "word": "עם הארץ", "interpretation": "חסר השכלה, הדיוט, בור." },
  { "word": "עמד בפרץ", "interpretation": "הגן, מנע אסון." },
  { "word": "עמד בשער", "interpretation": "הגן." },
  { "word": "עמד לו כוחו", "interpretation": "כוחו הספיק לו." },
  { "word": "עמד לימינו", "interpretation": "עזר לו." },
  { "word": "עמד מנגד", "interpretation": "לא בא לעזרה." },
  { "word": "עמד על דם רעהו", "interpretation": "לא חש לעזרת חברו." },
  { "word": "עמד על דעתו", "interpretation": "התעקש, עמד על מידותיו." },
  { "word": "עמד על טיבו", "interpretation": "תהה על קנקנו, בחן אותו." },
  { "word": "עמד על טעותו", "interpretation": "הבין שטעה." },
  { "word": "עמד על מידותיו", "interpretation": "התעקש, עמד על דעתו." },
  { "word": "עמדה לו השעה", "interpretation": "הצליח." },
  { "word": "עמוד השחר", "interpretation": "אור ראשון, דמדומי בוקר." },
  { "word": "עמוד התווך", "interpretation": "1. עמוד מרכזי בבניין 2. אדם או דבר מרכזי, המהווה בסיס לכל." },
  { "word": "עמום", "interpretation": "כהה, אטום, חשוך, קהה." },
  { "word": "עמותה", "interpretation": "התאגדות שלא למטרת רווח." },
  { "word": "עמימות", "interpretation": "אי בהירות." },
  { "word": "עמיר", "interpretation": "צרור שיבולים." },
  { "word": "עמית", "interpretation": "חבר לעבודה, רע, קולגה." },
  { "word": "עמק הבכא", "interpretation": "מקום של ייסורים." },
  { "word": "עמק השווה", "interpretation": "פשרה, הסכם." },
  { "word": "ענבל", "interpretation": "לשון הפעמון." },
  { "word": "ענבר", "interpretation": "1. צהוב בהיר 2. שרף מאובן." },
  { "word": "ענו", "interpretation": "צנוע, שפל רוח." },
  { "word": "ענות", "interpretation": "סבל, ייסורים." },
  { "word": "עני מרוד", "interpretation": "דל, דלפון, אביון, רש." },
  { "word": "עניו", "interpretation": "צנוע, שפל רוח, נחבא אל הכלים." },
  { "word": "ענק", "interpretation": "תכשיט לצוואר, רביד." },
  { "word": "עסיס", "interpretation": "מיץ פירות, תירוש, נקטר." },
  { "word": "עפאים", "interpretation": "ענפים, בדים, זרדים." },
  { "word": "עפרא דארעא", "interpretation": "עפר הארץ, דבר חסר ערך, שלג דאשתקד." },
  { "word": "עפרה", "interpretation": "מחצב המכיל מתכת." },
  { "word": "עצר", "interpretation": "שלטון, ממשל, שררה." },
  { "word": "עצת אחיתופל", "interpretation": "עצה רעה של מישהו המתחזה לידיד." },
  { "word": "עקב אכילס", "interpretation": "נקודת תורפה, בטן רכה." },
  { "word": "עקב בצד אגודל", "interpretation": "לאט." },
  { "word": "עקה", "interpretation": "מצוקה." },
  { "word": "עקוב", "interpretation": "1. עקום 2. מלא עקבות, מטונף." },
  { "word": "עקוב מדם", "interpretation": "רווי בדם." },
  { "word": "עקוד", "interpretation": "קשור, כפות." },
  { "word": "עקלקל", "interpretation": "מתפתל." },
  { "word": "עקלתון", "interpretation": "מתפתל, מעוקל." },
  { "word": "עקר", "interpretation": "חסר תועלת." },
  { "word": "ערב", "interpretation": "נעים." },
  { "word": "ערב רב", "interpretation": "1. קהל רב, המון 2. תערובת." },
  { "word": "ערגה", "interpretation": "כמיהה, געגועים, כיסופים." },
  { "word": "ערדליים", "interpretation": "נעלי גומי שנועלים על הנעליים בימי גשם." },
  { "word": "ערובה", "interpretation": "דבר שיש בו כדי להבטיח ביצוע." },
  { "word": "ערוד", "interpretation": "חמור הבר." },
  { "word": "ערוי", "interpretation": "העברה מכלי אל כלי." },
  { "word": "עשה שמות", "interpretation": "הרס, החריב, חרג מהכללים באופן קיצוני." }
]
