window.bet = [
  { "word": "בא אל אבותיו", "interpretation": "נפטר (גם נאסף אל אבותיו)." },
  { "word": "בא בדברים", "interpretation": "נשא ונתן, נדבר." },
  { "word": "בא בימים", "interpretation": "זקן, קשיש." },
  { "word": "באין ציפור שיר, גם עורב זמיר", "interpretation": "הסתפקות בדבר מה אשר איננו הטוב ביותר." },
  { "word": "בא כוח", "interpretation": "נציג, מורשה, ציר, מיופה כוח." },
  { "word": "בא כחתף", "interpretation": "בא לפתע, התקיף פתאום." },
  { "word": "בא על שכרו", "interpretation": "קיבל גמול על מעשיו הטובים." },
  { "word": "בא עליו במקלו ובתרמילו", "interpretation": "תקף אותו בלהט הוויכוח." },
  { "word": "באבו", "interpretation": "בצעירותו." },
  { "word": "באו מים עד נפש", "interpretation": "נמאס, עד קצה גבול היכולת." },
  { "word": "באוש", "interpretation": "מסריח, מעופש, עבש, מצחין." },
  { "word": "באותות ובמופתים", "interpretation": "באופן משכנע, באמצעות הוכחות חותכות." },
  { "word": "באישון לילה", "interpretation": "מאוחר בלילה." },
  { "word": "באשר על כן", "interpretation": "מכיוון שכך." },
  { "word": "בבואה", "interpretation": "דמות, המשתקפת במים או במראה." },
  { "word": "בביטול", "interpretation": "בחוסר הערכה, בהתעלמות מערכו של משהו." },
  { "word": "בגדי חמודות", "interpretation": "בגדים נאים ומכובדים." },
  { "word": "בגדי שרד", "interpretation": "מדים רשמיים." },
  { "word": "בגינו", "interpretation": "בגללו, בעטיו." },
  { "word": "בגפו", "interpretation": "לבדו." },
  { "word": "בגרון נטוי", "interpretation": "ביהירות." },
  { "word": "בד", "interpretation": "1.ענף של עץ, זרד, זלזל, נצר, עפי;2. מסך, אקרן, מרקע." },
  { "word": "בד בבד", "interpretation": "תוך כדי, סימולטני." },
  { "word": "בדותה", "interpretation": "שקר, כזב." },
  { "word": "בדימוס", "interpretation": "לשעבר, בגימלאות." },
  { "word": "בדיעבד", "interpretation": "לאחר מעשה, אפוסטריורי." },
  { "word": "בדלנות", "interpretation": "פרישה מן הכלל." },
  { "word": "בדם ליבו", "interpretation": "בשארית כוחותיו." },
  { "word": "בדם קר", "interpretation": "בלא התרגשות, בשיקול דעת קר." },
  { "word": "בדמי הליל", "interpretation": "בדממת הליל." },
  { "word": "בדמי ימיו", "interpretation": "באמצע חייו." },
  { "word": "בדעה צלולה", "interpretation": "בהכרה מלאה, במלוא החושים." },
  { "word": "בדק בית", "interpretation": "תיקון פגמים, שיפור." },
  { "word": "בדק בציציות", "interpretation": "בדק באופן מעמיק." },
  { "word": "בהול", "interpretation": "דחוף מאוד." },
  { "word": "בהמה גסה", "interpretation": "בקר." },
  { "word": "בהמה דקה", "interpretation": "צאן." },
  { "word": "בהק", "interpretation": "זהר." },
  { "word": "בהרת", "interpretation": "נמש." },
  { "word": "בואך", "interpretation": "הדרך הפונה אל מקום מסוים, בכיוון או בסביבת מקום מסוים." },
  { "word": "בוהו", "interpretation": "ריקנות." },
  { "word": "בוחן כליות ולב", "interpretation": "כינוי לאל." },
  { "word": "בוטה", "interpretation": "חריף, עוקצני, נוקב." },
  { "word": "בולבוס", "interpretation": "תפוח אדמה." },
  { "word": "בולמוס", "interpretation": "רעב חזק, תאווה." },
  { "word": "בומבסטי", "interpretation": "מנופח." },
  { "word": "בונה פידה", "interpretation": "באמת ובתמים, בתום לב." },
  { "word": "בוסר", "interpretation": "לא בשל." },
  { "word": "בוסתן", "interpretation": "גן." },
  { "word": "בוצר", "interpretation": "קוטף ענבים." },
  { "word": "בוקה ומבוקה ומבולקה", "interpretation": "שממון גמור, חורבן מלא." },
  { "word": "בוקי סריקי", "interpretation": "דברי הבאי והבל, להג." },
  { "word": "בוקר", "interpretation": "מגדל בקר." },
  { "word": "בור", "interpretation": "1. שדה לא מעובד; 2. חסר השכלה, נבער." },
  { "word": "בורדו", "interpretation": "אדום כהה." },
  { "word": "בור סוד שאינו מאבד טיפה", "interpretation": "כינוי לאדם בעל זכרון טוב." },
  { "word": "בור שומן", "interpretation": "עסק רווחי." },
  { "word": "בורית", "interpretation": "סבון." },
  { "word": "בורסקאי", "interpretation": "מעבד עורות." },
  { "word": "בושש", "interpretation": "התעכב, התמהמה, איחר." },
  { "word": "בזיך", "interpretation": "ספל, קערית." },
  { "word": "בזעיר אנפין", "interpretation": "בקנה מידה קטן." },
  { "word": "בזק", "interpretation": "פיזר, זרה, זורר." },
  { "word": "בחבו", "interpretation": "בתוכו." },
  { "word": "בחטף", "interpretation": "במהירות יתרה, בחיפזון, לפתע." },
  { "word": "בחל", "interpretation": "נגעל, תיעב, קץ, היה לו לזרא." },
  { "word": "בחרוק שיניים", "interpretation": "התאפקות שלא לחשוף תחושות של רוגז." },
  { "word": "בחרות", "interpretation": "ראשית תקופת הבגרות שבתום תקופת הנעורים." },
  { "word": "בטאון", "interpretation": "עיתון או כתב-עת." },
  { "word": "בטן רכה", "interpretation": "מקום רגיש, נקודת תורפה." },
  { "word": "בטנה", "interpretation": "בד המצפה בגדים או תיקים מצדם הפנימי." },
  { "word": "בטש", "interpretation": "דרך, רמס, כבש, דרס." },
  { "word": "ביאה", "interpretation": "1. פרוזדור, כניסה, מבואה; 2. הזדווגות." },
  { "word": "ביאר", "interpretation": "הסביר, פירש." },
  { "word": "ביב", "interpretation": "ביוב, תעלת שופכין." },
  { "word": "ביבר", "interpretation": "גן חיות." },
  { "word": "ביב שופכין", "interpretation": "ביוב, תעלת שופכין (ראה גם \"ביב\")." },
  { "word": "ביגמיה", "interpretation": "נישואי גבר אחד עם שתי נשים במקביל." },
  { "word": "ביד ברזל", "interpretation": "ביד קשה, ללא רחמים." },
  { "word": "ביד רכה", "interpretation": "בדרכי נועם, בכפפות של משי." },
  { "word": "ביזארי", "interpretation": "מוזר, חריג, יוצא דופן." },
  { "word": "ביזוי", "interpretation": "זילזול." },
  { "word": "ביזור", "interpretation": "פיזור סמכויות." },
  { "word": "ביכר", "interpretation": "העדיף." },
  { "word": "בין המצרים", "interpretation": "ללא מוצא, בין הפטיש ובין הסדן." },
  { "word": "בין השורות", "interpretation": "במרומז, בין השיטין." },
  { "word": "בין השמשות", "interpretation": "לפנות ערב, בין ערביים, דמדומים." },
  { "word": "בינאום", "interpretation": "הפיכת שטח לבינלאומי." },
  { "word": "בינארי", "interpretation": "עשוי משני מרכיבים, דיכוטומי, דואלי." },
  { "word": "בינה", "interpretation": "שכל, תבונה." },
  { "word": "בין ערביים", "interpretation": "לפנות ערב, דמדומים, בין השמשות." },
  { "word": "ביעור", "interpretation": "סילוק, השמדה, חיסול שיטתי." },
  { "word": "ביעות", "interpretation": "סיוט, פחד, יראה, בלהה, חת." },
  { "word": "ביעף", "interpretation": "במהירות, בחיפזון, בבהילות." },
  { "word": "ביצרון", "interpretation": "מבצר, בירנית, מילוא, עופל." },
  { "word": "בירא", "interpretation": "כרת, עקר עצים." },
  { "word": "בירך על המוגמר", "interpretation": "סיים בהצלחה את שהתחיל." },
  { "word": "בישוף", "interpretation": "דרגת כמורה גבוהה." },
  { "word": "בית בד", "interpretation": "בית מלאכה בו מייצרים שמן." },
  { "word": "בית גנזים", "interpretation": "ארכיון." },
  { "word": "בית הלל", "interpretation": "כינוי למי שנוטה להקל בדין." },
  { "word": "בית מטבחיים", "interpretation": "משחטה." },
  { "word": "בית מרזח", "interpretation": "פאב, מסבאה, ממזגה." },
  { "word": "בית נבחרים", "interpretation": "פרלמנט." },
  { "word": "בית נכות", "interpretation": "מוזיאון." },
  { "word": "בית נתיבות", "interpretation": "תחנה, מסוף, טרמינל." },
  { "word": "בית שמאי", "interpretation": "כינוי למי שנוטה להחמיר בדין." },
  { "word": "בית תמחוי", "interpretation": "מטבח ציבורי לנזקקים." },
  { "word": "ביתוק", "interpretation": "שיסוע, ביתור." },
  { "word": "ביתור", "interpretation": "חיתוך, שיסוף, ביתוק, פילוח." },
  { "word": "בכדי", "interpretation": "לשווא, לריק, לחינם." },
  { "word": "בכובד ראש", "interpretation": "ברצינות, מתוך שיקול דעת." },
  { "word": "בכי תמרורים", "interpretation": "בכי מר, בדמעות שליש." },
  { "word": "בכייה לדורות", "interpretation": "אסון שאין לו סוף." },
  { "word": "בכל רמח איבריו", "interpretation": "כל כולו, בכל הוויתו." },
  { "word": "בכפיפה אחת", "interpretation": "ביחד, בצוותא." },
  { "word": "בכר", "interpretation": "גמל צעיר." },
  { "word": "בכרה", "interpretation": "נאקה צעירה." },
  { "word": "בלאט", "interpretation": "בסתר, בחשאי, בצנעה." },
  { "word": "בלב ולב", "interpretation": "במרמה, בחוסר כנות." },
  { "word": "בלב שלם", "interpretation": "ביושר, באמת ובתמים." },
  { "word": "בלהה", "interpretation": "פחד, בעתה, חיל, פלצות." },
  { "word": "בלואים", "interpretation": "בגדים מרופטים." },
  { "word": "בלוי", "interpretation": "ישן, מרופט, בלה, מהוה." },
  { "word": "בלול", "interpretation": "מעורב, מעורבב." },
  { "word": "בלום", "interpretation": "סתום, מלא, גדוש." },
  { "word": "בלטריסטיקה", "interpretation": "ספרות יפה." },
  { "word": "בלי חשך", "interpretation": "ללא הפסקה, בלי הרף." },
  { "word": "בלי מצרים", "interpretation": "בלי גבול." },
  { "word": "בלימה", "interpretation": "כלום, אין, אפס." },
  { "word": "בליסטרא", "interpretation": "מכשיר מלחמה לזריקת אבנים, מרגמה." },
  { "word": "בלן", "interpretation": "עובד בבית מרחץ." },
  { "word": "בלע", "interpretation": "מרמה, שחיתות." },
  { "word": "בלשון סגי נהור", "interpretation": "שימוש בלשון במשמעות הפוכה." },
  { "word": "בלתי אמצעי", "interpretation": "ישיר, ללא תיווך." },
  { "word": "בלתי נדלה", "interpretation": "שאינו נגמר, אינסופי." },
  { "word": "בלתי נלאה", "interpretation": "חזק, נמרץ, כוחו במותניו." },
  { "word": "במזיד", "interpretation": "בכוונה להרע." },
  { "word": "במטותא", "interpretation": "בבקשה, אנא." },
  { "word": "במלוא הקיטור", "interpretation": "במלוא המרץ." },
  { "word": "במפגיע", "interpretation": "בתקיפות, באסרטיביות." },
  { "word": "במצב נחושה", "interpretation": "1. בעקשנות; 2. בחוצפה." },
  { "word": "במתק שפתיים", "interpretation": "בדיבור מתחנחן." },
  { "word": "במשורה", "interpretation": "בצמצום." },
  { "word": "בן אלמוות", "interpretation": "בעל חיי נצח." },
  { "word": "בן בלי שם", "interpretation": "בעל מעמד נחות." },
  { "word": "בן בליעל", "interpretation": "נבל, רשע, בן עוולה." },
  { "word": "בן חורין", "interpretation": "אדם חופשי." },
  { "word": "בן כלאיים", "interpretation": "צאצא של צמחים או בעלי- חיים בני זנים שונים." },
  { "word": "בן סורר ומורה", "interpretation": "מורד, אינו סר למרות הוריו." },
  { "word": "בן תשחורת", "interpretation": "צעיר, עול ימים." },
  { "word": "בנאלי", "interpretation": "שכיח, נדוש, שגרתי." },
  { "word": "בנה בחול", "interpretation": "טרח לשווא." },
  { "word": "בנוי לתלפיות", "interpretation": "1. בעל גוף שרירי; 2. מתנוסס ברוב הדרו." },
  { "word": "בניחותא", "interpretation": "באיטיות, בנחת, בשופי." },
  { "word": "בניין אב", "interpretation": "יסוד, אבטיפוס, פרוטוטיפ." },
  { "word": "בסירה אחת", "interpretation": "גורל משותף." },
  { "word": "בעברי פי פחת", "interpretation": "במקום מסוכן." },
  { "word": "בעור שיניו", "interpretation": "נמלט ברגע האחרון." },
  { "word": "בעטיו", "interpretation": "בגללו, בגינו." },
  { "word": "בעידנא דריתחא", "interpretation": "בשעת כעס." },
  { "word": "בעיצומו", "interpretation": "בשיאו." },
  { "word": "בעל אוב", "interpretation": "קוסם המעלה רוחות מתים לניחוש עתידות." },
  { "word": "בעל אף", "interpretation": "כעסן." },
  { "word": "בעל בשר", "interpretation": "שמן, בעל גוף." },
  { "word": "בעל כרחו", "interpretation": "שלא מרצונו." },
  { "word": "בעל קומה", "interpretation": "גבוה." },
  { "word": "בעלמא", "interpretation": "סתם, ללא כוונה." },
  { "word": "בעצלתיים", "interpretation": "באיטיות מרובה." },
  { "word": "בערוב ימיו", "interpretation": "בסוף חייו." },
  { "word": "בעתה", "interpretation": "פחד, חיל, פיק, פלצות." },
  { "word": "בפוטנציה", "interpretation": "באופן שעדיין לא מומש." },
  { "word": "בפרהסיה", "interpretation": "בגלוי, קבל עם ועדה." },
  { "word": "בצדיה", "interpretation": "בכוונה רעה." },
  { "word": "בצוותא", "interpretation": "ביחד." },
  { "word": "בציר", "interpretation": "קטיף ענבים." },
  { "word": "בצע", "interpretation": "פרס, חתך." },
  { "word": "בקי", "interpretation": "מומחה, יודע דבר על בוריו." },
  { "word": "בקק", "interpretation": "החריב." },
  { "word": "בר", "interpretation": "1. נקי; 2. חוץ; 3. בן; 4. תבואה." },
  { "word": "בר אוריין", "interpretation": "תלמיד חכם, למדן, בן תורה." },
  { "word": "בר בי רב", "interpretation": "תלמיד." },
  { "word": "בר דעת", "interpretation": "חכם." },
  { "word": "בר חלוף", "interpretation": "זמני, ארעי." },
  { "word": "בר לבב", "interpretation": "ישר, תמים." },
  { "word": "בר מינן", "interpretation": "מת, הלך בדרך כל הארץ." },
  { "word": "בר סמכא", "interpretation": "מומחה, בקי." },
  { "word": "בר פלוגתא", "interpretation": "יריב, בעל מחלוקת." },
  { "word": "בר קיימא", "interpretation": "יציב, מתקיים לאורך זמן." },
  { "word": "בר סמכא", "interpretation": "מומחה." },
  { "word": "בראש חוצות", "interpretation": "בגלוי, בפרהסיה." },
  { "word": "בראש מעיניו", "interpretation": "בראש סדר העדיפויות שלו." },
  { "word": "ברוד", "interpretation": "מכוסה כתמים או נקודות, מנומר." },
  { "word": "ברוטלי", "interpretation": "אכזרי." },
  { "word": "ברומו של עולם", "interpretation": "חשוב." },
  { "word": "ברי", "interpretation": "ברור, ודאי." },
  { "word": "בריה", "interpretation": "יצור, בעל חיים, בן תמותה." },
  { "word": "בריח", "interpretation": "מוט לנעילת הדלת." },
  { "word": "בריקדה", "interpretation": "מחסום, מתרס." },
  { "word": "ברכה לבטלה", "interpretation": "טרחה המושקעת לריק." },
  { "word": "ברנש", "interpretation": "בן אדם." },
  { "word": "בשוגג", "interpretation": "לא בכוונה." },
  { "word": "בשופי", "interpretation": "בנחת, בניחותא, מעדנות." },
  { "word": "בשן ועין", "interpretation": "בנזק כבד." },
  { "word": "בשר ודם", "interpretation": "בן תמותה." },
  { "word": "בשר מבשרו", "interpretation": "קרוב אליו, חשוב לו כבן משפחה." },
  { "word": "בת קול", "interpretation": "הד." },
  { "word": "בתה", "interpretation": "שדה מוזנח ושומם, ישימון." }
]
