window.gimel = [
  { "word": "גאה", "interpretation": "התרומם, עלה." },
  { "word": "גבה לבו", "interpretation": "התגאה, התייהר, התרברב." },
  { "word": "גבהו ממנו הדברים", "interpretation": "לא הבין." },
  { "word": "גבו אל הקיר", "interpretation": "ללא מוצא, בין המצרים." },
  { "word": "גבין", "interpretation": "גבה." },
  { "word": "גביר", "interpretation": "אדם עשיר, אמיד." },
  { "word": "גבנון", "interpretation": "עקמומיות של הגב, חטוטרת." },
  { "word": "גבר", "interpretation": "תרנגול, שכוי." },
  { "word": "גבר אגרופו", "interpretation": "התחזק." },
  { "word": "גברה ידו", "interpretation": "ניצח." },
  { "word": "גברתן", "interpretation": "בעל כוח, בעל גוף." },
  { "word": "גד", "interpretation": "מזל, אושר, הצלחה, פיס, פור." },
  { "word": "גדה", "interpretation": "שפת הנהר." },
  { "word": "גדוד", "interpretation": "חתוך." },
  { "word": "גדולות ונצורות", "interpretation": "דברים גדולים ומפתיעים." },
  { "word": "גדיד", "interpretation": "קטיף תמרים." },
  { "word": "גדיל", "interpretation": "קצוות חוטים, ציצית." },
  { "word": "גדיש", "interpretation": "ערמת תבואה שנקצרה." },
  { "word": "גדש", "interpretation": "צבר, ערם, מילא יתר על המידה." },
  { "word": "גהה", "interpretation": "רפואה, מרפא, צרי." },
  { "word": "גהות", "interpretation": "הגיינה." },
  { "word": "גהר", "interpretation": "התכופף, רכן, שח, גחן, השתופף." },
  { "word": "גו", "interpretation": "1. פנים, תוך; 2. גב, גוף." },
  { "word": "גוב", "interpretation": "בור, מאורה." },
  { "word": "גוב אריות", "interpretation": "מקום מסוכן." },
  { "word": "גוויל", "interpretation": "קלף, דף מספר עתיק." },
  { "word": "גוזמה", "interpretation": "הפרזה, דברי הבאי." },
  { "word": "גולל", "interpretation": "אבן עגולה ששימשה לכיסוי פי הבאר." },
  { "word": "גולמי", "interpretation": "בלתי מעובד." },
  { "word": "גומה", "interpretation": "חור, שקע." },
  { "word": "גומחה", "interpretation": "שקע, מגרעת." },
  { "word": "גוץ", "interpretation": "נמוך ושמנמן." },
  { "word": "גור", "interpretation": "היזהר." },
  { "word": "גורס", "interpretation": "לועס." },
  { "word": "גושפנקה", "interpretation": "חותם, אישור." },
  { "word": "גז", "interpretation": "1. צמר שנגזז; 2. נעלם, עבר, התפוגג." },
  { "word": "גזוזטרה", "interpretation": "מרפסת." },
  { "word": "גזיר", "interpretation": "חתיכה, נתח, פיסה." },
  { "word": "גזירה", "interpretation": "פקודה שיש בה איסור." },
  { "word": "גזר כליה", "interpretation": "הביא לסופו, חיסל אותו." },
  { "word": "גזרה שווה", "interpretation": "היקש, השוואה בין שני עניינים הדומים זה לזה בתכנם או בצורתם." },
  { "word": "גחמה", "interpretation": "רצון פתאומי שקשה להסבירו, עיקשות, קפריזה." },
  { "word": "גחן", "interpretation": "התכופף, רכן, שחה, גהר." },
  { "word": "גיא", "interpretation": "עמק." },
  { "word": "גיבב", "interpretation": "צבר, ערם, קושש, גדש." },
  { "word": "גיבח", "interpretation": "קרח בראשו מצד המצח." },
  { "word": "גיבן", "interpretation": "שגבו מעוקם, בעל חטוטרת." },
  { "word": "גידם", "interpretation": "קטוע יד, גידע." },
  { "word": "גידף", "interpretation": "קילל, חירף, גינה, ניאץ, ארר." },
  { "word": "גיור", "interpretation": "המרת דתו של אדם ליהדות." },
  { "word": "גילה את קלפיו", "interpretation": "חשף את כוונותיו." },
  { "word": "גילה טפח וכיסה טפחיים", "interpretation": "העלים יותר משגילה." },
  { "word": "גילו את אזנו", "interpretation": "גילו לו." },
  { "word": "גילוי דעת", "interpretation": "מאמר." },
  { "word": "גילום", "interpretation": "עיצוב, מתן צורה מוחשית." },
  { "word": "גילופין", "interpretation": "שכרות קלה." },
  { "word": "גימא ארץ", "interpretation": "דהר מהר." },
  { "word": "גינה", "interpretation": "קילל, חירף, קילס, ניאץ, גידף." },
  { "word": "גינונים", "interpretation": "נימוסים והליכות, דרך ארץ." },
  { "word": "גיס חמישי", "interpretation": "כינוי לבוגדים מבית, סוס טרויאני." },
  { "word": "גירסא דינקותא", "interpretation": "הידע שלמד אדם בילדותו." },
  { "word": "גל", "interpretation": "ערמה, תל, חשרה, צבר." },
  { "word": "גלד", "interpretation": "קרום יבש, המכסה את מקום הפציעה בעור." },
  { "word": "גלובלי", "interpretation": "כלל עולמי, אוניברסלי." },
  { "word": "גלום", "interpretation": "מקופל, מגולל, חבוי בפנים." },
  { "word": "גלוסקמה", "interpretation": "ארון קבורה, סרקופג." },
  { "word": "גלופה", "interpretation": "לוח עם תבליטי אותיות המשמש להדפסתן." },
  { "word": "גלוריפיקציה", "interpretation": "האדרה." },
  { "word": "גליל", "interpretation": "אזור, מחוז, חבל, פלך, נפה." },
  { "word": "גלל", "interpretation": "גילגל, טילטל." },
  { "word": "גלל חרפה מעליו", "interpretation": "החזיר אליו את כבודו." },
  { "word": "גלמוד", "interpretation": "בודד, ערירי, חשוך בנים." },
  { "word": "גלעין", "interpretation": "חרצן, גרעין של פרי." },
  { "word": "גלקסיה", "interpretation": "מערכת כוכבים." },
  { "word": "גמא", "interpretation": "שתה, לגם, גמע." },
  { "word": "גמא מרחקים", "interpretation": "עבר דרך ארוכה." },
  { "word": "גמלוני", "interpretation": "גבוה, ארוך, תמיר, רם, כיפח." },
  { "word": "גמר אומר", "interpretation": "החליט, גמר בליבו." },
  { "word": "גמר עליו את ההלל", "interpretation": "שיבח, קילס, הרים את קרנו, קשר כתרים." },
  { "word": "גנב את ליבו", "interpretation": "רימה, גנב את דעתו." },
  { "word": "גנוז", "interpretation": "נסתר, כמון, ספון, כמוס, צפון." },
  { "word": "גנזך", "interpretation": "ארכיון, ארכיב." },
  { "word": "גנראטור", "interpretation": "מתקן ליצור חשמל (ראה גם \"מחולל\" ו\"טורבינה\")." },
  { "word": "גסטרונומיה", "interpretation": "אמנות הבישול, קולינרי." },
  { "word": "גפה", "interpretation": "1. שפה; 2. החלק העליון בנעל, שבשוליו השרוכים." },
  { "word": "גפיים", "interpretation": "אברי התנועה, הידיים והרגליים בבני אדם." },
  { "word": "גפיר", "interpretation": "שומר, שוטר, זקיף, נוטר." },
  { "word": "גץ", "interpretation": "ניצוץ שביב אש." },
  { "word": "גר", "interpretation": "אדם שבא לגור בארץ זרה, נוכרי." },
  { "word": "גרדום", "interpretation": "גיליוטינה." },
  { "word": "גרוגרת", "interpretation": "תאנה מיובשת, דבלה." },
  { "word": "גרוטסקי", "interpretation": "מגוחך, נלעג." },
  { "word": "גרום", "interpretation": "בעל עצמות בולטות." },
  { "word": "גרידא", "interpretation": "אך ורך, בלבד, ותו לא." },
  { "word": "גרם", "interpretation": "1. עצם; 2. גוף." },
  { "word": "גרנדיוזי", "interpretation": "מפואר, נשגב, נאדר, עצום." },
  { "word": "גרס", "interpretation": "טען." },
  { "word": "גרעון", "interpretation": "חוסר, הפסד, חסך, פחת." },
  { "word": "גשם זלעפות", "interpretation": "גשם כבד וסוער." },
  { "word": "גשם נדבות", "interpretation": "גשם היורד בעתו ובשפע, גשם ברכה." },
  { "word": "גשמי", "interpretation": "חומרי, גופני, פיזי." },
  { "word": "גת", "interpretation": "בור, שדורכים בו ענבים ליין" }
]
