window.hei = [
  { "word": "הא בהא תליא", "interpretation": "הדברים תלויים זה בזה." },
  { "word": "האביס", "interpretation": "האכיל, הלעיט, פיטם." },
  { "word": "האדיר", "interpretation": "שיבח, הילל, קילס." },
  { "word": "האיר פנים", "interpretation": "גילה רצון טוב, הסביר פנים." },
  { "word": "האמיר", "interpretation": "גדל, התייקר." },
  { "word": "האנשה", "interpretation": "ייחוס תכונות אנושיות לבעלי חיים." },
  { "word": "האפיל", "interpretation": "החשיך." },
  { "word": "האצלה", "interpretation": "העברה, השראה." },
  { "word": "האריך אפו", "interpretation": "התאפק מלכעוס." },
  { "word": "הארקה", "interpretation": "חיבור מכשיר חשמלי לאדמה למניעת התחשמלות." },
  { "word": "הב!", "interpretation": "תן!" },
  { "word": "הבאי", "interpretation": "הגזמה, הבל, להג, קש וגבבה." },
  { "word": "הבאיש", "interpretation": "הפיץ ריח רע." },
  { "word": "הבאיש את ריחו", "interpretation": "הוציא לו שם רע." },
  { "word": "הבהיל", "interpretation": "הביא בדחיפות, הזעיק." },
  { "word": "הביל", "interpretation": "ספוג אדים, לח." },
  { "word": "הבכיר", "interpretation": "הבשיל." },
  { "word": "הבל", "interpretation": "1. קיטור, אד; 2. שטות, הבאי." },
  { "word": "הבלי עולם", "interpretation": "כינוי למותרות ולתענוגות הנתפסים כטפלים." },
  { "word": "הבליג", "interpretation": "התאפק, משל ברוחו." },
  { "word": "הבליח", "interpretation": "נצנץ." },
  { "word": "הברכה", "interpretation": "הבאת הגמל לכרוע על ברכיו." },
  { "word": "הגד", "interpretation": "הוכחה." },
  { "word": "הגהה", "interpretation": "בדיקת כתבים ותיקון הטעויות." },
  { "word": "הגות", "interpretation": "מחשבה, עיון, הרהורים, שגיונות." },
  { "word": "הגיגים", "interpretation": "הרהורים, מחשבות." },
  { "word": "הגיע לפרקו", "interpretation": "הגיעה שעתו להתחתן." },
  { "word": "הגיע עד צוואר", "interpretation": "הגיע לקצה גבול היכולת." },
  { "word": "הגיעו מים עד נפש", "interpretation": "עד כאן, כלו כל הקיצין." },
  { "word": "הגיף", "interpretation": "סגר, נעל." },
  { "word": "הגיר", "interpretation": "הזיל, הזליף, היזה, הרעיף." },
  { "word": "הגליד", "interpretation": "נרפא, העלה ארוכה." },
  { "word": "הגליה", "interpretation": "גירוש אדם ממולדתו." },
  { "word": "הגמוניה", "interpretation": "שליטה, שלטון עליון." },
  { "word": "הגעלה", "interpretation": "1. הכשרת כלים לפסח; 2. המאסה, גרימת גועל." },
  { "word": "הדביק", "interpretation": "השיג, רדף והגיע." },
  { "word": "הדביר", "interpretation": "השמיד, הכניע." },
  { "word": "הדום", "interpretation": "שרפרף, כסא נמוך, דרגש." },
  { "word": "הדוניזם", "interpretation": "רדיפת תענוגות, נהנתנות." },
  { "word": "הדוניסט", "interpretation": "נהנתן." },
  { "word": "הדיוט", "interpretation": "שאינו מומחה, חסר השכלה." },
  { "word": "הדיח", "interpretation": "הסית למעשה רע, פיתה, התעה." },
  { "word": "הדיר הנאה", "interpretation": "לא התיר להנות." },
  { "word": "הדיר רגליו", "interpretation": "נמנע מלהגיע, הוקיר רגליו." },
  { "word": "הדיר שינה מעיניו", "interpretation": "הדאיג אותו, מנע ממנו לישון." },
  { "word": "הדמיה", "interpretation": "סימולציה." },
  { "word": "הדר", "interpretation": "פאר, תפארת, הוד." },
  { "word": "הדריך את מנוחתו", "interpretation": "הטריד אותו." },
  { "word": "ההר הוליד עכבר", "interpretation": "תוצאות מאכזבות לנוכח הציפיות." },
  { "word": "הוד", "interpretation": "יופי, פאר, הדר, אדרת, יפעה." },
  { "word": "הוה", "interpretation": "אסון, צרה, פיד, איד, שבר." },
  { "word": "הווי אומר", "interpretation": "ברור שזה…, התשובה המובנת מאליה היא…" },
  { "word": "הוכיח", "interpretation": "נזף, הטיף מוסר, גער, גינה." },
  { "word": "הוליך שולל", "interpretation": "השלה, התעה." },
  { "word": "הולך בתלם", "interpretation": "שמרן, צייתן, קונפורמי." },
  { "word": "הולך על חבל דק", "interpretation": "נמצא במצב מסוכן." },
  { "word": "הומוגני", "interpretation": "אחיד." },
  { "word": "הומני", "interpretation": "אנושי." },
  { "word": "הוסיף נופך", "interpretation": "הוסיף משהו, קישט באמצעות תוספת כלשהי." },
  { "word": "הוסיף שמן למדורה", "interpretation": "סיבך את המצב, ליבה את היצרים." },
  { "word": "הופך יתוש לפיל", "interpretation": "מגזים." },
  { "word": "הוציא את הערמונים מהאש", "interpretation": "ביצע מלאכה קשה או בלתי נעימה." },
  { "word": "הוציא דיבה", "interpretation": "דיבר רעות, הכפיש." },
  { "word": "הוקיע", "interpretation": "גינה, ביקר, מוכיח בשער." },
  { "word": "הוקיר", "interpretation": "כיבד." },
  { "word": "הוקיר רגליו", "interpretation": "נמנע מלבקר, הדיר רגליו." },
  { "word": "הוריזונטלי", "interpretation": "אופקי." },
  { "word": "הותק", "interpretation": "הוזז." },
  { "word": "הותרו חרצובות לשונו", "interpretation": "התחיל לדבר." },
  { "word": "הזדיין בסבלנות", "interpretation": "חיכה בסבלנות." },
  { "word": "הזדינות", "interpretation": "התחמשות, הצטיידות בנשק." },
  { "word": "הזון חוזר", "interpretation": "משוב, פידבק." },
  { "word": "הזיה", "interpretation": "חלום בהקיץ, דמיון שווא, הלוצינציה." },
  { "word": "הזין", "interpretation": "האכיל." },
  { "word": "הזיע", "interpretation": "הזיז." },
  { "word": "הזליף", "interpretation": "טפטף, התיז, הזיל, היזה, הגיר." },
  { "word": "הזם", "interpretation": "הוכיח כשקרי, סתר." },
  { "word": "הזרה", "interpretation": "הרחקה." },
  { "word": "החזיק טובה", "interpretation": "הכיר תודה." },
  { "word": "החזיק טובה לעצמו", "interpretation": "התייהר." },
  { "word": "החזיר עטרה ליושנה", "interpretation": "שיקם דברים והחזירם לקדמותם." },
  { "word": "החיש", "interpretation": "זירז, האיץ, המריץ." },
  { "word": "החיש פעמיו", "interpretation": "הזדרז." },
  { "word": "החכיר", "interpretation": "השכיר נכס או קרקע לזמן קצוב." },
  { "word": "החלה", "interpretation": "הענקת תוקף לחוק או תקנה." },
  { "word": "החמיץ פנים", "interpretation": "עשה \"פרצוף חמוץ\"." },
  { "word": "החצין", "interpretation": "הפנה כלפי חוץ." },
  { "word": "החרה החזיק אחריו", "interpretation": "זירז, החיש, האיץ." },
  { "word": "החרים", "interpretation": "הפקיע, הוציא מרשות בעליו." },
  { "word": "החריש", "interpretation": "שתק, דמם, החשה, הסכית." },
  { "word": "החשה", "interpretation": "דמם, נדם, נאלם, החריש." },
  { "word": "הטביע", "interpretation": "יצר תבנית." },
  { "word": "הטחה", "interpretation": "השלכה, הטלה." },
  { "word": "הטיל אבק בעיני האנשים", "interpretation": "הטעה, הוליך שולל." },
  { "word": "הטיל מורא", "interpretation": "הפחיד." },
  { "word": "הטית אוזן", "interpretation": "הקשבה." },
  { "word": "הטית משפט / דין", "interpretation": "עיוות הדין." },
  { "word": "הטלת איפול", "interpretation": "החשכה, האפלה." },
  { "word": "הטמין", "interpretation": "החביא, הסתיר, הכמין, הצפין." },
  { "word": "הטמעה", "interpretation": "הפנמה, הידמות, אסימילציה." },
  { "word": "הטעים", "interpretation": "הדגיש." },
  { "word": "הטרים", "interpretation": "הקדים." },
  { "word": "הי", "interpretation": "אבל, קינה, נהי, מספד." },
  { "word": "היא הנותנת", "interpretation": "דווקא דבר זה מוכיח, אדרבא, לא כל שכן, קל וחומר." },
  { "word": "היבריד", "interpretation": "בן כלאיים." },
  { "word": "היבריס", "interpretation": "גאווה, גאוותנות, חשיבה עצמית יתרה." },
  { "word": "הידוס", "interpretation": "הליכה מתנודדת ולא יציבה." },
  { "word": "היה את נפשו", "interpretation": "רצה, חפץ, חשק, אבה." },
  { "word": "היה בלבו עליו", "interpretation": "כעס, שמר טינה." },
  { "word": "היה בעוכריו", "interpretation": "הכשיל אותו." },
  { "word": "היה כמרקחה", "interpretation": "מהומה." },
  { "word": "היה לו לזרא", "interpretation": "מאס." },
  { "word": "היה למשל ולשנינה", "interpretation": "צחקו עליו, היה ללעג ולקלס." },
  { "word": "היה נביא בעירו", "interpretation": "הצליח במקום מושבו." },
  { "word": "היה סיפק בידו", "interpretation": "היה באפשרותו." },
  { "word": "היהלום שבכתר", "interpretation": "הדבר היפה ביותר או החשוב ביותר." },
  { "word": "היהפוך כושי עורו", "interpretation": "הישתנה טבע האדם." },
  { "word": "היולי", "interpretation": "ראשוני, קדמוני, קמאי." },
  { "word": "היזה", "interpretation": "טפטף, הזיל, הזליף, הגיר." },
  { "word": "היטיב את ליבו", "interpretation": "נהנה מאוכל ומשתיה." },
  { "word": "היכה בברזל בעודו חם", "interpretation": "ניצל את ההזדמנות." },
  { "word": "היכה גלים", "interpretation": "עורר תגובות." },
  { "word": "היכה על חטא", "interpretation": "התחרט, ניחם, חזר בו." },
  { "word": "הילה", "interpretation": "מעגל או מסגרת של אור סביב משהו." },
  { "word": "הילך עליו אימים", "interpretation": "הפחיד אותו." },
  { "word": "הין", "interpretation": "מידה קדומה לנוזלים." },
  { "word": "הינומה", "interpretation": "כיסוי לראש הכלה." },
  { "word": "היפוקרטיזם", "interpretation": "צביעות." },
  { "word": "היפותזה", "interpretation": "השערה." },
  { "word": "היפותטי", "interpretation": "משוער, לא ודאי." },
  { "word": "היפרעות", "interpretation": "1. גביית חוב; 2. הענשה." },
  { "word": "היקוות", "interpretation": "האספות." },
  { "word": "היקש", "interpretation": "הסקה מתוך השוואה, אנלוגיה." },
  { "word": "הירואי", "interpretation": "שיש בו אומץ וגבורה." },
  { "word": "הירקמות", "interpretation": "היווצרות, התהוות." },
  { "word": "היררכיה", "interpretation": "סולם דרגות." },
  { "word": "הכביד את ליבו", "interpretation": "התעקש, עמד בסירובו." },
  { "word": "הכביד את ידו עליו", "interpretation": "החמיר עמו." },
  { "word": "הכביר", "interpretation": "הגדיל, הרבה, העתיר, העמיס." },
  { "word": "הכחיד", "interpretation": "השמיד, הצמית, ביער, הכרית." },
  { "word": "הכלאה", "interpretation": "זיווג בעלי-חיים או צמחים ממינים שונים." },
  { "word": "הכליב", "interpretation": "תפר תפרים גסים." },
  { "word": "הכלים", "interpretation": "בייש, הלבין פנים." },
  { "word": "הכמין", "interpretation": "הסתיר, החביא, הצפין, הטמין." },
  { "word": "הכפיף", "interpretation": "גרם למישהו להיות תחת סמכותו, הטיל מרותו." },
  { "word": "הכפיש", "interpretation": "דיבר רעות, הוציא דיבה." },
  { "word": "הכרית", "interpretation": "השמיד, חיסל, כילה." },
  { "word": "הלאים", "interpretation": "העביר נכסים מרשות הפרט לרשות המדינה." },
  { "word": "הלבין פנים", "interpretation": "בייש, הכלים." },
  { "word": "הלום", "interpretation": "כאן." },
  { "word": "הלוצינציה", "interpretation": "הזיה, מחזה שווא." },
  { "word": "הליט", "interpretation": "כיסה, עטף, כרך." },
  { "word": "הליכות", "interpretation": "נימוסים, גינונים, דרך ארץ." },
  { "word": "הלין", "interpretation": "1. התלונן 2. סיפק מקום לינה 3. עיכב." },
  { "word": "הלך בדרך כל בשר", "interpretation": "נפטר, מת." },
  { "word": "הלך בתלם", "interpretation": "התנהג כמקובל." },
  { "word": "הלך הזרזיר אצל העורב", "interpretation": "כל אחד מתחבר לדומים לו." },
  { "word": "הלך לאבדון", "interpretation": "נהרס, חדל להתקיים." },
  { "word": "הלך לאורו", "interpretation": "1. נהג על פיו; 2. האמין בו." },
  { "word": "הלך מדחי אל דחי", "interpretation": "הלך והידרדר." },
  { "word": "הלך לקנוסה", "interpretation": "נכנע, ביקש מחילה." },
  { "word": "הלך סחור סחור", "interpretation": "עסק בעניינים שוליים." },
  { "word": "הלך על חבל דק", "interpretation": "מצב שבו כל טעות קטנה גורמת נזק." },
  { "word": "הלך עמו בקרי", "interpretation": "התנגד לו, היה למכשול." },
  { "word": "הלך רכיל", "interpretation": "דיבר רעות, הכפיש." },
  { "word": "הלך שבי", "interpretation": "נמשך אחרי, נשבה בקסמו." },
  { "word": "הלך שולל", "interpretation": "הוטעה, רומה." },
  { "word": "הלכה למעשה", "interpretation": "בפועל, למעשה." },
  { "word": "הלמות", "interpretation": "דפיקה, מכה." },
  { "word": "הלנה", "interpretation": "1. הכנסת אורח למשך הלילה;  2. דחיית דבר מה למשך הלילה." },
  { "word": "הלעיז", "interpretation": "דיבר רעות, הכפיש." },
  { "word": "הלעיט", "interpretation": "האכיל, פיטם, האביס." },
  { "word": "הלקאה", "interpretation": "הכאה, הצלפה בשוט." },
  { "word": "המיה", "interpretation": "קול חלש ועדין." },
  { "word": "המיר", "interpretation": "החליף." },
  { "word": "המלכה", "interpretation": "1. הכתרה למלך; 2. ייעוץ." },
  { "word": "המציא", "interpretation": "הציג." },
  { "word": "המרה את פיו", "interpretation": "לא ציית לפקודתו." },
  { "word": "המשגה", "interpretation": "יצירת מושגים." },
  { "word": "המתיק את הגלולה", "interpretation": "הקל." },
  { "word": "המתיק סוד", "interpretation": "טיכס עצה, תחבל תחבולה." },
  { "word": "הנחיל", "interpretation": "הקנה, הוריש, העביר." },
  { "word": "הניא", "interpretation": "מנע, ביטל, עיכב." },
  { "word": "הניח כספו על קרן הצבי", "interpretation": "סיכן את כספו בעסק שהפסדו ודאי." },
  { "word": "הנפיק", "interpretation": "הוציא, הניב." },
  { "word": "הנץ החמה", "interpretation": "זריחת השחר, דמדומים." },
  { "word": "הסח הדעת", "interpretation": "חוסר תשומת לב." },
  { "word": "הסיע דבר מלבו", "interpretation": "התעלם." },
  { "word": "הסיק", "interpretation": "העלה אש." },
  { "word": "הסכין", "interpretation": "התרגל." },
  { "word": "הסכית", "interpretation": "1. שתק, דמם; 2. הקשיב." },
  { "word": "הסתאב", "interpretation": "הזדהם, התנוון, הושחת." },
  { "word": "הסתודד", "interpretation": "ריכל." },
  { "word": "הסתופף", "interpretation": "שהה, ביקר, בילה." },
  { "word": "העבטה", "interpretation": "נתינת הלוואה תמורת ערבות." },
  { "word": "העביר על מידותיו", "interpretation": "ויתר, לא הקפיד." },
  { "word": "העבירו על דעתו", "interpretation": "הרגיז אותו מאוד." },
  { "word": "העויה", "interpretation": "עיוות הפנים, לעשות \"פרצוף\"." },
  { "word": "העז פנים", "interpretation": "התחצף." },
  { "word": "העלה ארוכה", "interpretation": "הבריא." },
  { "word": "העלה באוב", "interpretation": "הזכיר נשכחות." },
  { "word": "העלה חרס", "interpretation": "לא מצא דבר, הפסיד." },
  { "word": "העלה על נס", "interpretation": "פרסם, קשר כתרים." },
  { "word": "העלה את קרנו", "interpretation": "שיבח והילל אותו." },
  { "word": "העמיד את העגלה לפני הסוסים", "interpretation": "הקדים את המאוחר, הפך את היוצרות." },
  { "word": "הערה אל קרבו", "interpretation": "שתה." },
  { "word": "העתיק", "interpretation": "הזיז ממקומו." },
  { "word": "העתיר", "interpretation": "נתן הרבה, הכביר." },
  { "word": "הפוגה", "interpretation": "הפסקה." },
  { "word": "הפטיר", "interpretation": "מילמל." },
  { "word": "הפיג", "interpretation": "הפחית, החליש." },
  { "word": "הפיך", "interpretation": "שאפשר להפכו." },
  { "word": "הפיל את חיתתו", "interpretation": "גרם לפחד." },
  { "word": "הפיס את דעתו", "interpretation": "הרגיע אותו, פייס אותו." },
  { "word": "הפך בדבר", "interpretation": "התלבט, בחן את הדבר על היבטיו השונים." },
  { "word": "הפך בדעתו", "interpretation": "התקשה להחליט." },
  { "word": "הפליא בו מכותיו", "interpretation": "הרביץ לו קשות." },
  { "word": "הפליג בשבחו", "interpretation": "שיבח." },
  { "word": "הפקיע", "interpretation": "הוציא מרשות בעליו, החרים." },
  { "word": "הפציר", "interpretation": "התחנן, סרהב, עתר." },
  { "word": "הפריז", "interpretation": "הגזים, הפליג, הגדיש את הסאה." },
  { "word": "הפריט", "interpretation": "הפך רכוש לאומי לפרטי." },
  { "word": "הפריך", "interpretation": "סתר, הזם." },
  { "word": "הפרצה קוראת לגנב", "interpretation": "דבר ללא השגחה מעודד גניבה." },
  { "word": "הצטללות", "interpretation": "היהפכות לצלול, הזדככות." },
  { "word": "הצטנפות", "interpretation": "התכרבלות, התקפלות." },
  { "word": "הציגו ככלי ריק", "interpretation": "לעג לו." },
  { "word": "הציץ ונפגע", "interpretation": "נחשף למשהו ללא הכנה ונכבש בקסמיו." },
  { "word": "הצלבה", "interpretation": "השוואת מידע שמתקבל ממקורות שונים." },
  { "word": "הצמית", "interpretation": "השמיד, הכחיד, הכרית, כילה." },
  { "word": "הצפין", "interpretation": "החביא, הסתיר, הכמין." },
  { "word": "הצר את צעדיו", "interpretation": "הפריע למעשיו, היה לו למכשול." },
  { "word": "הקדיח תבשילו", "interpretation": "קילקל." },
  { "word": "הקדיח תבשילו ברבים", "interpretation": "נהג שלא כהוגן." },
  { "word": "הקדים רפואה למכה", "interpretation": "צפה בעיה מראש ומנע אותה." },
  { "word": "הקיז", "interpretation": "הוציא דם." },
  { "word": "הקיץ", "interpretation": "התעורר." },
  { "word": "הקניט", "interpretation": "הכעיס, קנטר, עקץ, סנט." },
  { "word": "הקצה", "interpretation": "הקציב, ייחד, הועיד." },
  { "word": "הקשה את לבו", "interpretation": "סירב לסלוח או לוותר." },
  { "word": "הראהו נחת זרועו", "interpretation": "היכה אותו מכות נמרצות." },
  { "word": "הרביץ תורה", "interpretation": "הרצה, לימד." },
  { "word": "הרביק", "interpretation": "פיטם." },
  { "word": "הרהיב עוז בנפשו", "interpretation": "העז, ההין." },
  { "word": "הרואי", "interpretation": "יש בו אומץ וגבורה." },
  { "word": "הרים את קרנו", "interpretation": "שיבח אותו, האדיר." },
  { "word": "הרים מעפר", "interpretation": "שיקם, קומם." },
  { "word": "הרך הנולד", "interpretation": "כינוי לתינוק שרק נולד." },
  { "word": "הרמוניה", "interpretation": "התאמה, אידיליה, פסטורליה." },
  { "word": "הרמטי", "interpretation": "אטום לחלוטין." },
  { "word": "הרעיף", "interpretation": "1. טפטף, התיז; 2. הרבה, הכביר." },
  { "word": "הרף!", "interpretation": "הפסק, הרפה, הנח." },
  { "word": "הרשיע", "interpretation": "חייב בדין." },
  { "word": "השאה", "interpretation": "פיתוי, הסתה." },
  { "word": "השאור שבעיסה", "interpretation": "החלק החשוב ביותר." },
  { "word": "השביר", "interpretation": "מכר מזון." },
  { "word": "השבת נפש", "interpretation": "עידוד, החזרת המרץ." },
  { "word": "השבת פנים", "interpretation": "דחיית בקשה, סירוב." },
  { "word": "השגה", "interpretation": "ערעור, הערת בקורת." },
  { "word": "השחירו פניו כשולי קדרה", "interpretation": "התבייש." },
  { "word": "השחית דרכיו", "interpretation": "יצא לתרבות רעה." },
  { "word": "השיא", "interpretation": "יעץ." },
  { "word": "השיב מלחמה שערה", "interpretation": "נלחם חזרה." },
  { "word": "השיב עטרה ליושנה", "interpretation": "החזיר לגדולה." },
  { "word": "השית את לבו", "interpretation": "שם לב." },
  { "word": "השכם והערב", "interpretation": "פעמים רבות, ללא הרף." },
  { "word": "השכנה", "interpretation": "השלטה, הבאה למצב מסויים." },
  { "word": "השליך את יהבו", "interpretation": "תלה את תקוותו." },
  { "word": "השליך נפשו מנגד", "interpretation": "סיכן את חייו." },
  { "word": "השמה", "interpretation": "שיבוץ ביחידה או במקום עבודה מסוים." },
  { "word": "השנות", "interpretation": "חזרה, כפילות." },
  { "word": "השעה משחקת לו", "interpretation": "מצליח." },
  { "word": "השקה", "interpretation": "1. נגיעת דבר בדבר; 2. טקס חניכת ספינה או חפץ אחר." },
  { "word": "השריש", "interpretation": "התבסס, היכה שורש, התערה." },
  { "word": "השתאה", "interpretation": "התפלא, נדהם, השתומם." },
  { "word": "השתהה", "interpretation": "התעכב." },
  { "word": "השתכר אל צרור נקוב", "interpretation": "הפסיד את כל רווחיו." },
  { "word": "השתלח", "interpretation": "תקף." },
  { "word": "השתנקות", "interpretation": "היחנקות." },
  { "word": "השתרג", "interpretation": "השתלב." },
  { "word": "השתרך", "interpretation": "הלך לאיטו." },
  { "word": "התאבכות", "interpretation": "1. התעבות; 2.התרוממות." },
  { "word": "התאבק בעפר רגליו", "interpretation": "למד ממנו, העריץ אותו, התבטל בפניו." },
  { "word": "התאדן", "interpretation": "התנשא." },
  { "word": "התאונן", "interpretation": "התלונן, התרעם." },
  { "word": "התאמר", "interpretation": "התפאר, התיימר." },
  { "word": "התאנה", "interpretation": "התגרה, התעמר, נגש, התנכל." },
  { "word": "התאנף", "interpretation": "התרגז." },
  { "word": "התבדה", "interpretation": "לא התממשו תחזיותיו." },
  { "word": "התבדלות", "interpretation": "התרחקות מאחרים, פרישה." },
  { "word": "התבדר", "interpretation": "1. התפזר, התנפנף; 2. השתעשע." },
  { "word": "התבוסס", "interpretation": "התגלגל, התפלש." },
  { "word": "התבשם", "interpretation": "1. נמלא ריח טוב; 2. נהנה מאוד; 3. השתכר." },
  { "word": "התגודדו", "interpretation": "נאספו, התקהלו, צבאו." },
  { "word": "התגושש", "interpretation": "נאבק, התנצח, התכתש." },
  { "word": "התגלע", "interpretation": "התפרץ, התלקח." },
  { "word": "התדפק על דלתו", "interpretation": "ניסה שוב ושוב לקבל דבר מסויים." },
  { "word": "התוויה", "interpretation": "תכנון בקווים כלליים." },
  { "word": "התחבט", "interpretation": "התלבט." },
  { "word": "התחוור", "interpretation": "התברר." },
  { "word": "התחנחנות", "interpretation": "התנהגות בחן מזויף, התחנפות." },
  { "word": "התחסדות", "interpretation": "צביעות." },
  { "word": "התחקות", "interpretation": "הליכה בעקבות, חיפוש אחרי-" },
  { "word": "התחשרו", "interpretation": "נערמו." },
  { "word": "התיז", "interpretation": "1. כרת, גדע; 2. טפטף, הזיל." },
  { "word": "התייפחות", "interpretation": "געייה בבכי מר." },
  { "word": "התיר", "interpretation": "1. הרשה, איפשר; 2. שיחרר." },
  { "word": "התכתש", "interpretation": "נאבק, התגושש, התלהם." },
  { "word": "התלהם", "interpretation": "השתולל, התנצח, התכתש." },
  { "word": "התעמר", "interpretation": "התאכזר, התעלל, התאנה." },
  { "word": "התערה", "interpretation": "התבסס במקום, השתקע." },
  { "word": "התערטל", "interpretation": "התפשט, נחשף." },
  { "word": "התעשת", "interpretation": "חשב, החזיר עשתונותיו." },
  { "word": "התעתד", "interpretation": "התכונן." },
  { "word": "התפוגג", "interpretation": "נעלם, התנדף." },
  { "word": "התפכח", "interpretation": "התעורר משכרונו." },
  { "word": "התפלה", "interpretation": "הפיכת דבר מה לתפל." },
  { "word": "התפלמס", "interpretation": "התווכח, התנצח, התלהם." },
  { "word": "התפעם", "interpretation": "התרגש." },
  { "word": "התפקח", "interpretation": "הכיר במציאות, התנפצו אשליותיו." },
  { "word": "התפקר", "interpretation": "עזב את הדת, כפר, פרק עול." },
  { "word": "התפרץ לדלת פתוחה", "interpretation": "אין התנגדות." },
  { "word": "התפרקדות", "interpretation": "שכיבה על הגב בפישוק ידיים ורגליים." },
  { "word": "התפשט כאש בשדה קוצים", "interpretation": "עבר מאדם לאדם במהירות רבה." },
  { "word": "התקה", "interpretation": "הזזה, העתקה, הזחה." },
  { "word": "התקן עצמך בפרוזדור כדי שתיכנס לטרקלין", "interpretation": "יש לטרוח לפני שנהנים מפירות העמל." },
  { "word": "התקרנפות", "interpretation": "הליכה אחרי העדר, ניוון מוסרי." },
  { "word": "התקשט בנוצות זרות", "interpretation": "התפאר בדברים לא לו." },
  { "word": "התרגש", "interpretation": "התרחש." },
  { "word": "התרה", "interpretation": "הזהיר." },
  { "word": "התרועע", "interpretation": "בילה בחברת מישהו." },
  { "word": "התריס", "interpretation": "התנגד, מחה, התמרד." },
  { "word": "התרעם", "interpretation": "התלונן, התאונן, התרגז." },
  { "word": "התרפס", "interpretation": "התחנף, מלחך פנכה." },
  { "word": "התרפקות", "interpretation": "הישענות על מישהו מתוך אהבה." },
  { "word": "התרצה", "interpretation": "הסכים, נעתר, הופסה דעתו." },
  { "word": "התרת רסן", "interpretation": "נתינת חופש מוחלט." }
]
