window.het = [
  { "word": "חאן", "interpretation": "אכסניה, מלון אורחים, פונדק." },
  { "word": "חבוט", "interpretation": "נדוש, בנאלי, שאין בו עניין." },
  { "word": "חבורה", "interpretation": "פצע, חבלה, נגע." },
  { "word": "חבוש", "interpretation": "קשור, כלוא, אסור." },
  { "word": "חביצה", "interpretation": "פודינג, רפרפת." },
  { "word": "חבל", "interpretation": "1. אזור, גליל; 2. קבוצה, סיעה." },
  { "word": "חבל", "interpretation": "כאב." },
  { "word": "חבק", "interpretation": "חביקה, לפיתה, אחיזה חזקה." },
  { "word": "חברבר", "interpretation": "מנומר, בעל חברבורות." },
  { "word": "חבר מרעים", "interpretation": "חברים." },
  { "word": "חג", "interpretation": "הסתובב, סב." },
  { "word": "חגו", "interpretation": "סדק, נקיק, חריץ, נקרה, בקיע." },
  { "word": "חגר שק", "interpretation": "התאבל, נשא קינה." },
  { "word": "חדגוני", "interpretation": "משעמם, מונוטוני." },
  { "word": "חדוה", "interpretation": "שמחה, ששון, גיל, דיצה." },
  { "word": "חדור", "interpretation": "מלא, ספוג, רווי." },
  { "word": "חדל אישים", "interpretation": "לא יוצלח." },
  { "word": "חדל ישע", "interpretation": "חסר אונים." },
  { "word": "חדשים לבקרים", "interpretation": "מפעם לפעם, שוב ושוב." },
  { "word": "חוד החנית", "interpretation": "החלק העומד בראש מבצעי משימה כלשהי." },
  { "word": "חווק", "interpretation": "שלב בסולם." },
  { "word": "חוזר על הפתחים", "interpretation": "מקבץ נדבות." },
  { "word": "חוח", "interpretation": "סוג של קוץ, דרדר, חרול." },
  { "word": "חוט השני", "interpretation": "קו יסודי, תכונה אופיינית." },
  { "word": "חוט השערה", "interpretation": "דבר קטן ומועט ביותר." },
  { "word": "חוטבי עצים ושואבי מים", "interpretation": "פשוטים, חסרי השכלה, בורים." },
  { "word": "חוטם", "interpretation": "אף." },
  { "word": "חוטר", "interpretation": "1. ענף עיקרי היוצא מגזע עץ; 2. צאצא; 3. מקל דק המשמש לניקוי קנים ומקטרות." },
  { "word": "חוילה", "interpretation": "וילה, בית פרטי." },
  { "word": "חוכא ואטלולא", "interpretation": "צחוק גדול, לעג וקלס." },
  { "word": "חוכך בדעתו", "interpretation": "מהסס, מתלבט, מתחבט." },
  { "word": "חוכר", "interpretation": "שוכר קרקע או עסק." },
  { "word": "חוליגן", "interpretation": "בריון." },
  { "word": "חולש", "interpretation": "שולט, מושל." },
  { "word": "חומץ בן יין", "interpretation": "רשע בן צדיק." },
  { "word": "חומר", "interpretation": "אדמה המשמשת לקדרות, טיט." },
  { "word": "חומרה", "interpretation": "מכלול הרכיבים הפיסיים של המחשב." },
  { "word": "חוסן", "interpretation": "כוח, עוז, גבורה, און." },
  { "word": "חופן", "interpretation": "מלוא היד." },
  { "word": "חופף", "interpretation": "שווה בדיוק לאחר, זהה לגמרי." },
  { "word": "חוצב להבות אש", "interpretation": "מלהיב בדבריו." },
  { "word": "חוצן", "interpretation": "שולי הבגד." },
  { "word": "חוק דרקוני", "interpretation": "חוק לא הגיוני ושרירותי." },
  { "word": "חור", "interpretation": "אדם נכבד." },
  { "word": "חורמה", "interpretation": "השמדה, כליון, כליה, חידלון." },
  { "word": "חורשף", "interpretation": "ארטישוק, קנרס." },
  { "word": "חושך שבטו שונא בנו", "interpretation": "יש צורך ביד קשה כחלק מהחינוך." },
  { "word": "חותלת", "interpretation": "אריג שכורכים סביב שוק הרגל." },
  { "word": "חזון נפרץ", "interpretation": "תופעה שכיחה." },
  { "word": "חזקה", "interpretation": "זכות קניין ובעלות." },
  { "word": "חזקה עליו", "interpretation": "ודאי." },
  { "word": "חזר כלעומת שבא", "interpretation": "חזר בידיים ריקות." },
  { "word": "חזר לסורו", "interpretation": "שב למנהגיו הרעים." },
  { "word": "חח", "interpretation": "טבעת ברזל באף הבהמה." },
  { "word": "חט", "interpretation": "השן החדה בקדמת הפה." },
  { "word": "חט", "interpretation": "שן פיל." },
  { "word": "חטוטרת", "interpretation": "גיבנת, גבנון." },
  { "word": "חיבוטי נפש", "interpretation": "התלבטויות." },
  { "word": "חיבוטי קבר", "interpretation": "סבל רב, ייסורים." },
  { "word": "חיבוטים", "interpretation": "לבטים." },
  { "word": "חיבוץ", "interpretation": "עשיית חמאה מחלב או שמנת." },
  { "word": "חיבוק דוב", "interpretation": "קשר רגשי שחונק וכובל." },
  { "word": "חיברות", "interpretation": "הקניית ערכי החברה, סוציאליזציה." },
  { "word": "חיגר", "interpretation": "צולע, פיסח." },
  { "word": "חידוד", "interpretation": "בדיחה, שנינה, הלצה." },
  { "word": "חידלון", "interpretation": "אבדון, כליה, כליון, אפסות." },
  { "word": "חיוה", "interpretation": "אמר, הביע." },
  { "word": "חיוני", "interpretation": "1. הכרחי, לחם חוק; 2. מלא חיים ורעננות, ויטאלי." },
  { "word": "חיי שעה", "interpretation": "חיים של הנאה מהרגע, הדוניזם." },
  { "word": "חיכה עד בוש", "interpretation": "חיכה לשווא." },
  { "word": "חיל", "interpretation": "1. כוח, גבורה; 2. יכולת, הישג." },
  { "word": "חיל", "interpretation": "פחד, יראה, חרדה, אימה." },
  { "word": "חיל ורעדה", "interpretation": "פחד." },
  { "word": "חילוט", "interpretation": "קביעה מוחלטת." },
  { "word": "חילוי", "interpretation": "בקשה, תחינה, עתירה." },
  { "word": "חילול", "interpretation": "ביזוי, השפלה, הפרה." },
  { "word": "חילופי גברי", "interpretation": "שינוי באיוש תפקידים." },
  { "word": "חילחול", "interpretation": "חדירה פנימה." },
  { "word": "חילץ את עצמותיו", "interpretation": "התמתח, התאוורר." },
  { "word": "חימה", "interpretation": "כעס רב, זעם, חרון, עברה." },
  { "word": "חיסיון", "interpretation": "הגנה משפטית לשמירת סודיות." },
  { "word": "חיפוי", "interpretation": "כיסוי, ציפוי, קירוי." },
  { "word": "חיץ", "interpretation": "מחיצה, קיר מבדיל." },
  { "word": "חירוף", "interpretation": "ביזוי, גידוף, קללה." },
  { "word": "חירוף נפש", "interpretation": "סיכון עצמי." },
  { "word": "חישב להתפקע", "interpretation": "עומד להתפרק." },
  { "word": "חישול", "interpretation": "1. עיצוב, גיבוש;2. חיזוק באמצעות התנסויות מפרכות." },
  { "word": "חישור", "interpretation": "מוט המחבר בין חישוק הגלגל למרכזו." },
  { "word": "חישן", "interpretation": "הססן, חששן, רהוי, מוג לב." },
  { "word": "חישר", "interpretation": "טפטף." },
  { "word": "חיתוך דיבור", "interpretation": "צורת דיבור, מבטא." },
  { "word": "חכירה", "interpretation": "שכירת קרקע או נכס תמורת תשלום." },
  { "word": "חכלילי", "interpretation": "אדמדם, שני, סיקרה, ארגמן." },
  { "word": "חל", "interpretation": "מתרחש." },
  { "word": "חלאה", "interpretation": "לכלוך, טינופת, זוהמה, סחי." },
  { "word": "חלב", "interpretation": "כינוי לשעווה של נר." },
  { "word": "חלבו ודמו", "interpretation": "מיטב כוחותיו." },
  { "word": "חלד", "interpretation": "1. ארץ, תבל, קוסמוס; 2. חיי אדם." },
  { "word": "חלומות באספמיה", "interpretation": "חלומות לא מציאותיים, אוטופיה, אשליה." },
  { "word": "חלונות גבוהים", "interpretation": "אנשי הפקידות הגבוהה." },
  { "word": "חלופה", "interpretation": "תחליף, אלטרנטיבה." },
  { "word": "חלחולת", "interpretation": "פי הטבעת." },
  { "word": "חלחלה", "interpretation": "רעד, בהלה, חיל, פיק." },
  { "word": "חלט", "interpretation": "יצק מים רותחים, שלק, שפת." },
  { "word": "חליצה", "interpretation": "הסרת נעל מרגל היבם על-ידי אשת אחיו, שמת בלא בנים, כאות לכך שהיא פוטרת אותו מלשאת אותה לאשה." },
  { "word": "חלכאי", "interpretation": "עני, אביון, דל." },
  { "word": "חלמאי", "interpretation": "שוטה." },
  { "word": "חלפן", "interpretation": "אדם המחליף מטבעות ושטרות כסף." },
  { "word": "חלק הארי", "interpretation": "החלק הגדול ביותר." },
  { "word": "חלשה דעתו", "interpretation": "הצטער מאוד, נפלה רוחו." },
  { "word": "חם מזג", "interpretation": "אימפולסיבי, עצבני." },
  { "word": "חמד", "interpretation": "רצה, התאווה, תאב, השתוקק." },
  { "word": "חמד לצון", "interpretation": "התבדח." },
  { "word": "חמה", "interpretation": "שמש." },
  { "word": "חמור גרם", "interpretation": "טיפש, עקשן." },
  { "word": "חמס", "interpretation": "שוד, גזל." },
  { "word": "חמקמק", "interpretation": "מתחמק, מתפתל, משתמט." },
  { "word": "חמרי", "interpretation": "ארצי, גשמי, מטריאלי." },
  { "word": "חמת", "interpretation": "שק עור לנוזלים, נאד." },
  { "word": "חמתה מרובה מצילתה", "interpretation": "החיוב רב על השלילה." },
  { "word": "חנווני", "interpretation": "בעל חנות." },
  { "word": "חנוט", "interpretation": "שמור ללא שינוי, מומיה." },
  { "word": "חנחון", "interpretation": "גנדרנות, טרזנות." },
  { "word": "חס", "interpretation": "ריחם, חמל." },
  { "word": "חס על כבודו", "interpretation": "שמר על כבודו." },
  { "word": "חסה", "interpretation": "הסתתר, בטח, סמך." },
  { "word": "חסון", "interpretation": "חזק, בעל כוח רב." },
  { "word": "חסות", "interpretation": "מקלט, מחסה, אפוטרופסות." },
  { "word": "חסיד שוטה", "interpretation": "קנאי לרעיון בצורה עיוורת." },
  { "word": "חסך", "interpretation": "מחסור, גירעון, פחת." },
  { "word": "חסר שחר", "interpretation": "חסר ביסוס, חסר מובן." },
  { "word": "חף", "interpretation": "1. לא אשם; 2. נקי, צח, זך." },
  { "word": "חפוי ראש", "interpretation": "1. מבויש, נכלם; 2. אבל." },
  { "word": "חפיסה", "interpretation": "צרור, חבילה קטנה." },
  { "word": "חפיר", "interpretation": "תעלה חפורה סביב מבצר להגנה." },
  { "word": "חפן", "interpretation": "מילא את כף ידו, אחז, לפת." },
  { "word": "חפץ", "interpretation": "רצה, אבה." },
  { "word": "חפץ כפיים", "interpretation": "חריצות, שקידה." },
  { "word": "חפת", "interpretation": "קיפול של שולי הבגד כלפי מעלה." },
  { "word": "חצה את הרוביקון", "interpretation": "עשה צעד גורלי." },
  { "word": "חצובה", "interpretation": "בסיס בן שלוש רגליים להגבהה." },
  { "word": "חציצה", "interpretation": "הפרדה, הבדלה, סייג." },
  { "word": "חציר", "interpretation": "שם כולל לעשבים המשמשים למאכל בהמות." },
  { "word": "חקוק", "interpretation": "חרוט." },
  { "word": "חרב דמוקלס", "interpretation": "סכנה גדולה ומאיימת." },
  { "word": "חרב חדה מונחת על צווארו", "interpretation": "נמצא בסכנה גדולה." },
  { "word": "חרב פיפיות", "interpretation": "דבר שעשוי לפגוע בעושהו, בומרנג." },
  { "word": "חרבה", "interpretation": "יבשה, מקום יבש." },
  { "word": "חרול", "interpretation": "קוץ, דרדר, חוח." },
  { "word": "חרום", "interpretation": "פחוס או שקוע." },
  { "word": "חרון", "interpretation": "כעס, חימה, זעם, חרי." },
  { "word": "חרון אף", "interpretation": "כעס רב." },
  { "word": "חרוק שיניים", "interpretation": "זעם, רוגז רב תוך התאפקות מתגובה אלימה." },
  { "word": "חרי", "interpretation": "כעס, חרון, חימה, זעם, קצף." },
  { "word": "חריט", "interpretation": "ארנק." },
  { "word": "חריץ", "interpretation": "נתח, חתיכה, פרוסה." },
  { "word": "חרישי", "interpretation": "שקט." },
  { "word": "חרך", "interpretation": "חלון, אשנב, צוהר." },
  { "word": "חרמש", "interpretation": "כלי לקצירת תבואה המורכב מסכין בצורת קשת." },
  { "word": "חרפה", "interpretation": "בושה, כלימה, בזיון." },
  { "word": "חרץ את לשונו", "interpretation": "איים." },
  { "word": "חרצובה", "interpretation": "קשר, כבל, שלשלת." },
  { "word": "חרקירי", "interpretation": "התאבדות." },
  { "word": "חרש", "interpretation": "אומן, בעל מלאכה." },
  { "word": "חרשף", "interpretation": "ארטישוק, קנרס (גם \"חורשף\")." },
  { "word": "חרש רעה", "interpretation": "חשב להרע, התנכל, זמם." },
  { "word": "חרת", "interpretation": "חקק." },
  { "word": "חשוך", "interpretation": "מחוסר, נטול." },
  { "word": "חשוך בנים", "interpretation": "שאין לו ילדים." },
  { "word": "חשק", "interpretation": "חיבר, הצמיד." },
  { "word": "חשרה", "interpretation": "ערימה, צבר, גל, תל." },
  { "word": "חשרת עננים", "interpretation": "ערימת עננים." },
  { "word": "חת", "interpretation": "פחד, יראה, אימה, מורא." },
  { "word": "חתה", "interpretation": "גרף גחלים." },
  { "word": "חתה גחלים על ראשו", "interpretation": "גרם לו ייסורים." },
  { "word": "חתול בשק", "interpretation": "משהו שטיבו אינו ברור." },
  { "word": "חתול שחור עבר ביניהם", "interpretation": "רבו." },
  { "word": "חתיכה הראויה להתכבד בה", "interpretation": "חלק גדול." },
  { "word": "חתימת זקן", "interpretation": "סימן של זקן." },
  { "word": "חתף", "interpretation": "שוד, חטיפה." },
  { "word": "חתר", "interpretation": "1. פרץ, בקע; 2. פעל בחשאי נגד מישהו." },
  { "word": "חתרני", "interpretation": "לא נאמן\".\"" },
]
