window.kaf = [
  { "word": "כאוות נפשו", "interpretation": "ככל שליבו חפץ." },
  { "word": "כאוס", "interpretation": "אי סדר, ערבוביה, תוהו ובוהו." },
  { "word": "כאסקופה נדרסת", "interpretation": "רכרוכי." },
  { "word": "כבד-פה", "interpretation": "מגמגם, עילג, כבד לשון." },
  { "word": "כבודה", "interpretation": "רכוש, מטען, מטלטלין." },
  { "word": "כבודו במקומו מונח", "interpretation": "לא מזלזלים בו." },
  { "word": "כבול", "interpretation": "קשור, אסור." },
  { "word": "כבידה", "interpretation": "כוח המשיכה, גרביטציה." },
  { "word": "כברה", "interpretation": "מסננת, נפה." },
  { "word": "כברת-דרך", "interpretation": "מרחק מסוים." },
  { "word": "כבש", "interpretation": "סולם מדרגות כמו במטוס." },
  { "word": "כבש את יצרו", "interpretation": "התאפק, הבליג." },
  { "word": "כבש פניו בקרקע", "interpretation": "התבייש, נכלם." },
  { "word": "כבש רחמיו", "interpretation": "לא ריחם." },
  { "word": "כבשן", "interpretation": "תנור, קמין, אח, כירה." },
  { "word": "כבשת הרש", "interpretation": "מצב שבו לוקחים למישהו גם את המעט שיש לו." },
  { "word": "כדבעי", "interpretation": "כמו שצריך, כראוי, כהלכה." },
  { "word": "כדור שלג", "interpretation": "עניין פעוט שהולך וגדל." },
  { "word": "כדלקמן", "interpretation": "כמו הדברים שיובאו בהמשך, כדלהלן." },
  { "word": "כדרכו בקודש", "interpretation": "כמנהגו תמיד." },
  { "word": "כדת וכדין", "interpretation": "כהלכה, לפי הנהוג." },
  { "word": "כהו עיניו", "interpretation": "ראייתו נפגעה." },
  { "word": "כהרף עין", "interpretation": "בן-רגע, תיכף ומייד, לאלתר." },
  { "word": "כונן", "interpretation": "הקים, ייסד." },
  { "word": "כונס נכסים", "interpretation": "אחראי על הנכסים, המופקעים בפשיטת רגל." },
  { "word": "כוס תרעלה", "interpretation": "מנה של צרה ופורענות." },
  { "word": "כוסות רוח למת", "interpretation": "מעשה חסר תועלת." },
  { "word": "כופר", "interpretation": "מכחיש." },
  { "word": "כופר", "interpretation": "תשלום הנדרש כדי להציל חיים." },
  { "word": "כור היתוך", "interpretation": "מיזוג יסודות שונים למשהו חדש ואחיד." },
  { "word": "כורח", "interpretation": "הכרח, חוסר ברירה." },
  { "word": "כוריאוגרפיה", "interpretation": "בימוי של מחול." },
  { "word": "כורם", "interpretation": "בעל כרם, עובד בכרם." },
  { "word": "כותל", "interpretation": "קיר." },
  { "word": "כזב", "interpretation": "שקר, הונאה, אחיזת עיניים." },
  { "word": "כזה ראה וקדש", "interpretation": "יש לבצע את ההוראות בדיוק." },
  { "word": "כזית", "interpretation": "מעט, קמצוץ, קורט, שמץ." },
  { "word": "כחוט השני", "interpretation": "קו יסודי, דבר חוזר ונשנה." },
  { "word": "כחומר ביד היוצר", "interpretation": "נתון בידי מישהו שמכוון אותו ועושה בו כרצונו." },
  { "word": "כחוש", "interpretation": "רזה, דק גו, צנום." },
  { "word": "כחכוח", "interpretation": "חיכוך בגרון." },
  { "word": "כחש", "interpretation": "1. רזון 2. שקר, כזב." },
  { "word": "כיב", "interpretation": "פצע מוגלתי." },
  { "word": "כיבד", "interpretation": "טאטא, ניקה מאבק, אשפה וכו'." },
  { "word": "כיבן", "interpretation": "חיבר, רכס, פרף." },
  { "word": "כיו\"ב", "interpretation": "ראשי התיבות של כיוצא בזה." },
  { "word": "כיול", "interpretation": "כיוון מכשיר מדידה." },
  { "word": "כיחד", "interpretation": "הסתיר, שיקר, הכחיש, כיזב." },
  { "word": "כיכר", "interpretation": "משקל עתיק למתכות." },
  { "word": "כילה", "interpretation": "1. גמר, סיים 2. השמיד." },
  { "word": "כילה", "interpretation": "רשת מעל למיטה להגנה מפני יתושים." },
  { "word": "כילי", "interpretation": "קמצן, צייקן, קפוץ יד." },
  { "word": "כיליון עיניים", "interpretation": "קוצר רוח." },
  { "word": "כילכל את דבריו/צעדיו", "interpretation": "שקל היטב את דבריו, תכנן מראש." },
  { "word": "כימות", "interpretation": "מדידה, שקילה, הערכת הכמות." },
  { "word": "כינס רגליו", "interpretation": "נשאר במקומו." },
  { "word": "כיסופים", "interpretation": "געגועים, ערגה, כמיהה." },
  { "word": "כיסן", "interpretation": "בצק ממולא." },
  { "word": "כיפח", "interpretation": "גבוה מהרגיל, גמלוני, רם." },
  { "word": "כירה", "interpretation": "תנור, אח, קמין, כבשן." },
  { "word": "כירורג", "interpretation": "רופא מנתח." },
  { "word": "כישור", "interpretation": "קנה עליו מלפפים חוטי צמר, פלך." },
  { "word": "כיתת את רגליו", "interpretation": "הלך הרבה, התייגע בהליכה." },
  { "word": "ככתבו וכלשונו", "interpretation": "בדיוק על פי הנאמר." },
  { "word": "כל אימת ש…", "interpretation": "בכל זמן ש…" },
  { "word": "כל דאלים גבר", "interpretation": "החזק מנצח." },
  { "word": "כל דיכפין", "interpretation": "כל הנזקק למשהו." },
  { "word": "כל הפוסל במומו פוסל", "interpretation": "המצביע על חסרונות אצל אחרים, שיבדוק תחילה את עצמו." },
  { "word": "כלאחר יד", "interpretation": "בחוסר אכפתיות, כבדרך אגב." },
  { "word": "כלאיים", "interpretation": "הרכב של שני מינים." },
  { "word": "כלה", "interpretation": "1. זמני, שמסתיים בסוף 2. משתוקק, נכסף." },
  { "word": "כלה ונחרצה מעמו", "interpretation": "דעתו נחושה, החליט סופית." },
  { "word": "כלו כל הקיצין", "interpretation": "אבדה כל תקווה." },
  { "word": "כלונס", "interpretation": "מוט ארוך, קורה." },
  { "word": "כליה", "interpretation": "השמדה, אבדון, חורמה." },
  { "word": "כליחוך השור", "interpretation": "מוקדם בבוקר, השכם בבוקר." },
  { "word": "כליל", "interpretation": "לגמרי, בשלמות." },
  { "word": "כליל השלמות", "interpretation": "שיא השלמות." },
  { "word": "כלימה", "interpretation": "בושה, חרפה, בזיון, קלון." },
  { "word": "כלתה נפשו", "interpretation": "נתקף געגועים, נכסף." },
  { "word": "כמוס", "interpretation": "חבוי, סודי, גנוז, צפון." },
  { "word": "כמוסה", "interpretation": "קפסולה, שפופרת ובתוכה תרופה." },
  { "word": "כמוצא שלל רב", "interpretation": "בשמחה רבה." },
  { "word": "כמוש", "interpretation": "יבש, נבול, מצומק." },
  { "word": "כמטחווי", "interpretation": "כטווח הפגיעה." },
  { "word": "כמי שכפאו שד", "interpretation": "בחוסר רצון." },
  { "word": "כמיהה", "interpretation": "רצון עז, השתוקקות." },
  { "word": "כמלוא הנימה", "interpretation": "מעט שבמעט, כחוט השערה." },
  { "word": "כמעיין המתגבר", "interpretation": "אדם שמוסיף ליצור ולהתחדש ללא הפסק." },
  { "word": "כן", "interpretation": "בסיס, מסד, תשתית." },
  { "word": "כן", "interpretation": "דובר אמת." },
  { "word": "כנימה", "interpretation": "חרק קטן המזיק לצמחים." },
  { "word": "כנף בגד", "interpretation": "קצה הבגד." },
  { "word": "כנשוך נחש", "interpretation": "קפץ בבהלה." },
  { "word": "כסות", "interpretation": "בגד, לבוש." },
  { "word": "כסיה", "interpretation": "כפפה." },
  { "word": "כסיל", "interpretation": "טיפש, שוטה, אויל, סכל." },
  { "word": "כסיסה", "interpretation": "כרסום, גריסה ופריכה בשיניים." },
  { "word": "כספר החתום", "interpretation": "קשה לפענוח ולהבנה." },
  { "word": "כסת", "interpretation": "שמיכת נוצות." },
  { "word": "כעך", "interpretation": "בייגלה." },
  { "word": "כעלה נידף", "interpretation": "חלש וחסר אונים." },
  { "word": "כעני בפתח", "interpretation": "מושפל." },
  { "word": "כעפר הארץ", "interpretation": "אינסופי." },
  { "word": "כעצם בגרון", "interpretation": "מפריע מאוד." },
  { "word": "כעת חיה", "interpretation": "בדיוק בעוד שנה." },
  { "word": "כפה עליו הר כגיגית", "interpretation": "הכריח אותו." },
  { "word": "כפטריות אחרי הגשם", "interpretation": "דברים הצצים ומתרבים מהר ובשפע." },
  { "word": "כפיס", "interpretation": "גזר עץ." },
  { "word": "כפיר", "interpretation": "אריה צעיר, ליש, לביא, שחל." },
  { "word": "כפן", "interpretation": "רעב." },
  { "word": "כפר", "interpretation": "הכחיש." },
  { "word": "כפת", "interpretation": "קשר את הידיים והרגליים זו לזו." },
  { "word": "כפתור ופרח", "interpretation": "דבר נאה מאוד, שכיית חמדה." },
  { "word": "כקליפת השום", "interpretation": "דבר חסר ערך." },
  { "word": "כקצף על פני המים", "interpretation": "חולף מהר." },
  { "word": "כר", "interpretation": "שדה מרעה, אחו, אפר." },
  { "word": "כרה", "interpretation": "ארוחה, סעודה, טוזיג." },
  { "word": "כרוב", "interpretation": "מלאך, שרף, אראל." },
  { "word": "כרומוזום", "interpretation": "חומר חלבוני בתא החי, הנושא את המידע התורשתי." },
  { "word": "כרוניקה", "interpretation": "תיאור אירועים לפי סדר התרחשותם." },
  { "word": "כרוני", "interpretation": "תמידי, ממושך." },
  { "word": "כרזה", "interpretation": "מודעה גדולה." },
  { "word": "כריזמה", "interpretation": "קסם אישי, כושר מנהיגות." },
  { "word": "כריתות", "interpretation": "גירושין, גט." },
  { "word": "כרך", "interpretation": "1. עטף 2. חיבר." },
  { "word": "כרך", "interpretation": "עיר גדולה, מטרופולין, קרת." },
  { "word": "כרכוב", "interpretation": "1. מסילה לתליית הוילון 2. בליטה לאורך קיר או בית." },
  { "word": "כרכר", "interpretation": "רקד, פיזז." },
  { "word": "כרכשת", "interpretation": "מעי." },
  { "word": "כרסה בין שיניה", "interpretation": "אשה בהריון." },
  { "word": "כרסתן", "interpretation": "שיש לו כרס גדולה." },
  { "word": "כרע", "interpretation": "רגל, שוק של בעל-חיים." },
  { "word": "כרעם ביום בהיר", "interpretation": "לפתע פתאום." },
  { "word": "כרשה", "interpretation": "ירק מאכל הדומה לבצל." },
  { "word": "כשלג דאשתקד", "interpretation": "דבר לא רלוונטי." },
  { "word": "כשמן בעצמותיו", "interpretation": "דבר טוב." },
  { "word": "כתב חרטומים", "interpretation": "כתב מסובך שקשה לפענחו." },
  { "word": "כתב עת", "interpretation": "עיתון היוצא לאור בפרק זמן קבוע (אחת ליום, אחת לחודש וכו')." },
  { "word": "כתישת מים", "interpretation": "מעשה חסר תועלת." },
  { "word": "כתיתה", "interpretation": "1.מעיכה 2. קציצה, שניצל." },
  { "word": "כתמול שלשום", "interpretation": "כרגיל." },
  { "word": "כתש", "interpretation": "שחק, כתת, הפך לפירורים." },
]
