window.kuf = [
  { "word": "קב", "interpretation": "1. מידה קטנה; 2. משענת לנכה." },
  { "word": "קבל עם ועדה", "interpretation": "בפומבי." },
  { "word": "קבס", "interpretation": "גועל, בחילה, זרא, מיאוס." },
  { "word": "קבע מסמרות בדבר", "interpretation": "ניסח ככללים קבועים שאין לשנותם." },
  { "word": "קברניט", "interpretation": "1. מפקד אוניה או מטוס; 2. מנהיג, פרנס, נגיד, נשיא." },
  { "word": "קדומני", "interpretation": "הנמצא לפנים, קדמי." },
  { "word": "קדורני", "interpretation": "קודר." },
  { "word": "קדח", "interpretation": "חלל של קידוח." },
  { "word": "קדחתנות", "interpretation": "התלהבות מופרזת, בהילות." },
  { "word": "קדים", "interpretation": "מזרח, קדם." },
  { "word": "קדם", "interpretation": "1. תקופות קדומות; 2. צד מזרח." },
  { "word": "קדנציה", "interpretation": "תקופה קצובה לפעילות רשות נבחרת." },
  { "word": "קדר", "interpretation": "יוצר כלי חרס (ראה גם \"אבניים\")." },
  { "word": "קדרה", "interpretation": "סיר, מגס, אלפס, פרור." },
  { "word": "קהה", "interpretation": "לא חד, מטושטש, מעורפל." },
  { "word": "קהות חושים", "interpretation": "חושים שאינם חדים." },
  { "word": "קו פרשת המים", "interpretation": "נקודת זמן שממנה לא ניתן לחזור." },
  { "word": "קואופרטיב", "interpretation": "איגוד." },
  { "word": "קוב", "interpretation": "מידת נפח." },
  { "word": "קובה", "interpretation": "סוכה, אוהל, חופה." },
  { "word": "קוביוסטוס", "interpretation": "מהמר." },
  { "word": "קובלנה", "interpretation": "תלונה, טענה, מענה, תרעומת." },
  { "word": "קובע", "interpretation": "קסדה." },
  { "word": "קובעת", "interpretation": "כוס, גביע, בזיך, אגן." },
  { "word": "קוגנטיבי", "interpretation": "הכרני, ששייך להכרה." },
  { "word": "קודקס", "interpretation": "קובץ חוקים." },
  { "word": "קוהרנטי", "interpretation": "הגיוני, עקבי." },
  { "word": "קווצה", "interpretation": "קבוצה של שערות, ציצה." },
  { "word": "קוטל קנים", "interpretation": "אדם פשוט, הדיוט, בור." },
  { "word": "קולגה", "interpretation": "עמית." },
  { "word": "קולגיאליות", "interpretation": "נאמנות בין חברים." },
  { "word": "קולוניה", "interpretation": "מושבה." },
  { "word": "קולוסלי", "interpretation": "עצום, כביר, טיטני." },
  { "word": "קולינרי", "interpretation": "של אמנות הבישול, גסטרונומי." },
  { "word": "קולמוס", "interpretation": "עט, מכשיר כתיבה." },
  { "word": "קולס", "interpretation": "גבעול, קנה, קלח." },
  { "word": "קולקטיבי", "interpretation": "ציבורי, כללי, משותף." },
  { "word": "קולקציה", "interpretation": "אוסף." },
  { "word": "קומבינציה", "interpretation": "צירוף, הרכבה." },
  { "word": "קוממיות", "interpretation": "תקומה, עצמאות, ריבוניות." },
  { "word": "קומפוזיטור", "interpretation": "מלחין." },
  { "word": "קומפטנטי", "interpretation": "מתאים." },
  { "word": "קומפליקציה", "interpretation": "סיבוך." },
  { "word": "קומפנסציה", "interpretation": "פיצוי, תגמול, שיפוי." },
  { "word": "קומפקטי", "interpretation": "קטן ויעיל." },
  { "word": "קומפרומיס", "interpretation": "פשרה." },
  { "word": "קומץ", "interpretation": "כמות קטנה, קמצוץ, קורט." },
  { "word": "קונדסות", "interpretation": "מעשי שובבות, תעלולים." },
  { "word": "קונוטציה", "interpretation": "משמעות נוספת." },
  { "word": "קונוס", "interpretation": "חרוט." },
  { "word": "קונטקסט", "interpretation": "הקשר." },
  { "word": "קונטרוורסלי", "interpretation": "שנוי במחלוקת." },
  { "word": "קונטרס", "interpretation": "גיליון, רשימה, חוברת." },
  { "word": "קונסונאנס", "interpretation": "הרמוניה." },
  { "word": "קונסטיטוציה", "interpretation": "חוקה." },
  { "word": "קונסטרוקציה", "interpretation": "מבנה." },
  { "word": "קונספירציה", "interpretation": "קשר חשאי, קנוניה." },
  { "word": "קונספציה", "interpretation": "תפיסה, השקפה." },
  { "word": "קונסרבטיבי", "interpretation": "שמרני, פוריטני." },
  { "word": "קונפורמי", "interpretation": "צייתן, הולך עם הזרם." },
  { "word": "קונפליקט", "interpretation": "מאבק, עימות, ניגוד." },
  { "word": "קונצנזוס", "interpretation": "הסכמה כללית, תמימות דעים." },
  { "word": "קונצרן", "interpretation": "התאחדות מפעלים תחת הנהלה משותפת." },
  { "word": "קונקרטי", "interpretation": "ממשי, מוחשי, ריאלי." },
  { "word": "קוסמוס", "interpretation": "עולם, יקום, תבל, חלד." },
  { "word": "קוף", "interpretation": "חור המחט." },
  { "word": "קופיץ", "interpretation": "סכין לחיתוך בשר." },
  { "word": "קופת שרצים", "interpretation": "אוסף עבירות ועניינים מפוקפקים שיש לאדם." },
  { "word": "קוצו של יוד", "interpretation": "דבר קטן וחסר ערך." },
  { "word": "קוצר יד", "interpretation": "חוסר יכולת, אין אונים." },
  { "word": "קוקטי", "interpretation": "גנדרני, מתחנחן, מטורזן." },
  { "word": "קור רוח", "interpretation": "שליטה עצמית." },
  { "word": "קורט", "interpretation": "מידה קטנה, מעט." },
  { "word": "קורטוב", "interpretation": "כמות מועטה, שמץ." },
  { "word": "קוריוז", "interpretation": "מקרה מבדח." },
  { "word": "קורלציה", "interpretation": "מתאם, קשר של שני גדלים." },
  { "word": "קורנס", "interpretation": "פטיש כבד, מקוב, מקבת." },
  { "word": "קורקטי", "interpretation": "הוגן, ראוי, נאות, הולם." },
  { "word": "קורת רוח", "interpretation": "הנאה, שביעות רצון." },
  { "word": "קושיה", "interpretation": "שאלה קשה." },
  { "word": "קושן", "interpretation": "תעודת רישום של קרקע." },
  { "word": "קושש", "interpretation": "אסף, ליקט, גיבב, צבר." },
  { "word": "קזוס בלי", "interpretation": "עילה למלחמה." },
  { "word": "קטגורי", "interpretation": "מוחלט." },
  { "word": "קטום", "interpretation": "שנכרת ראשו." },
  { "word": "קטליזטור", "interpretation": "זרז." },
  { "word": "קטרוג", "interpretation": "האשמה." },
  { "word": "קיבוץ גלויות", "interpretation": "התכנסות יהודים מרחבי העולם לארץ ישראל (ראה גם \"פזורה\")." },
  { "word": "קיבורת", "interpretation": "שריר הזרוע." },
  { "word": "קיבר", "interpretation": "קמח גס." },
  { "word": "קידושין", "interpretation": "נישואין." },
  { "word": "קיטון", "interpretation": "חדר קטן." },
  { "word": "קיטע", "interpretation": "קטוע יד או רגל." },
  { "word": "קילס", "interpretation": "1. לעג, גידף; 2. שיבח, הילל." },
  { "word": "קינרס", "interpretation": "ארטישוק." },
  { "word": "קיפד", "interpretation": "חתך." },
  { "word": "קיקיוני", "interpretation": "ארעי." },
  { "word": "קירזול", "interpretation": "סלסול." },
  { "word": "קיתון", "interpretation": "כד, עביט, יורה." },
  { "word": "קיתונות", "interpretation": "כמות גדולה." },
  { "word": "קל וחומר", "interpretation": "ודאי, על אחת כמה וכמה." },
  { "word": "קלגס", "interpretation": "חייל אכזר, השייך לצבא כובש." },
  { "word": "קלון", "interpretation": "בושה, כלימה, ביזיון, חרפה." },
  { "word": "קלוש", "interpretation": "דליל." },
  { "word": "קלח", "interpretation": "זרם." },
  { "word": "קלחת", "interpretation": "סיר גדול, קדרה, פרור." },
  { "word": "קלי", "interpretation": "טוסט, צנים, פכסם." },
  { "word": "קליבר", "interpretation": "1. קוטר צינור חלול; 2. קנה מידה, טיב, שיעור." },
  { "word": "קליגרפיה", "interpretation": "כתיבה תמה." },
  { "word": "קליני", "interpretation": "רפואי." },
  { "word": "קלישאה", "interpretation": "שבלונה, ביטוי נדוש." },
  { "word": "קלל", "interpretation": "מבריק, מלוטש." },
  { "word": "קליסיפיקציה", "interpretation": "מיון." },
  { "word": "קלסתר פנים", "interpretation": "תווי פנים של אדם." },
  { "word": "קלע", "interpretation": "מיידה אבנים קטנות, רוגטקה." },
  { "word": "קלפטומן", "interpretation": "בעל דחף לגנוב." },
  { "word": "קלקל את השורה", "interpretation": "סטה מדרך הישר." },
  { "word": "קם", "interpretation": "אויב, שונא, צר, צורר, רודף." },
  { "word": "קמאי", "interpretation": "ראשוני, קדמון, היולי." },
  { "word": "קמה", "interpretation": "שם כולל לתבואה לפני הקציר." },
  { "word": "קמה בו רוח", "interpretation": "לא פחד." },
  { "word": "קמטר", "interpretation": "שידה, ארונית." },
  { "word": "קמילה", "interpretation": "נבילה, כמישה, התייבשות." },
  { "word": "קמין", "interpretation": "תנור, אח, כירה, כבשן." },
  { "word": "קמעה", "interpretation": "מעט, קצת, קורט, קורטוב." },
  { "word": "קמרון", "interpretation": "כיפה, בליטה." },
  { "word": "קנה אחיזה", "interpretation": "תפס." },
  { "word": "קנה במשיכה", "interpretation": "גנב." },
  { "word": "קנה לו שם", "interpretation": "התפרסם." },
  { "word": "קנה עולמו", "interpretation": "זכה להצלחה רבה." },
  { "word": "קנה שביתה", "interpretation": "התיישב במקום, נאחז בו." },
  { "word": "קנוניה", "interpretation": "הסכם חשאי, קונספירציה." },
  { "word": "קנוקנת", "interpretation": "גבעול דק, המאפשר לצמח להיאחז בקיר." },
  { "word": "קניין", "interpretation": "רכוש." },
  { "word": "קנרס", "interpretation": "ארטישוק, חרשף, חורשף." },
  { "word": "קסרקטין", "interpretation": "מחנה צבאי." },
  { "word": "קסת", "interpretation": "כלי לדיו, דיותה." },
  { "word": "קעור", "interpretation": "שקוע כלפי פנים." },
  { "word": "קפא על שמריו", "interpretation": "לא השתנה." },
  { "word": "קפוץ יד", "interpretation": "קמצן, צייקן." },
  { "word": "קפיטלי", "interpretation": "ראשי." },
  { "word": "קפלה", "interpretation": "כנסייה קתולית." },
  { "word": "קפלט", "interpretation": "פאה נוכרית." },
  { "word": "קפץ", "interpretation": "סגר, קמץ." },
  { "word": "קפץ פיו", "interpretation": "השתתק, נדם, נאלם דום." },
  { "word": "קפריזי", "interpretation": "גחמני." },
  { "word": "קץ", "interpretation": "מאס, בחל, תיעב, היה לו לזרא." },
  { "word": "קצף", "interpretation": "כעס, חימה, חרון, חרי אף." },
  { "word": "קצר רוח", "interpretation": "חסר סבלנות, רגזן." },
  { "word": "קצרה ידו", "interpretation": "לא יכול לעזור." },
  { "word": "קרא לו דרור", "interpretation": "שחרר אותו." },
  { "word": "קרא תיגר", "interpretation": "ערער, התריס, יצא נגד." },
  { "word": "קרביים", "interpretation": "חלקי גוף פנימיים." },
  { "word": "קרדום", "interpretation": "גרזן." },
  { "word": "קרדום לחפור בו", "interpretation": "ניצל דבר לתועלתו." },
  { "word": "קרדיט", "interpretation": "אשראי, הקפה." },
  { "word": "קרדינאל", "interpretation": "דרגת כמורה בכירה." },
  { "word": "קרדינאלי", "interpretation": "עיקרי, יסודי, חשוב." },
  { "word": "קרוא", "interpretation": "אורח, מוזמן." },
  { "word": "קרוב לוודאי", "interpretation": "ככל הנראה, יש להניח." },
  { "word": "קרוי", "interpretation": "התקנת תקרה, חיפוי, סיכוך." },
  { "word": "קרוץ", "interpretation": "חצוב, נוצר, עשוי." },
  { "word": "קרוש", "interpretation": "יבש." },
  { "word": "קרטל", "interpretation": "איגוד של חברות לשם שמירת המונופול." },
  { "word": "קריה", "interpretation": "עיר, כרך, מטרופולין, קרת." },
  { "word": "קריטריון", "interpretation": "אמת מידה, אבן בוחן." },
  { "word": "קרם עור וגידים", "interpretation": "הלך ונוצר, מומש באופן מעשי." },
  { "word": "קרן זווית", "interpretation": "פינה." },
  { "word": "קרס", "interpretation": "וו, אנקול." },
  { "word": "קרע קרע", "interpretation": "התאבל, נשא קינה." },
  { "word": "קרפיף", "interpretation": "שטח גדור, עזרה." },
  { "word": "קרקע בתולה", "interpretation": "אדמה שלא עובדה מעולם, עניין שלא עסקו בו." },
  { "word": "קרת", "interpretation": "עיר קטנה, כרך, קריה." },
  { "word": "קרתן", "interpretation": "בן עיר קטנה שאינו בקי בהליכות העיר, תמים." },
  { "word": "קש וגבבה", "interpretation": "דברים חסרי חשיבות." },
  { "word": "קשה עורף", "interpretation": "עקשן, סרבן." },
  { "word": "קשר גורדי", "interpretation": "תסבוכת שקשה לצאת ממנה." },
  { "word": "קשר כתרים", "interpretation": "הילל, שיבח, קילס." },
  { "word": "קשה יום", "interpretation": "מסכן." },
  { "word": "קתדרה", "interpretation": "כיסא כבוד, דוכן." }
]
