window.lamed = [
  { "word": "לא אחת", "interpretation": "מדי פעם, לעתים מזומנות." },
  { "word": "לא בכדי", "interpretation": "לא לחינם, לא לשווא." },
  { "word": "לא דובים ולא יער", "interpretation": "לא היו דברים מעולם." },
  { "word": "לא הניד עפעף", "interpretation": "בקור רוח." },
  { "word": "לא יכירנו מקומו", "interpretation": "לא מתאים לסביבתו." },
  { "word": "לא יסולא בפז", "interpretation": "יקר מאוד." },
  { "word": "לא יצאה שעה קלה עד", "interpretation": "לא עבר זמן רב." },
  { "word": "לא כל שכן", "interpretation": "בוודאי ובוודאי, אדרבא." },
  { "word": "לא ליקק דבש", "interpretation": "התאמץ." },
  { "word": "לא לעולם חוסן", "interpretation": "אין חסינות מפני כישלון." },
  { "word": "לא מאהבת מרדכי אלא משנאת המן", "interpretation": "בחירה באופציה הפחות גרועה." },
  { "word": "לא מדובשך ולא מעוקצך", "interpretation": "אל תשבח ואל תגנה." },
  { "word": "לא מעלה ולא מוריד", "interpretation": "לא משנה דבר." },
  { "word": "לא משתמע לשתי פנים", "interpretation": "חד משמעי." },
  { "word": "לא נס ליחו", "interpretation": "עדיין כוחו במותניו." },
  { "word": "לא נקף אצבע", "interpretation": "לא התערב, ישב בחיבוק ידיים." },
  { "word": "לא ראי זה כראי זה", "interpretation": "אין שני הדברים דומים." },
  { "word": "לא תחסום שור בדישו", "interpretation": "גישה סלחנית למעשי מעילה שוליים." },
  { "word": "לאבות", "interpretation": "לרצות (משמש לרוב בשלילה)." },
  { "word": "לאבק", "interpretation": "לנקות מאבק." },
  { "word": "לאה", "interpretation": "עייף, יעף, יגע, אפס כוחו." },
  { "word": "לאומני", "interpretation": "פטריוט." },
  { "word": "לאט", "interpretation": "לחש." },
  { "word": "לאין שיעור", "interpretation": "ללא גבול." },
  { "word": "לאלתר", "interpretation": "תיכף ומיד." },
  { "word": "לאשורו", "interpretation": "במדויק." },
  { "word": "לב אבן", "interpretation": "אכזריות, חוסר רחמים." },
  { "word": "לב בשר", "interpretation": "רחמנות, רכות." },
  { "word": "לבו טוב עליו", "interpretation": "מרוצה." },
  { "word": "לבו נוקפו", "interpretation": "מתחרט." },
  { "word": "לביא", "interpretation": "אריה, ליש, כפיר, שחל." },
  { "word": "לבילי", "interpretation": "בלתי יציב." },
  { "word": "לבירינת", "interpretation": "מבוך." },
  { "word": "לבל", "interpretation": "כדי שלא, פן, שמא." },
  { "word": "לבלר", "interpretation": "פקיד, מזכיר, טפסר." },
  { "word": "לגאלי", "interpretation": "חוקי." },
  { "word": "לגטו", "interpretation": "בנשימה אחת, ללא הפסקה (במקור מונח מוסיקאלי)." },
  { "word": "לגיון", "interpretation": "יחידה צבאית גדולה." },
  { "word": "לגיטימי", "interpretation": "חוקי, לגאלי, קביל." },
  { "word": "לגין", "interpretation": "1. כד; 2. קופסה, תיבה." },
  { "word": "לדאבונו", "interpretation": "לצערו, להוותו." },
  { "word": "לדגול", "interpretation": "להאמין במשהו ולהפוך אותו לאידיאל." },
  { "word": "לדידו", "interpretation": "לגביו, מצידו." },
  { "word": "לדלוק", "interpretation": "לרדוף." },
  { "word": "להב", "interpretation": "החלק החד של סכין או חרב." },
  { "word": "להג", "interpretation": "פטפוט, דברי הבאי והבל." },
  { "word": "להד\"ם", "interpretation": "ראשי התיבות של לא היו הדברים מעולם, הדברים אינם אמת." },
  { "word": "להה", "interpretation": "עייף, לאה, יגע." },
  { "word": "להוותו", "interpretation": "לצערו, לדאבונו, לרוע מזלו." },
  { "word": "להלכה", "interpretation": "באופן תיאורטי, בכוח, דה יורה." },
  { "word": "להלן", "interpretation": "בהמשך." },
  { "word": "להקל ראש", "interpretation": "לזלזל." },
  { "word": "לוגיקה", "interpretation": "תורת ההיגיון." },
  { "word": "לוז", "interpretation": "יסוד, תמצית, עיקר, לשד." },
  { "word": "לוז", "interpretation": "שקד." },
  { "word": "לוח חלק", "interpretation": "אין לו דיעות או ידע מוקדם, טאבולה ראזה." },
  { "word": "לוט", "interpretation": "1. עטוף, מכוסה; 2. חומר המצורף למכתב." },
  { "word": "לוט בערפל", "interpretation": "לא ברור, לא ידוע." },
  { "word": "לוליני", "interpretation": "סלילי." },
  { "word": "לויאלי", "interpretation": "נאמן, שומר אמונים." },
  { "word": "לוקאלי", "interpretation": "מקומי." },
  { "word": "לזות שפתיים", "interpretation": "רכילות מרושעת." },
  { "word": "לחלוחית", "interpretation": "רטיבות, לחות." },
  { "word": "לחם חוק", "interpretation": "דבר שאין לוותר עליו, חיוני." },
  { "word": "לחם חוקו", "interpretation": "הרגל שיש לו, עניין שבשגרה." },
  { "word": "לחם חסד", "interpretation": "דבר שניתן בנדבה או במתנה." },
  { "word": "לחם צר", "interpretation": "מזון מועט ומצומצם." },
  { "word": "לטיפונדיה", "interpretation": "אחוזה." },
  { "word": "לטישת עיניים", "interpretation": "נעיצת מבט ממושך." },
  { "word": "לטנטי", "interpretation": "חבוי, סמוי, כמוס, צפון, גנוז." },
  { "word": "ליבה", "interpretation": "גרעין, לב, החלק המרכזי." },
  { "word": "ליבוי", "interpretation": "הגברה, גירוי." },
  { "word": "ליבוי יצרים", "interpretation": "שילהוב, הגברת היצרים." },
  { "word": "ליבון", "interpretation": "בירור, הבהרה." },
  { "word": "ליברה", "interpretation": "יחידת משקל, ליטרה." },
  { "word": "ליברל", "interpretation": "שואף לחירות הפרט ולפיתוח היוזמה החופשית." },
  { "word": "ליחוך פינכה", "interpretation": "חנופה, התרפסות." },
  { "word": "ליחך", "interpretation": "1. נגס, לעס; 2. השמיד, כילה." },
  { "word": "ליטוש", "interpretation": "1. שפשוף, השחזה; 2. שיפור, שכלול, עיבוד (בעיקר של יצירה)." },
  { "word": "ליטרה", "interpretation": "יחידת משקל, ליברה." },
  { "word": "ליל שימורים", "interpretation": "לילה שלא ישנים בו." },
  { "word": "לילות כימים", "interpretation": "עבודה מאומצת." },
  { "word": "לימד זכות", "interpretation": "טען לטובת מישהו, סניגור." },
  { "word": "לימד חובה", "interpretation": "טען לחובת מישהו, קיטרג." },
  { "word": "ליסטים", "interpretation": "שודד, גזלן." },
  { "word": "לירה", "interpretation": "כלי פריטה." },
  { "word": "לירי", "interpretation": "פיוטי." },
  { "word": "ליש", "interpretation": "אריה, כפיר, לביא, שחל." },
  { "word": "לית", "interpretation": "אין." },
  { "word": "לית דין ולית דין", "interpretation": "אין משפט ואין שופט, איש הישר בעיניו יעשה." },
  { "word": "לית מאן דפליג", "interpretation": "אין התנגדות, אין חולק, אין עליו עוררין." },
  { "word": "ללא כחל וסרק", "interpretation": "בגלוי, ישירות." },
  { "word": "ללא רבב", "interpretation": "מושלם, ללא דופי." },
  { "word": "למגינת ליבם", "interpretation": "לצערם." },
  { "word": "למוד סבל", "interpretation": "מורגל בסבל." },
  { "word": "למותר", "interpretation": "מיותר, לא נחוץ." },
  { "word": "למכביר", "interpretation": "בשפע, הרבה." },
  { "word": "למפרע", "interpretation": "1. על מה שכבר נעשה, בדיעבד; 2. מראש, אפריורי." },
  { "word": "למצער", "interpretation": "לכל הפחות, מינימלי." },
  { "word": "למראית עין", "interpretation": "כלפי חוץ, לכאורה." },
  { "word": "למרגלותיו", "interpretation": "ליד רגליו. בהשאלה: בחלק הנמוך שלו." },
  { "word": "למשעי", "interpretation": "נקי ביותר, באופן חלק." },
  { "word": "לן", "interpretation": "ישן." },
  { "word": "לנוכח", "interpretation": "לנגד." },
  { "word": "לסוטה", "interpretation": "מעיל נשים קצר, עליונית." },
  { "word": "לעג לרש", "interpretation": "להזכיר לאדם את חולשתו." },
  { "word": "לעו דבריו", "interpretation": "דיבר לא ברור." },
  { "word": "לעז", "interpretation": "שם רע, דיבה, גנות." },
  { "word": "לעט", "interpretation": "אכל, בלע, זלל." },
  { "word": "לעיל", "interpretation": "למעלה, קודם לכן." },
  { "word": "לעילא ולעילא", "interpretation": "משובח, הטוב ביותר." },
  { "word": "לפדות", "interpretation": "להחזיר, להשיב." },
  { "word": "לפי עניות דעתי", "interpretation": "אמירת הצטנעות למי שמביע דעה מנוגדת." },
  { "word": "לפלות", "interpretation": "להוציא כינים." },
  { "word": "לפלל", "interpretation": "לקוות, לצפות, לייחל." },
  { "word": "לפנים משורת הדין", "interpretation": "הקלה בדין, סלחנות." },
  { "word": "לפעות", "interpretation": "לגעות, להשמיע קול יבבה." },
  { "word": "לפרקים", "interpretation": "לפעמים, לעיתים." },
  { "word": "לפת", "interpretation": "תפס, אחז, חפן." },
  { "word": "לפתח חטאת רובץ", "interpretation": "החטא מפתה." },
  { "word": "לץ", "interpretation": "ליצן, מרבה לצחוק, קל דעת." },
  { "word": "לצון", "interpretation": "צחוק, היתול, ליצנות, מהתלה." },
  { "word": "לקוני", "interpretation": "קצר ותמציתי, ענייני." },
  { "word": "לקות", "interpretation": "ליקוי, פגם, מום בגוף או בנפש." },
  { "word": "לקח עיתותיו בידיו", "interpretation": "לקח את הזמן." },
  { "word": "לקט", "interpretation": "אוסף." },
  { "word": "לקיש", "interpretation": "מאחר לבוא." },
  { "word": "לרבות", "interpretation": "ובכלל זה." },
  { "word": "לריק", "interpretation": "לחינם, לשווא, בכדי." },
  { "word": "לרפות ידי מישהו", "interpretation": "לייאש." },
  { "word": "לשבט או לחסד", "interpretation": "לטוב או לרע, לזכות או לחובה." },
  { "word": "לשד", "interpretation": "תמצית, לוז." },
  { "word": "לשון בני אדם", "interpretation": "שפה ברורה ומובנת." },
  { "word": "לשון הרע", "interpretation": "רכילות, דיבה, לעז." },
  { "word": "לשון סגי נהור", "interpretation": "שימוש במילה במשמעות הפוכה." },
  { "word": "לשון שקוצים", "interpretation": "ניבול פה." },
  { "word": "לשיעורין", "interpretation": "טיפין טיפין, לא בבת אחת." },
  { "word": "לשם שמים", "interpretation": "לא לתועלת אישית." },
  { "word": "לשרש", "interpretation": "לעקור מהשורש." },
]
