window.mem = [
  { "word": "מאגרא רמה לבירא עמיקתא", "interpretation": "מעבר ממעמד גבוה לשפל המדרגה." },
  { "word": "מאוזוליאום", "interpretation": "מקדש קבורה, סרקופג." },
  { "word": "מאויים", "interpretation": "רצונות, חשקים, כיסופים, ערגה." },
  { "word": "מאי נפקא מינא", "interpretation": "לשם מה? מה ההבדל?" },
  { "word": "מאידך גיסא", "interpretation": "מצד שני." },
  { "word": "מאכלת", "interpretation": "סכין שחיטה." },
  { "word": "מאן", "interpretation": "סירב." },
  { "word": "מאן דהו", "interpretation": "מישהו, אלמוני." },
  { "word": "מאניה", "interpretation": "שיגעון." },
  { "word": "מאסף", "interpretation": "מי שנע בסוף הטור או השיירה." },
  { "word": "מאפליה", "interpretation": "חושך, אפלה, אופל, עלטה." },
  { "word": "מארה", "interpretation": "קללה, אלה, גידוף, חירוף." },
  { "word": "מבאיש", "interpretation": "מצחין, מסריח." },
  { "word": "מבדה", "interpretation": "משהו בדוי." },
  { "word": "מבדוק", "interpretation": "מזח לבדיקה ולתיקון אוניות." },
  { "word": "מבהיק", "interpretation": "מבריק, בוהק." },
  { "word": "מבואה", "interpretation": "לובי, אולם כניסה במבנה ציבורי." },
  { "word": "מבואר", "interpretation": "ברור, מוסבר." },
  { "word": "מבוי סתום", "interpretation": "ללא מוצא." },
  { "word": "מבולק", "interpretation": "נתון באי סדר." },
  { "word": "מבוסם", "interpretation": "שיכור, סובא, בגילופין." },
  { "word": "מבותק", "interpretation": "משוסע, חתוך, מבותר, מבוקע." },
  { "word": "מבכירה", "interpretation": "היולדת או הממליטה הראשונה." },
  { "word": "מבלי משים", "interpretation": "בלי כוונה." },
  { "word": "מבעית", "interpretation": "מבהיל." },
  { "word": "מג", "interpretation": "מכשף, קוסם, מעונן, ידעוני." },
  { "word": "מגד", "interpretation": "מתוק." },
  { "word": "מגדל שן", "interpretation": "מצב של התרחקות מהציבור והתבודדות מתוך התנשאות." },
  { "word": "מגדנות", "interpretation": "ממתקים, תיקרובת." },
  { "word": "מגואל", "interpretation": "מלוכלך, מזוהם, נאלח, עקוב." },
  { "word": "מגוב", "interpretation": "מגרפה." },
  { "word": "מגולוון", "interpretation": "מצופה מתכת." },
  { "word": "מגור", "interpretation": "פחד, אימה, יראה, מורא." },
  { "word": "מגזר", "interpretation": "אזור, סקטור." },
  { "word": "מגיה", "interpretation": "קסם, כישוף, להטים." },
  { "word": "מגיה", "interpretation": "מי שתפקידו לבצע הגהה." },
  { "word": "מגינת לב", "interpretation": "עוגמת נפש." },
  { "word": "מגל", "interpretation": "מכשיר לקצירת תבואה." },
  { "word": "מגלב", "interpretation": "שוט, פרגול, שבט." },
  { "word": "מגלומניה", "interpretation": "שיגעון גדלות." },
  { "word": "מגס", "interpretation": "קערה, סיר, קלחת, דוד, קדירה." },
  { "word": "מגרעה", "interpretation": "שקע, גומחה, מגרעת." },
  { "word": "מגרעת", "interpretation": "1. חיסרון, פגם; 2. שקע." },
  { "word": "מדד לו כמידתו", "interpretation": "שילם לו כגמולו." },
  { "word": "מדובלל", "interpretation": "דליל, מודלל, קלוש." },
  { "word": "מדוה", "interpretation": "כאב, מחלה, דווי." },
  { "word": "מדוכה", "interpretation": "מכתש, כלי לכתישת דברים יבשים." },
  { "word": "מדון", "interpretation": "ריב, קטטה." },
  { "word": "מדושן עונג", "interpretation": "נהנה, שבע נחת." },
  { "word": "מדיח", "interpretation": "מסית." },
  { "word": "מדמנה", "interpretation": "מזבלה." },
  { "word": "מדרשה", "interpretation": "מוסד להשכלה על-תיכונית." },
  { "word": "מה יום מיומיים?", "interpretation": "מה החידוש?" },
  { "word": "מה עניין שמיטה להר סיני?", "interpretation": "אין קשר בין הדברים." },
  { "word": "מהביל", "interpretation": "מעלה אדים." },
  { "word": "מהדר", "interpretation": "מקפיד." },
  { "word": "מהוה", "interpretation": "שחוק, בלוי, דהוי, מרופט." },
  { "word": "מהוקצע", "interpretation": "מוחלק, מלוטש." },
  { "word": "מהימן", "interpretation": "אמין." },
  { "word": "מהיר חימה", "interpretation": "עצבני, נוטה להתרגז במהירות." },
  { "word": "מהיר לאבד", "interpretation": "שכחן." },
  { "word": "מהיר לשמוע", "interpretation": "בעל תפישה טובה." },
  { "word": "מהל", "interpretation": "ערבב, מזג." },
  { "word": "מהלך באמצע", "interpretation": "מתון." },
  { "word": "מהלך בין הטיפות", "interpretation": "נזהר זהירות יתרה." },
  { "word": "מהלך על חבל דק", "interpretation": "מצבו עדין." },
  { "word": "מהמורה", "interpretation": "בור, שוחה, מכשול, אבן נגף." },
  { "word": "מהשפה ולחוץ", "interpretation": "דיבור שאינו תואם את המחשבה." },
  { "word": "מהתלה", "interpretation": "בדיחה, לצון, היתול." },
  { "word": "מובאה", "interpretation": "ציטוט." },
  { "word": "מובלעת", "interpretation": "חבל ארץ במדינה, המוקף שטחי אדמה של מדינה אחרת." },
  { "word": "מוביליות", "interpretation": "ניידות." },
  { "word": "מוג לב", "interpretation": "פחדן, רך לב, חיישן, רהוי." },
  { "word": "מוגף", "interpretation": "סגור." },
  { "word": "מודוס אופרנדי", "interpretation": "שיטת פעולה אופיינית של אדם." },
  { "word": "מוזה", "interpretation": "השראה." },
  { "word": "מוטב", "interpretation": "עדיף, טוב יותר." },
  { "word": "מוטו", "interpretation": "אימרה קצרה, המהווה עיקרון התנהגות, נר לרגליו." },
  { "word": "מוטיב", "interpretation": "רעיון, נושא." },
  { "word": "מוטציה", "interpretation": "שינוי גנטי, המביא להיווצרות זן חדש בחי או בצומח." },
  { "word": "מוך", "interpretation": "דבר רך כצמר גפן, פלומת נוצות." },
  { "word": "מוכיח בשער", "interpretation": "מבקר, מוקיע, מגנה." },
  { "word": "מולל", "interpretation": "גלגל באצבעות, מעך, שפשף." },
  { "word": "מולקולה", "interpretation": "חלקיק, פרודה." },
  { "word": "מום", "interpretation": "פגם, ליקוי, מגרעת." },
  { "word": "מונוגמיה", "interpretation": "נשיאת אישה אחת בלבד." },
  { "word": "מונוגרמה", "interpretation": "ראשי תיבות, הכתובים בצורה אומנותית." },
  { "word": "מונוטוני", "interpretation": "חדגוני, משעמם." },
  { "word": "מונולוג", "interpretation": "שיחת יחיד." },
  { "word": "מונוליטי", "interpretation": "שלם, אחיד." },
  { "word": "מונומנטלי", "interpretation": "גדול מאוד, עצום, כביר." },
  { "word": "מונופול", "interpretation": "שליטה בלעדית בתחום כלשהו, ללא מתחרים." },
  { "word": "מונוקל", "interpretation": "משקפיים לעין אחת." },
  { "word": "מונותאיזם", "interpretation": "אמונה באל אחד." },
  { "word": "מוניטין", "interpretation": "שם טוב, פרסום." },
  { "word": "מוניטרי", "interpretation": "כספי, הקשור לכסף." },
  { "word": "מוניציפלי", "interpretation": "עירוני." },
  { "word": "מונרכיה", "interpretation": "מלכות, שלטון מלך יחיד." },
  { "word": "מוסר כליות", "interpretation": "חרטה, נקיפות מצפון." },
  { "word": "מוסרה", "interpretation": "חבל לרתימת בהמה לעגלה." },
  { "word": "מועד", "interpretation": "חג." },
  { "word": "מועד", "interpretation": "עלול, ידוע מראש." },
  { "word": "מועל יד", "interpretation": "הרמת יד." },
  { "word": "מופז", "interpretation": "מוזהב." },
  { "word": "ופלג", "interpretation": "שדרגתו גבוהה או שמידתו גדולה." },
  { "word": "מופשט", "interpretation": "חסר קיום פיזי, אבסטרקטי." },
  { "word": "מופשל", "interpretation": "מקופל." },
  { "word": "מוץ", "interpretation": "פסולת התבואה." },
  { "word": "מוקד", "interpretation": "1. מדורה, תופת 2. מרכז, עיקר." },
  { "word": "מוקצה מחמת מיאוס", "interpretation": "שאין לנגוע בו, מנודה." },
  { "word": "מורא", "interpretation": "פחד, יראה, אימה, מגור, חרדה." },
  { "word": "מורבידיות", "interpretation": "חולניות." },
  { "word": "מורג", "interpretation": "כלי דיש." },
  { "word": "מורטוריום", "interpretation": "שמיטת חובות." },
  { "word": "מורך לב", "interpretation": "פחדנות." },
  { "word": "מורסה", "interpretation": "פצע מוגלתי." },
  { "word": "מורשה", "interpretation": "ירושה, נחלה, אחוזה." },
  { "word": "מורת רוח", "interpretation": "רוגז, צער." },
  { "word": "מושך בחוטים", "interpretation": "מפעיל השפעתו בסתר." },
  { "word": "מושך בעט", "interpretation": "עוסק בכתיבה." },
  { "word": "מושל בכיפה", "interpretation": "שולט ביד רמה." },
  { "word": "מושל ברוחו", "interpretation": "מתאפק, שולט בעצמו." },
  { "word": "מזה רעב", "interpretation": "מורעב." },
  { "word": "מזוה", "interpretation": "חדר או ארון למוצרי מזון." },
  { "word": "מזור", "interpretation": "1. חולי, מכאוב 2. תרופה." },
  { "word": "מזכר", "interpretation": "מכתב משרדי קצר ובלתי רשמי." },
  { "word": "מזמרה", "interpretation": "מספריים גדולים לקיצוץ ענפים." },
  { "word": "מחבוש", "interpretation": "כליאה, הכנסה למעצר." },
  { "word": "מחבצה", "interpretation": "מתקן להכנת חמאה." },
  { "word": "מחד גיסא", "interpretation": "מצד אחד." },
  { "word": "מחה", "interpretation": "התנגד, ערער." },
  { "word": "מחווה", "interpretation": "תנועת גוף להעברת מסר, ג'סטה." },
  { "word": "מחוור", "interpretation": "ברור, נהיר, בהיר." },
  { "word": "מחוטט", "interpretation": "מצולק." },
  { "word": "מחויט", "interpretation": "תפור, רקום, מהודר." },
  { "word": "מחולל", "interpretation": "1. יוצר, גורם 2. מתקן יצור חשמל (ראה \"טורבינה\" ו\"גנראטור\") 3. רקדן, רוקד 4. טמא, מזוהם, איבד את קדושתו." },
  { "word": "מחונחן", "interpretation": "מלא חן." },
  { "word": "מחופה", "interpretation": "מכוסה, מקורה, לוט." },
  { "word": "מחושים", "interpretation": "כאבים." },
  { "word": "מחושים", "interpretation": "איברי חישה שיש לחיות שונות." },
  { "word": "מחט", "interpretation": "ניקה, קינח את אפו." },
  { "word": "מחי", "interpretation": "מכה, מהלומה." },
  { "word": "מחית", "interpretation": "רסק." },
  { "word": "מחלפה", "interpretation": "קווצת שיער, צמה." },
  { "word": "מחמלי", "interpretation": "אהובי." },
  { "word": "מחמת", "interpretation": "בגלל, מפני, משום, מפאת." },
  { "word": "מחפיר", "interpretation": "מבייש, גורם חרפה." },
  { "word": "מחצלת", "interpretation": "שטיח." },
  { "word": "מחרחר ריב", "interpretation": "סכסכן." },
  { "word": "מחתה", "interpretation": "יעה המשמש לטיפול בגחלים." },
  { "word": "מט לנפול", "interpretation": "נוטה ליפול, במצב רעוע." },
  { "word": "מטאפורה", "interpretation": "השאלה, שימוש במילה בדרך ציורית." },
  { "word": "מטבוליזם", "interpretation": "חילוף החומרים בגוף." },
  { "word": "מטבל", "interpretation": "רוטב שטובלים בו ירקות וחטיפים." },
  { "word": "מטבע עובר לסוחר", "interpretation": "מטבע המקובל על כולם, שיש לו מהלכים בשוק." },
  { "word": "מטבע שחוק", "interpretation": "דבר נדוש." },
  { "word": "מטה ידו", "interpretation": "הפך לעני, ירד מנכסיו." },
  { "word": "מטה לחמו", "interpretation": "מקור פרנסתו, עיסוקו." },
  { "word": "מטול", "interpretation": "מקרן." },
  { "word": "מטורזן", "interpretation": "מגונדר, מהודר." },
  { "word": "מטותא", "interpretation": "בבקשה." },
  { "word": "מטווחי קשת", "interpretation": "מרחק קצר." },
  { "word": "מטיל", "interpretation": "גוש של מתכת." },
  { "word": "מטיל אבק בעיני הבריות", "interpretation": "מרמה." },
  { "word": "מטלורגיה", "interpretation": "חקר מתכות." },
  { "word": "מטלטלין", "interpretation": "חפצים, כבודה." },
  { "word": "מטמורה", "interpretation": "מקום מסתור, מטמון, מכמן." },
  { "word": "מטפיסי", "interpretation": "מופשט, ערטילאי, רוחני." },
  { "word": "מטרופולין", "interpretation": "עיר בירה, מגלופוליס, כרך." },
  { "word": "מטריאליזם", "interpretation": "חומרנות." },
  { "word": "מטריה", "interpretation": "1. חומר 2. אריג." },
  { "word": "מטרימוניאלי", "interpretation": "שייך לנישואים." },
  { "word": "מי אפסיים", "interpretation": "מים רדודים." },
  { "word": "מי שנכווה ברותחין נזהר בצוננין", "interpretation": "ניסיון כושל מוביל לזהירות רבה." },
  { "word": "מיאוס", "interpretation": "גועל." },
  { "word": "מיגר", "interpretation": "השמיד, הכריע." },
  { "word": "מיופה כוח", "interpretation": "מורשה, מוסמך, בעל תוקף." },
  { "word": "מיושב בדעתו", "interpretation": "רגוע, מתון, שליו." },
  { "word": "מיזם", "interpretation": "מפעל רב היקף שיזמו אותו, פרויקט." },
  { "word": "מיזנטרופ", "interpretation": "שונא אדם וחברה." },
  { "word": "מיזע", "interpretation": "סווטשרט, אפודה." },
  { "word": "מיטת סדום", "interpretation": "מצב דחוק שאין בו אפשרות תמרון, בין הפטיש ובין הסדן." },
  { "word": "מילא פיו מים", "interpretation": "לא אמר מילה, נדם." },
  { "word": "מילה", "interpretation": "כריתת עורלה לזכר." },
  { "word": "מילוא", "interpretation": "סוללת עפר, מבצר, מצודה." },
  { "word": "מיליטנטי", "interpretation": "תוקפני, לוחמני." },
  { "word": "מיליטריזם", "interpretation": "ממשל המדגיש את הצבא." },
  { "word": "מיליטריסטי", "interpretation": "צבאי." },
  { "word": "מיליציה", "interpretation": "צבא עממי." },
  { "word": "מים גנובים ימתקו", "interpretation": "הנאה מדבר אסור גדולה יותר מאשר כשהוא מותר." },
  { "word": "מים לחץ", "interpretation": "מעט מים." },
  { "word": "מימים ימימה", "interpretation": "מאז ומעולם, משכבר הימים, מקדמת דנא." },
  { "word": "מימרה", "interpretation": "פתגם, מטבע לשון, אימרה." },
  { "word": "מין", "interpretation": "כופר, אפיקורוס, אתיאיסט." },
  { "word": "מינוח", "interpretation": "קביעת מונחים, טרמינולוגיה." },
  { "word": "מינורי", "interpretation": "קטן, חלש, נוגה." },
  { "word": "מינות", "interpretation": "כפירה, התפקרות, אפיקורסיות." },
  { "word": "מיני תרגימא", "interpretation": "ממתקים." },
  { "word": "מיניאטורה", "interpretation": "דבר קטן ממדים." },
  { "word": "מיניה וביה", "interpretation": "מייד, לאלתר, בו במקום." },
  { "word": "מינימליזם", "interpretation": "הסתפקות במועט." },
  { "word": "מיסב", "interpretation": "טבעת תומכת בציר מסתובב." },
  { "word": "מיסוך", "interpretation": "התקנת מסך, הסתרה, הלטה." },
  { "word": "מיצר", "interpretation": "צרה." },
  { "word": "מיקרון", "interpretation": "אלפית המילימטר." },
  { "word": "מיראז'", "interpretation": "אשליה, פטה מורגנה." },
  { "word": "מירוק", "interpretation": "צחצוח, הברקה, ליטוש, ניקוי." },
  { "word": "מיתולוגיה", "interpretation": "אוסף אגדות ימי קדם." },
  { "word": "מיתת נשיקה", "interpretation": "מוות טבעי ללא ייסורים." },
  { "word": "מך", "interpretation": "עני, אביון, דל, חסר כל, חלכאי." },
  { "word": "מכביר", "interpretation": "להוסיף, להרבות (לרוב שלא לצורך) (ראה גם \"למכביר\")." },
  { "word": "מכבנה", "interpretation": "סיכה לשיער." },
  { "word": "מכולה", "interpretation": "תיבה גדולה להובלת מטען." },
  { "word": "מכונף", "interpretation": "שיש לו כנף או כנפיים." },
  { "word": "מכורבל", "interpretation": "עטוף, מכווץ." },
  { "word": "מכורה", "interpretation": "מולדת, צור מחצבתו." },
  { "word": "מכל מקום", "interpretation": "בכל אופן, אף על פי כן." },
  { "word": "מכמונת", "interpretation": "מלכודת, פח, אבן נגף, פוקה." },
  { "word": "מכמורת", "interpretation": "רשת דייגים." },
  { "word": "מכפתיים", "interpretation": "פלאייר, כלי עבודה המאפשר אחיזת רכיבים שונים." },
  { "word": "מכתבה", "interpretation": "שולחן כתיבה עם מגירות." },
  { "word": "מכתם", "interpretation": "שיר קצר שתוכנו סאטירי." },
  { "word": "מכתש", "interpretation": "1. כלי בו כותשים גרגרי מזון שונים (ראה גם \"עלי\") 2. עמק המוקף בהרים מכל צדדיו 3. בור הנוצר עקב התפוצצות פגז או פצצה." },
  { "word": "מלא תכונה", "interpretation": "מלא פעילות, שוקק חיים." },
  { "word": "מלאה הסאה", "interpretation": "לא ניתן לשאת עוד." },
  { "word": "מלאו ליבו", "interpretation": "העז, ההין." },
  { "word": "מלאך", "interpretation": "1. שליח, בלדר 2. אראל, שרף, כרוב." },
  { "word": "מלאכת מחשבת", "interpretation": "עבודה אמנותית הדורשת מומחיות רבה." },
  { "word": "מלבב", "interpretation": "מושך את הלב, נעים." },
  { "word": "מלגו ומלבר", "interpretation": "מבפנים ומבחוץ." },
  { "word": "מלובן", "interpretation": "מלוהט באש עד היותו לבן." },
  { "word": "מלודרמה", "interpretation": "מחזה שבו רגשנות מופרזת." },
  { "word": "מלופת", "interpretation": "מתובל." },
  { "word": "מלח הארץ", "interpretation": "מיטב הארץ." },
  { "word": "מלחה", "interpretation": "אדמה שאינה פוריה." },
  { "word": "מלחך פנכה", "interpretation": "חנפן, מתרפס." },
  { "word": "מלחמת חורמה", "interpretation": "מלחמה עזה המתנהלת בכל העוצמה." },
  { "word": "מליץ", "interpretation": "מתרגם." },
  { "word": "מליץ יושר", "interpretation": "סניגור, מלמד זכות." },
  { "word": "מליצה", "interpretation": "1. דיבור שירי 2. דיבור מנופח, דיבור פומפוזי." },
  { "word": "מלמד", "interpretation": "מקל מחודד לזירוז בהמות." },
  { "word": "מלמלה", "interpretation": "אריג, בד דק." },
  { "word": "מלנכוליה", "interpretation": "דיכאון, דכדוך, מרה שחורה." },
  { "word": "מלק", "interpretation": "ערף ראש, התיז, קיפד, קטם." },
  { "word": "מלקוח", "interpretation": "שלל, ביזה." },
  { "word": "מלקוש", "interpretation": "גשם מאוחר בסוף עונת הגשמים." },
  { "word": "מלקטת", "interpretation": "פינצטה." },
  { "word": "ממאיר", "interpretation": "1. עוקץ, צורב 2. חסר מרפא." },
  { "word": "ממבראנה", "interpretation": "קרום של עור או רקמה." },
  { "word": "ממגורה", "interpretation": "מחסן לאחסון תבואה, אסם, אמבר." },
  { "word": "ממוטט", "interpretation": "הרוס, לא יציב." },
  { "word": "ממולח", "interpretation": "אדם פיקח וחריף." },
  { "word": "ממורט", "interpretation": "1. מצוחצח, מלוטש 2. שחוק." },
  { "word": "ממורק", "interpretation": "נקי, מצוחצח, מלוטש, ממורט." },
  { "word": "ממזגה", "interpretation": "פאב, מסבאה, בית מרזח." },
  { "word": "ממיר", "interpretation": "מחליף." },
  { "word": "ממשלת צללים", "interpretation": "חברי האופוזיציה המציגים עצמם כממשלה." },
  { "word": "מן המניין", "interpretation": "בעל זכויות מלאות." },
  { "word": "מן הפח אל הפחת", "interpretation": "מצרה לצרה גדולה ממנה, מדחי אל דחי." },
  { "word": "מן השיתין", "interpretation": "מן היסוד." },
  { "word": "מן השפה ולחוץ", "interpretation": "דיבור שאינו תואם את המחשבה, אין סתרו כגילויו." },
  { "word": "מנדט", "interpretation": "תעודת ייפוי כוח, היתר." },
  { "word": "מנוי וגמור", "interpretation": "מוחלט, מוסכם." },
  { "word": "מנוס", "interpretation": "בריחה, המלטות." },
  { "word": "מנחה", "interpretation": "מתנה, שי, דורון, תשורה." },
  { "word": "מנטלי", "interpretation": "שכלי." },
  { "word": "מני אז", "interpretation": "מאותו זמן והלאה." },
  { "word": "מניה", "interpretation": "שיגעון." },
  { "word": "מנין", "interpretation": "1. כמות, מספר 2. עשרה יהודים הדרושים לתפילה." },
  { "word": "מניפולציה", "interpretation": "תחבולה, שימוש בעורמה להשגת מטרה." },
  { "word": "מניפסט", "interpretation": "מסמך גילוי דעת פוליטי, מנשר." },
  { "word": "מנעל", "interpretation": "נעל." },
  { "word": "מנקר עיניים", "interpretation": "מעורר קנאה במכוון." },
  { "word": "מנשא", "interpretation": "מתקן לנשיאת חפצים שונים." },
  { "word": "מנשר", "interpretation": "מסמך גילוי דעת פוליטי." },
  { "word": "מס שפתיים", "interpretation": "אמירה כדי לצאת ידי חובה, מן השפה ולחוץ, אין תוכו כברו." },
  { "word": "מסבאה", "interpretation": "בית מרזח, פאב, ממזגה." },
  { "word": "מסבר את האוזן", "interpretation": "דיבור פשוט להבנה." },
  { "word": "מסג", "interpretation": "תערובת מתכות, סגסוגת, נתך." },
  { "word": "מסד", "interpretation": "יסוד, בסיס, סובסטרט, תשתית." },
  { "word": "מסה", "interpretation": "1. נסיון, מבחן 2. מאמר קצר 3.כמות חומר." },
  { "word": "מסואב", "interpretation": "מלוכלך, מזוהם, מרובב, מטונף." },
  { "word": "מסובב", "interpretation": "תוצאה." },
  { "word": "מסובב בכחש", "interpretation": "מרמה, מטעה." },
  { "word": "מסובסד", "interpretation": "מקבל תמיכה כספית ממוסד ציבורי." },
  { "word": "מסווג", "interpretation": "1. ממויין 2. סודי." },
  { "word": "מסוכסך", "interpretation": "מבולבל." },
  { "word": "מסוף", "interpretation": "תחנה, בית נתיבות, טרמינל." },
  { "word": "מסוקס", "interpretation": "מחוספס." },
  { "word": "מסיבי", "interpretation": "כבד, מוצק, איתן, מגושם." },
  { "word": "מסיג גבול", "interpretation": "נכנס לתחום שאינו שלו." },
  { "word": "מסיק", "interpretation": "קטיף זיתים." },
  { "word": "מסירות נפש", "interpretation": "נאמנות עד מוות, חירוף נפש." },
  { "word": "מסית ומדיח", "interpretation": "מפתה מישהו לסטות מדרך הישר." },
  { "word": "מסך", "interpretation": "מזג, ערבב משקאות." },
  { "word": "מסכת", "interpretation": "תוכנית של קריאה, שירה ומשחק." },
  { "word": "מספוא", "interpretation": "מזון לבהמות." },
  { "word": "מעבורת", "interpretation": "1. כלי שייט לחציית נהרות 2. ספינת חלל." },
  { "word": "מעדנות", "interpretation": "בשקט, בשלווה, בניחותא." },
  { "word": "מעוגן", "interpretation": "מבוסס." },
  { "word": "מעוז", "interpretation": "1. מקלט, מחסה 2. כוח, חוזק." },
  { "word": "מעונן", "interpretation": "קוסם, מכשף, מג." },
  { "word": "מעופש", "interpretation": "רקוב, מבאיש, עבש." },
  { "word": "מעוקב", "interpretation": "בעל שלושה ממדים, בעל נפח." },
  { "word": "מעוקר", "interpretation": "מחוטא, סטרילי, מפוסטר." },
  { "word": "מעורה", "interpretation": "מחובר, מעורב, משולב." },
  { "word": "מעורטל", "interpretation": "חשוף." },
  { "word": "מעורר פלצות", "interpretation": "מזעזע." },
  { "word": "מעושה", "interpretation": "מלאכותי, שנעשה באופן מזויף." },
  { "word": "מעז יצא מתוק", "interpretation": "מן הרעה צמחה טובה." },
  { "word": "מעל", "interpretation": "בגד באמון." },
  { "word": "מענית", "interpretation": "חריץ שנוצר על ידי המחרשה, תלם." },
  { "word": "מעפל", "interpretation": "מעשה נועז." },
  { "word": "מעקש", "interpretation": "1. פיתול; 2. עניין קשה ומסובך." },
  { "word": "מערוך", "interpretation": "כלי מטבח המשמש לשיטוח הבצק (ראה גם \"רידוד\")." },
  { "word": "מערפת", "interpretation": "גיליוטינה." },
  { "word": "מעשה מרכבה", "interpretation": "דבר מסובך ומורכב." },
  { "word": "מעשי אבות סימן לבנים", "interpretation": "הבנים ממשיכים את מסורת הוריהם." },
  { "word": "מעשנה", "interpretation": "ארובה." },
  { "word": "מעשר", "interpretation": "עשירית." },
  { "word": "מפאת", "interpretation": "מפני, משום, בגלל." },
  { "word": "מפה לאוזן", "interpretation": "שמועה המועברת באופן חשאי." },
  { "word": "מפוברק", "interpretation": "עשוי באופן מלאכותי, מזויף." },
  { "word": "מפולפל", "interpretation": "חריף שכל, שנון." },
  { "word": "מפולש", "interpretation": "פתוח משני צדדיו." },
  { "word": "מפוסטר", "interpretation": "מחוטא, מעוקר, סטרילי." },
  { "word": "מפורז", "interpretation": "שטח שאינו בשליטת שני הצדדים הלוחמים בו אין כלי נשק." },
  { "word": "מפורכס", "interpretation": "מאופר." },
  { "word": "מפח נפש", "interpretation": "אכזבה, ייאוש, פחי נפש." },
  { "word": "מפסלת", "interpretation": "כלי עבודה המשמש לפיסול." },
  { "word": "מפעפע", "interpretation": "1. רותח ומבעבע; 2. מחלחל." },
  { "word": "מפקידה לפקידה", "interpretation": "מדי פעם, מזמן לזמן." },
  { "word": "מפריח יונים", "interpretation": "ממציא דברים." },
  { "word": "מפתן", "interpretation": "פתח הבית, סף, אסקופה." },
  { "word": "מץ", "interpretation": "לוחץ." },
  { "word": "מצא את מחייתו", "interpretation": "מצא מקור פרנסה." },
  { "word": "מצא לו מהלכים", "interpretation": "נעשה רווח ומצוי." },
  { "word": "מצא מסילות בליבו", "interpretation": "עניין אותו." },
  { "word": "מצאה ידו", "interpretation": "היה ביכולתו." },
  { "word": "מצביא", "interpretation": "מפקד, אסטרטג, שר צבא." },
  { "word": "מצד", "interpretation": "מבצר, ביצרון, מצודה, מילוא." },
  { "word": "מצדד", "interpretation": "תומך." },
  { "word": "מצודד", "interpretation": "מושך, שובה את הלב." },
  { "word": "מצולה", "interpretation": "מים עמוקים, מי תהום." },
  { "word": "מצונף", "interpretation": "מכורבל." },
  { "word": "מצועף", "interpretation": "מכוסה, עטוף, לוט." },
  { "word": "מצח נחושה", "interpretation": "עקשן, חצוף, עז מצח." },
  { "word": "מצחין", "interpretation": "מסריח, מבאיש, מעופש." },
  { "word": "מצילה", "interpretation": "פעמון קטן." },
  { "word": "מצנם", "interpretation": "טוסטר." },
  { "word": "מצערת", "interpretation": "אמצעי ויסות המהירות במטוסים וכלי רכב." },
  { "word": "מצקצק", "interpretation": "משמיע קול." },
  { "word": "מצר", "interpretation": "נתון בצרה, סובל." },
  { "word": "מצר", "interpretation": "גבול, סייג, חציצה." },
  { "word": "מק", "interpretation": "רקב, ריקבון." },
  { "word": "מקאמה", "interpretation": "סיפור שנון הכתוב בחרוזים." },
  { "word": "מקברי", "interpretation": "מפחיד, מבעית." },
  { "word": "מקבת", "interpretation": "פטיש, קורנס, מקוב." },
  { "word": "מקדמת דנא", "interpretation": "מאז ומעולם, משכבר הימים." },
  { "word": "מקוב", "interpretation": "פטיש, קורנס, מקבת." },
  { "word": "מקווה", "interpretation": "מאגר מים המשמש להיטהרות." },
  { "word": "מקוף", "interpretation": "אזור בפיקוח אדם המקיפו מדי פעם." },
  { "word": "מקורה", "interpretation": "מכוסה בתקרה, מחופה." },
  { "word": "מקורזל", "interpretation": "מתולתל, מסולסל." },
  { "word": "מקח", "interpretation": "1. סחורה, מרכולת; 2. קנייה." },
  { "word": "מקח וממכר", "interpretation": "קנייה ומכירה." },
  { "word": "מקטורן", "interpretation": "מעיל." },
  { "word": "מקטרג", "interpretation": "תובע, מאשים, קטיגור." },
  { "word": "מקל נועם", "interpretation": "נוהג ביד רכה." },
  { "word": "מקלעת", "interpretation": "צמה." },
  { "word": "מקנה", "interpretation": "שם כולל לצאן ולבקר." },
  { "word": "מקסם שווא", "interpretation": "מעשה כשפים, אשליה." },
  { "word": "מקפא", "interpretation": "ג'לי." },
  { "word": "מקצוע", "interpretation": "צלע של גוף תלת מימדי." },
  { "word": "מקצועה", "interpretation": "כלי נגרים המשמש להחלקת עצים." },
  { "word": "מקצצת בנטיעות", "interpretation": "כופרת." },
  { "word": "מקשה", "interpretation": "שדה קישואים או אבטיחים." },
  { "word": "מקשה", "interpretation": "גוש." },
  { "word": "מר נפש", "interpretation": "מתוסכל, ממורמר, מדוכדך." },
  { "word": "מראית עין", "interpretation": "לכאורה, במבט שטחי." },
  { "word": "מרבד", "interpretation": "שטיח, מחצלת." },
  { "word": "מרבץ", "interpretation": "שכבת קרקע, רובד." },
  { "word": "מרה שחורה", "interpretation": "דיכאון, פסימיות." },
  { "word": "מרובב", "interpretation": "מלוכלך, מוכתם, מטונף." },
  { "word": "מרוב עצים לא רואים את היער", "interpretation": "ריבוי פרטים נקודתיים מקשה על ראיית התמונה הכוללת." },
  { "word": "מרופט", "interpretation": "בלוי, קרוע, שחוק." },
  { "word": "מרופש", "interpretation": "מלוכלך, מלא רפש ובוץ." },
  { "word": "מרושש", "interpretation": "אדם שירד מנכסיו." },
  { "word": "מרות", "interpretation": "שליטה, משמעת, אדנות, שררה." },
  { "word": "מרחשת", "interpretation": "מחבת, אלפס, קלחת." },
  { "word": "מרי", "interpretation": "התנגדות, מרד." },
  { "word": "מרית", "interpretation": "שפכטל, כף שטוחה המשמשת נגרים וצבעים." },
  { "word": "מריונטה", "interpretation": "כינוי למי שמופעל על ידי אחרים." },
  { "word": "מריטה", "interpretation": "תלישה ועקירה." },
  { "word": "מרכולת", "interpretation": "סחורה, מקח, טובין." },
  { "word": "מרנין", "interpretation": "משמח." },
  { "word": "מרעין ובישין", "interpretation": "צרות צרורות." },
  { "word": "מרצע", "interpretation": "מכשיר חד המשמש לניקוב חורים." },
  { "word": "מרקחת", "interpretation": "1. תערובת, מרקחה; 2. ריבה." },
  { "word": "מרקיז", "interpretation": "אציל, נכבד, שוע." },
  { "word": "מרקם", "interpretation": "מבנה החלקים בחומר מורכב, טקסטורה." },
  { "word": "מרקקה", "interpretation": "כלי שנועד לירוק לתוכו." },
  { "word": "מש", "interpretation": "זז, נע, זע, נד, זח, סר." },
  { "word": "משאת נפש", "interpretation": "שאיפה עזה, אידיאל." },
  { "word": "משבר", "interpretation": "גל גדול, נחשול." },
  { "word": "משגב", "interpretation": "1. מבצר, מעוז; 2. מחסה, מגן." },
  { "word": "משדדה", "interpretation": "מכשיר חקלאי לפירור ויישור האדמה." },
  { "word": "משה", "interpretation": "הוציא מהמים." },
  { "word": "משואה", "interpretation": "מדורת אש, לפיד, אבוקה." },
  { "word": "משוא פנים", "interpretation": "אפליה, איפה ואיפה." },
  { "word": "משוב", "interpretation": "פידבק." },
  { "word": "משובב", "interpretation": "משעשע." },
  { "word": "משובה", "interpretation": "שובבות, מעשה קונדס." },
  { "word": "משוגה", "interpretation": "טעות, שגגה, שגיאה." },
  { "word": "משוורת", "interpretation": "ארכוף, טבעת לרגל בצד האוכף." },
  { "word": "משוכה", "interpretation": "1. גדר; 2. מכשול במסלול ריצה." },
  { "word": "משולל", "interpretation": "נטול." },
  { "word": "משומד", "interpretation": "יהודי שהמיר דתו, מומר." },
  { "word": "משונן", "interpretation": "1. מחודד, מלוטש; 2. בעל בליטות." },
  { "word": "משועבד", "interpretation": "נכנע, עבד." },
  { "word": "משופה", "interpretation": "מלוטש." },
  { "word": "משוקץ", "interpretation": "נתעב." },
  { "word": "משורבב", "interpretation": "מושט, שלוח קדימה, שמוכנס שלא במקומו." },
  { "word": "משורה", "interpretation": "כלי למדידת כמויות של נוזלים." },
  { "word": "משורת", "interpretation": "טבעת באוכף לשים את הרגל, ארכוף." },
  { "word": "משוש", "interpretation": "שמחה, ששון, עליצות." },
  { "word": "משחזת", "interpretation": "מכשיר לליטוש והשחזה." },
  { "word": "משטין", "interpretation": "שונא, מקטרג, תובע." },
  { "word": "משטמה", "interpretation": "שנאה, איבה." },
  { "word": "משיב נפש", "interpretation": "מרענן." },
  { "word": "משיחה", "interpretation": "1. מריחה בחומר; 2. מינוי למשרה חשובה." },
  { "word": "משים פעמיו", "interpretation": "יוצא לדרך." },
  { "word": "משך את ידו מן", "interpretation": "הסתלק, ויתר." },
  { "word": "משכוכי", "interpretation": "מוביל אחריו." },
  { "word": "משכון", "interpretation": "עבוט, ערבון." },
  { "word": "משכית", "interpretation": "1. ציור; 2. תכשיט, עדי." },
  { "word": "משכן", "interpretation": "בית מגורים, מעון." },
  { "word": "משל ברוחו", "interpretation": "התאפק, לא התפרץ." },
  { "word": "משל ושנינה", "interpretation": "לעג וקלס." },
  { "word": "משמים", "interpretation": "משועמם, שותק, דומם." },
  { "word": "משנה", "interpretation": "1. כפול ומכופל; 2. סגן." },
  { "word": "משעול", "interpretation": "שביל, דרך צרה למעבר." },
  { "word": "משענת קנה רצוץ", "interpretation": "דבר או אדם שכושלים בשעת מבחן." },
  { "word": "משק", "interpretation": "שקשוק, רעש." },
  { "word": "משרך דרכו", "interpretation": "הולך לאיטו, מתנהל בכבדות." },
  { "word": "מתאבנים", "interpretation": "מעוררי תיאבון." },
  { "word": "מתבדר", "interpretation": "מתפזר." },
  { "word": "מתבל", "interpretation": "רוטב לתיבול." },
  { "word": "מתבן", "interpretation": "מחסן לתבן." },
  { "word": "מתווה", "interpretation": "קווים כללים של תוכנית, סקיצה." },
  { "word": "מתוך שלא לשמה בא לשמה", "interpretation": "עסק בדבר לא מאהבה והגיע לאהבו." },
  { "word": "מתום", "interpretation": "מקום שלם בגוף, מקום ללא פצע." },
  { "word": "מתי מספר", "interpretation": "מעט אנשים, קומץ." },
  { "word": "מתנשא", "interpretation": "מתפאר, מתגאה, זחוח, נישא כלפי מעלה." },
  { "word": "מתרס", "interpretation": "מחסום רחוב מאולתר, בריקדה." }
]
