window.nun = [
  { "word": "נא", "interpretation": "מבושל למחצה." },
  { "word": "נאד", "interpretation": "שק עור לנוזלים." },
  { "word": "נאדר", "interpretation": "נהדר, נשגב, נעלה, גרנדיוזי." },
  { "word": "נאה דורש ונאה מקיים", "interpretation": "לא רק נותן הוראות אלא גם מבצע אותן." },
  { "word": "נאור", "interpretation": "משכיל, בן תרבות." },
  { "word": "נאחז בקש", "interpretation": "נעזר בדבר שאין בו ממש." },
  { "word": "נאלח", "interpretation": "מלוכלך, מזוהם, מסואב." },
  { "word": "נאלם דום", "interpretation": "השתתק, נדם." },
  { "word": "נאסף אל עמיו", "interpretation": "מת, נפטר, עלה השמימה." },
  { "word": "נאצה", "interpretation": "קללה, גידוף, חירוף." },
  { "word": "נאקה", "interpretation": "נקבת הגמל." },
  { "word": "נבדל", "interpretation": "שונה מהשאר, נפרד." },
  { "word": "נבוב", "interpretation": "חלול, ריק מתוכן, שדוף." },
  { "word": "נבוט", "interpretation": "מקל, אלה." },
  { "word": "נבכי נפשו", "interpretation": "מעמקי נפשו." },
  { "word": "נבער", "interpretation": "חסר השכלה, בור, בער." },
  { "word": "נבעת", "interpretation": "נבהל, ירא, נחרד." },
  { "word": "נבצר ממנו", "interpretation": "נמנע ממנו." },
  { "word": "נבר", "interpretation": "חפר, חיטט." },
  { "word": "נברשת", "interpretation": "מנורה גדולה הנתלית בתקרה." },
  { "word": "נגה", "interpretation": "זרח, הפיץ אור." },
  { "word": "נגוהה", "interpretation": "אור, זיו, זוהר, נוגה, הילה." },
  { "word": "נגטיבי", "interpretation": "שלילי." },
  { "word": "נגיד", "interpretation": "מושל, שליט, פרנס." },
  { "word": "נגיף", "interpretation": "וירוס." },
  { "word": "נגע", "interpretation": "מחלה, מכה, חבלה, חבורה." },
  { "word": "נגש", "interpretation": "דחק, זירז בכוח, התאנה." },
  { "word": "נד", "interpretation": "זז, נע, זע, מש, סר." },
  { "word": "נד", "interpretation": "קיר, תל." },
  { "word": "נדבך", "interpretation": "שורת לבנים בבניין, שכבה, רובד, סובסטרט." },
  { "word": "נדכא", "interpretation": "עני, חסר כל, דל, מך." },
  { "word": "נדם", "interpretation": "השתתק, נאלם דום." },
  { "word": "נדן", "interpretation": "נרתיק החרב." },
  { "word": "נדף", "interpretation": "הפיץ, התפשט, דחף, הדף." },
  { "word": "נהור", "interpretation": "אור." },
  { "word": "נהי", "interpretation": "קינה, מספד, בכי, הי." },
  { "word": "נהיה", "interpretation": "רצון עז, השתוקקות, כיסופים." },
  { "word": "נהיר", "interpretation": "ברור, בהיר, מחוור." },
  { "word": "נהירה", "interpretation": "זרימה בצורה מסיבית לאירוע." },
  { "word": "נהמה", "interpretation": "קול עמום וחזק." },
  { "word": "נהנתנות", "interpretation": "רדיפת תענוגות, הדוניזם." },
  { "word": "נהפוך הוא", "interpretation": "אדרבא, ההיפך." },
  { "word": "נהרה", "interpretation": "אור, זוהר, זיו, נוגה." },
  { "word": "נוגה", "interpretation": "אור, זיו, זוהר, נהרה." },
  { "word": "נוגה", "interpretation": "עצוב, עגום, טרגי, סכוף." },
  { "word": "נוה", "interpretation": "1. מקום מרעה במדבר 2. מקום מגורים, מעון 3. יפה, נאה." },
  { "word": "נוח לבריות", "interpretation": "מי שקל להסתדר איתו." },
  { "word": "נוח לכעוס", "interpretation": "עצבני, מהיר חימה." },
  { "word": "נוח לרצות", "interpretation": "סולח מהר, קל לרצותו." },
  { "word": "נוטר", "interpretation": "1. שומר, גפיר, שוטר  2. שומר כעס על מישהו במשך זמן רב." },
  { "word": "נוטריון", "interpretation": "מי שמוסמך לאשר העתקים של תעודות רשמיות." },
  { "word": "נוטריקון", "interpretation": "כתיבה בראשי תיבות." },
  { "word": "נוירוטי", "interpretation": "בעל הפרעה נפשית קלה." },
  { "word": "נול", "interpretation": "מכונת אריגה." },
  { "word": "נומרוס קלאוזוס", "interpretation": "מספר מוגבל." },
  { "word": "נונשלנטי", "interpretation": "חסר אכפתיות." },
  { "word": "נוסטלגיה", "interpretation": "התרפקות על זכר הימים שעברו." },
  { "word": "נוף", "interpretation": "צמרת העץ, אמיר." },
  { "word": "נופך", "interpretation": "אחת מאבני החושן." },
  { "word": "נופת", "interpretation": "דבש." },
  { "word": "נוקב", "interpretation": "יסודי, חודר, מעמיק, חריף." },
  { "word": "נוקד", "interpretation": "מגדל צאן." },
  { "word": "נוקדן", "interpretation": "קפדן, פדנט, דקדקן." },
  { "word": "נוקש", "interpretation": "נכשל." },
  { "word": "נורמליזציה", "interpretation": "הבאה לידי מצב תקין." },
  { "word": "נור", "interpretation": "אש, אור." },
  { "word": "נושב", "interpretation": "מאוכלס, מיושב." },
  { "word": "נושה", "interpretation": "מלווה הדורש מן הלווה לפרוע את חובו." },
  { "word": "נותר וחצי תאוותו בידו", "interpretation": "לא בא על סיפוקו." },
  { "word": "נזיד", "interpretation": "תבשיל ירקות." },
  { "word": "נזר", "interpretation": "כתר, עטרה." },
  { "word": "נח על זרי הדפנה", "interpretation": "מי שמתענג על הישגי העבר ולא ממשיך להתאמץ." },
  { "word": "נחבא אל הכלים", "interpretation": "צנוע, ביישן, עניו." },
  { "word": "נחה דעתו", "interpretation": "נרגע." },
  { "word": "נחוש בדעתו", "interpretation": "שדעתו נחרצת." },
  { "word": "נחושתיים", "interpretation": "כבלי מתכת, אזיקים." },
  { "word": "נחיל", "interpretation": "1. קבוצת דבורים 2. קבוצת בעלי חיים." },
  { "word": "נחירה", "interpretation": "המתת בעל חיים על ידי דקירה." },
  { "word": "נחל", "interpretation": "ירש, זכה, נפל בחלקו." },
  { "word": "נחל איתן", "interpretation": "נחל שזורם כל השנה." },
  { "word": "נחל אכזב", "interpretation": "נחל שזורם רק בחורף, ממי הגשמים." },
  { "word": "נחלה", "interpretation": "אחוזה, קניין, ירושה." },
  { "word": "נחמה פורתא", "interpretation": "נחמה כלשהי, חצי נחמה." },
  { "word": "נחרץ", "interpretation": "מוחלט, סופי, גמור." },
  { "word": "נחש", "interpretation": "קסם, לחש, השבעה, להט, מגיה." },
  { "word": "נחשול", "interpretation": "גל גדול, משבר." },
  { "word": "נחשוני", "interpretation": "ראשוני, חלוצי, נועז." },
  { "word": "נחשל", "interpretation": "מפגר, שאינו מתקדם כמו השאר." },
  { "word": "נחת רוח", "interpretation": "עונג רב, שביעות רצון." },
  { "word": "נחתום", "interpretation": "אופה." },
  { "word": "נטה היום", "interpretation": "ירד היום והתקרב הערב." },
  { "word": "נטה חסד", "interpretation": "נהג כלפי מישהו ברחמים." },
  { "word": "נטף", "interpretation": "טיפה, אגל, רסיס, נתז." },
  { "word": "ניאוף", "interpretation": "בגידה, קיום יחסי מין שלא עם בן הזוג." },
  { "word": "ניב", "interpretation": "ביטוי שגור, אימרה, דיאלקט." },
  { "word": "ניגח", "interpretation": "פגע, היכה, תקף." },
  { "word": "ניגף", "interpretation": "הוכה, נחל תבוסה." },
  { "word": "ניגר", "interpretation": "נשפך, נזל, זרם." },
  { "word": "נידה", "interpretation": "הרחיק, סילק, דחה, החרים." },
  { "word": "נידה", "interpretation": "כינוי לאישה בזמן הווסת." },
  { "word": "נידח", "interpretation": "1. מגורש, מוגלה 2. מרוחק, מבודד." },
  { "word": "נידף", "interpretation": "נדחף, פוזר, נזרה." },
  { "word": "ניהיליזם", "interpretation": "שלילת הסדר החברתי הקיים." },
  { "word": "ניואנס", "interpretation": "גוון, הבדל דק." },
  { "word": "ניחא", "interpretation": "טוב, נוח, שפיר" },
  { "word": "ניחוח", "interpretation": "ריח נעים וטוב." },
  { "word": "ניחם", "interpretation": "התחרט, חזר בו, היכה על חטא." },
  { "word": "ניחר", "interpretation": "נשרף, התייבש מחום, צרוב." },
  { "word": "ניחר גרונו", "interpretation": "גרונו יבש מאוד." },
  { "word": "ניטור", "interpretation": "מעקב אחר תנאים או תהליכים." },
  { "word": "ניטל עוקצו", "interpretation": "פגה חריפותו." },
  { "word": "נייח", "interpretation": "יציב, שאינו זז." },
  { "word": "ניכור", "interpretation": "הרגשת זרות, התרחקות." },
  { "word": "ניכוש", "interpretation": "עקירת עשבים שוטים." },
  { "word": "נים ולא נים", "interpretation": "מצב שבין שינה לעירות, נמנום." },
  { "word": "נימה", "interpretation": "1. חוט, שערה 2. צליל, הד." },
  { "word": "נימוח", "interpretation": "מתמוסס, נעשה רך מאוד." },
  { "word": "נימפה", "interpretation": "אלה, כלה, יפהפייה." },
  { "word": "ניע", "interpretation": "תנועה, זיע." },
  { "word": "ניער חוצנו", "interpretation": "סירב לקבל אחריות." },
  { "word": "ניער כפיו", "interpretation": "לא השתתף." },
  { "word": "ניפוי", "interpretation": "ברירה, מיון, ניקוי." },
  { "word": "ניצב", "interpretation": "ידית הסכין, קת." },
  { "word": "ניצה", "interpretation": "ניצן הפרח." },
  { "word": "ניצח", "interpretation": "ניהל, פיקד, פיקח." },
  { "word": "ניצחון פירוס", "interpretation": "ניצחון בעל תופעות לוואי שליליות." },
  { "word": "ניצים", "interpretation": "שונאים." },
  { "word": "ניצל בעור שיניו", "interpretation": "הציל עצמו בקושי רב." },
  { "word": "ניקוז", "interpretation": "העברת עודפי מים בתעלות." },
  { "word": "ניקרה", "interpretation": "שקע, נקיק בסלע או בהר." },
  { "word": "ניר", "interpretation": "שדה חרוש." },
  { "word": "נירוונה", "interpretation": "מצב של שלווה מוחלטת." },
  { "word": "נישא", "interpretation": "רם, גבוה, נכבד, נעלה." },
  { "word": "נישול", "interpretation": "גירוש, עקירה." },
  { "word": "נישום", "interpretation": "מי שאומדים את הכנסתו לצורך מס." },
  { "word": "נכא", "interpretation": "מדוכא, מדוכדך, דווי, דואב, עגום." },
  { "word": "נכאים", "interpretation": "עצבות, דיכדוך, יגון, דאבה." },
  { "word": "נכזבה תוחלתו", "interpretation": "תקוותיו היו לשווא." },
  { "word": "נכלולי", "interpretation": "רמאי, נוכל, בדאי, שרלטן." },
  { "word": "נכלם", "interpretation": "מבויש, נבוך, כבש פניו בקרקע." },
  { "word": "נכמרו רחמיו", "interpretation": "ריחם." },
  { "word": "נכנס בעובי הקורה", "interpretation": "נכנס לעומקו של העניין, אחז את השור בקרניו." },
  { "word": "נכסי דלא ניידי", "interpretation": "נכסים נייחים, כמו קרקעות, בניינים ומגרשים." },
  { "word": "נכסי צאן ברזל", "interpretation": "דברים שחשיבותם נצחית." },
  { "word": "נכסף", "interpretation": "רוצה, משתוקק, מתאווה, עורג." },
  { "word": "נכר", "interpretation": "מקום זר." },
  { "word": "נלוז", "interpretation": "עקום, סוטה מדרך הישר." },
  { "word": "נלכד בכף", "interpretation": "נפל בפח." },
  { "word": "נמהר", "interpretation": "פזיז, נחפז." },
  { "word": "נמוג", "interpretation": "נעלם, התנדף, פג, התפוגג, נגוז." },
  { "word": "נמוך רוח", "interpretation": "צנוע, עניו, שפל רוח." },
  { "word": "נמלט בעור שיניו", "interpretation": "הציל את עצמו בקושי רב." },
  { "word": "נמלך", "interpretation": "התייעץ, התעשת." },
  { "word": "נמלץ", "interpretation": "דיבור נפוח, גדוש מליצות." },
  { "word": "נמק", "interpretation": "מוות של חלק חי." },
  { "word": "נמר של נייר", "interpretation": "איום לא ממשי." },
  { "word": "נס", "interpretation": "1. דגל 2. פלא." },
  { "word": "נס", "interpretation": "ברח." },
  { "word": "נסח", "interpretation": "עקר, תלש." },
  { "word": "נסיוב", "interpretation": "נוזל חיסוני." },
  { "word": "נסך", "interpretation": "1. יציקת נוזלים 2. מסכה, תבנית יצוקה." },
  { "word": "נסק", "interpretation": "המריא, הרקיע." },
  { "word": "נעו אמות הספים", "interpretation": "נוצרה מהומה רבה." },
  { "word": "נעימה", "interpretation": "ניגון, נימה, צליל, טון." },
  { "word": "נעים הליכות", "interpretation": "מנומס (ראה גם \"הליכות\")." },
  { "word": "נעלס", "interpretation": "מאושר." },
  { "word": "נעתקו המילים מפיו", "interpretation": "השתתק, נדם." },
  { "word": "נפה", "interpretation": "1. מסננת, כברה 2. אזור, חבל." },
  { "word": "נפוטיזם", "interpretation": "פרוטקציה, משוא פנים." },
  { "word": "נפח רוחו", "interpretation": "מת, נפח נשמתו." },
  { "word": "נפיל", "interpretation": "ענק, טיטן." },
  { "word": "נפל", "interpretation": "דבר שנכשל בראשיתו." },
  { "word": "נפל למשכב", "interpretation": "חלה." },
  { "word": "נפלה עטרת ראשנו", "interpretation": "קריאה נרגשת על מות אדם יקר." },
  { "word": "נפלה רוחו", "interpretation": "התייאש." },
  { "word": "נפסד", "interpretation": "פגום, פסול, מושחת." },
  { "word": "נפעם", "interpretation": "נרגש." },
  { "word": "נפקנית", "interpretation": "זונה." },
  { "word": "נצור", "interpretation": "שמור, נעול, נסתר, עלום, צפון." },
  { "word": "נציב", "interpretation": "1. עמוד 2. מושל, ממונה." },
  { "word": "נצר", "interpretation": "ענף רך, זרד, שריג, זלזל." },
  { "word": "נקב", "interpretation": "קבע, ציין, הודיע במפורש." },
  { "word": "נקבה", "interpretation": "מנהרה, מחילה." },
  { "word": "נקוד", "interpretation": "מכוסה נקודות, חברבר, ברוד." },
  { "word": "נקודת תורפה", "interpretation": "נקודה חלשה, בטן רכה." },
  { "word": "נקטר", "interpretation": "יין משובח, תירוש, עסיס." },
  { "word": "נקי כפיים", "interpretation": "ישר, שאינו לוקח שוחד." },
  { "word": "נקיפה", "interpretation": "1. דפיקה, נקישה 2. חלוף הזמן." },
  { "word": "נקיק", "interpretation": "סדק בסלע, בקיע, ניקרה, חגו." },
  { "word": "נקלה", "interpretation": "נתעב, בזוי, נחות, פחות ערך." },
  { "word": "נקעה נפשו", "interpretation": "נמאס עליו, קצה נפשו." },
  { "word": "נקף", "interpretation": "עבר ושב." },
  { "word": "נקפו ליבו", "interpretation": "התחרט, חש ייסורי מצפון." },
  { "word": "נקר", "interpretation": "קרע בצמיג, נקב, פנצ'ר." },
  { "word": "נקרה", "interpretation": "שקע, נקיק , חגו, בקיע." },
  { "word": "נקרן", "interpretation": "חטטן." },
  { "word": "נקרתה", "interpretation": "הזדמנה." },
  { "word": "נר לרגליו", "interpretation": "עיקרון שלפיו האדם נוהג, מוטו." },
  { "word": "נרגן", "interpretation": "מתלונן, רוטן, מחרחר ריב." },
  { "word": "נרעש", "interpretation": "נרגש." },
  { "word": "נרפה", "interpretation": "עצל, בטלן, פוחז, ריקא, יחפן." },
  { "word": "נרקוטי", "interpretation": "מרדים." },
  { "word": "נרקסיזם", "interpretation": "התאהבות האדם בעצמו." },
  { "word": "נשא", "interpretation": "אדם שנושא בגופו חיידק או נגיף." },
  { "word": "נשא בשרו בשיניו", "interpretation": "לא הגיב." },
  { "word": "נשא עיניו", "interpretation": "1. הסתכל למרחוק 2. קיווה, ייחל." },
  { "word": "נשא קינה", "interpretation": "השמיע דבר הספד, תינה." },
  { "word": "נשא רגליו", "interpretation": "קם ללכת, עקר רגליו." },
  { "word": "נשגב", "interpretation": "1. נעלה, מרומם 2. חזק, איתן." },
  { "word": "נשוא פנים", "interpretation": "נכבד, חשוב, שוע." },
  { "word": "נשיא", "interpretation": "ענן גשם, עב." },
  { "word": "נשיה", "interpretation": "שכחה." },
  { "word": "נשך", "interpretation": "ריבית על הלוואה." },
  { "word": "נשפה", "interpretation": "חלק, תלול." },
  { "word": "נשרך", "interpretation": "נגרר, נסחב." },
  { "word": "נתון בכף הקלע", "interpretation": "מתלבט." },
  { "word": "נתז", "interpretation": "רסיס, טיפה, אגל, נטף." },
  { "word": "נתח", "interpretation": "חתיכה, חריץ, פרוסה." },
  { "word": "נתיב", "interpretation": "שביל, דרך, מנהג." },
  { "word": "נתיך", "interpretation": "פיוז." },
  { "word": "נתין", "interpretation": "אזרח." },
  { "word": "נתיצה", "interpretation": "הריסה." },
  { "word": "נתך", "interpretation": "תערובת מתכות, מסג, סגסוגת." },
  { "word": "נתכרכמו פניו", "interpretation": "פניו האדימו מבושה או מצער, נבוך ונכלם." },
  { "word": "נתלה באילנות גבוהים", "interpretation": "הסתמך על גדולים ממנו." },
  { "word": "נתן בו אותותיו", "interpretation": "השפיע עליו." },
  { "word": "נתן דעתו", "interpretation": "שם לב, שת ליבו, שעה." },
  { "word": "נתן עיניו בו", "interpretation": "חמד, חשק, התאווה." },
  { "word": "נתן עינו בכוס", "interpretation": "החל להשתכר." },
  { "word": "נתן פומבי", "interpretation": "פרסם ברבים." },
  { "word": "נתעב", "interpretation": "מאוס, בזוי." },
  { "word": "נתפס בקלקלתו", "interpretation": "נתפס בהתנהגותו הרעה." }
]
