window.pay = [
  { "word": "פאה", "interpretation": "1. קצה, פינה 2. דופן של גוף תלת-מימדי." },
  { "word": "פארה", "interpretation": "ענף, בד, זרד, זלזל, נצר." },
  { "word": "פאשיזם", "interpretation": "משטר דיקטטורי לאומני." },
  { "word": "פאתוס", "interpretation": "התפעלות והתרגשות מופרזות." },
  { "word": "פג", "interpretation": "לא בשל, בוסר." },
  { "word": "פג", "interpretation": "נעלם, התאדה, התפוגג, נמוג, נגוז." },
  { "word": "פגניות", "interpretation": "עבודת אלילים, פוליתיאיזם." },
  { "word": "פגע", "interpretation": "פגש." },
  { "word": "פגע", "interpretation": "מקרה רע, תאונה." },
  { "word": "פגרה", "interpretation": "חופשה." },
  { "word": "פדגוג", "interpretation": "מחנך." },
  { "word": "פדות", "interpretation": "גאולה, הצלה, שחרור." },
  { "word": "פדיון", "interpretation": "גאולה בכסף, הצלה." },
  { "word": "פדנט", "interpretation": "דייקן, דקדקן, קפדן, נוקדן." },
  { "word": "פדרציה", "interpretation": "התאחדות, אגודה." },
  { "word": "פוביה", "interpretation": "פחד, בעתה, יראה, אימה." },
  { "word": "פובליציסטי", "interpretation": "עיתונאי." },
  { "word": "פוגרום", "interpretation": "פרעות, מעשי רצח נגד קבוצה." },
  { "word": "פוזיציה", "interpretation": "עמדה." },
  { "word": "פוזמק", "interpretation": "גרב." },
  { "word": "פוחז", "interpretation": "פזיז, נמהר, שובב." },
  { "word": "פוחח", "interpretation": "שובב." },
  { "word": "פוחלץ", "interpretation": "עור של בעל חיים ממולא בחומר." },
  { "word": "פוטנציה", "interpretation": "יכולת." },
  { "word": "פוטש", "interpretation": "נסיון הפיכה כושל." },
  { "word": "פוך", "interpretation": "1. איפור קדום לעיניים 2. חומר ריפוד." },
  { "word": "פולארי", "interpretation": "קוטבי, מנוגד." },
  { "word": "פולה", "interpretation": "מוציא כינים." },
  { "word": "פוליגמיה", "interpretation": "מצב שבו גבר נשוי לנשים רבות." },
  { "word": "פוליסה", "interpretation": "תעודת ביטוח." },
  { "word": "פוליפוני", "interpretation": "רב קולי." },
  { "word": "פוליתיאיזם", "interpretation": "אמונה באלים רבים." },
  { "word": "פולמוס", "interpretation": "ויכוח, ריב, מחלוקת." },
  { "word": "פולקלור", "interpretation": "יצירות עממיות כגון אגדות." },
  { "word": "פומבי", "interpretation": "גלוי, מפורסם, פרהסיה." },
  { "word": "פומית", "interpretation": "פיה, קצה של כלי שנועד להחזיקו בפה." },
  { "word": "פונטיקה", "interpretation": "חקר ההגייה." },
  { "word": "פונקציה", "interpretation": "תפקיד, משימה." },
  { "word": "פוסט מורטם", "interpretation": "לאחר המוות." },
  { "word": "פוסט פקטום", "interpretation": "בדיעבד." },
  { "word": "פועה", "interpretation": "מייבב." },
  { "word": "פוקה", "interpretation": "תקלה, מכשול, אבן נגף, דחי." },
  { "word": "פור", "interpretation": "גורל, מזל, פיס, גד." },
  { "word": "פורח באוויר", "interpretation": "חסר שחר." },
  { "word": "פוריטניות", "interpretation": "פשטות וצניעות, שמרנות." },
  { "word": "פורץ גדר", "interpretation": "פושע." },
  { "word": "פורק עול", "interpretation": "נוהג בהפקרות." },
  { "word": "פורתא", "interpretation": "מעט, קצת, קורט." },
  { "word": "פושט", "interpretation": "פותח, פורש." },
  { "word": "פושט יד", "interpretation": "קבצן." },
  { "word": "פושק שפתיים", "interpretation": "פטפטן." },
  { "word": "פז", "interpretation": "זהב מובחר." },
  { "word": "פזורה", "interpretation": "גלות, מקומות שונים בהם מפוזרים יהודים." },
  { "word": "פזרן", "interpretation": "נדיב, ובמובן שלילי: בזבזן." },
  { "word": "פח", "interpretation": "מלכודת, מכשול." },
  { "word": "פח יקוש", "interpretation": "מלכודת." },
  { "word": "פחוס", "interpretation": "שטוח." },
  { "word": "פחז כמים", "interpretation": "חסר סבלנות." },
  { "word": "פחי נפש", "interpretation": "אכזבה, מפח נפש." },
  { "word": "פחת", "interpretation": "גירעון, חסך, חיסרון." },
  { "word": "פטוטרת", "interpretation": "החלק הצר של העלה." },
  { "word": "פטיציה", "interpretation": "עצומה." },
  { "word": "פטלי", "interpretation": "גורלי, בלתי נמנע." },
  { "word": "פטר", "interpretation": "בכור, הוולד הראשון." },
  { "word": "פטר אותו בלא כלום", "interpretation": "לא נתן לו את מבוקשו." },
  { "word": "פטרון", "interpretation": "נותן חסות, אפוטרופוס." },
  { "word": "פטריארכלי", "interpretation": "של שלטון אבות המשפחה." },
  { "word": "פיאודל", "interpretation": "בעל אחוזה עם אריסים." },
  { "word": "פיאסקו", "interpretation": "כשלון." },
  { "word": "פיגול", "interpretation": "דבר מתועב, שיקוץ, ניוול." },
  { "word": "פיד", "interpretation": "אסון, צרה, איד, שבר, הוה." },
  { "word": "פיו וליבו שווים", "interpretation": "ישר, כן, תוכו כברו." },
  { "word": "פיוט", "interpretation": "שיר." },
  { "word": "פיוטי", "interpretation": "מלא רוח שירה." },
  { "word": "פיון", "interpretation": "1. חייל פשוט 2. כלי משחק." },
  { "word": "פיזור נפש", "interpretation": "חוסר ריכוז, בלבול, פיזור דעת." },
  { "word": "פיזז", "interpretation": "רקד, כירכר." },
  { "word": "פיזר דרכיו", "interpretation": "הלך בדרך רעה." },
  { "word": "פיטם", "interpretation": "1. האכיל במזון רב 2. מילא דבר מה בחומר (כטבק במקטרת)." },
  { "word": "פיכה", "interpretation": "זרם, נבע, פרץ." },
  { "word": "פיכח", "interpretation": "שאינו שיכור." },
  { "word": "פיל לבן", "interpretation": "כינוי למשהו גרנדיוזי וחסר תועלת." },
  { "word": "פילוס", "interpretation": "סלילה, הבקעת דרך." },
  { "word": "פילח", "interpretation": "חתך, ביקע, שיסף, שיסע." },
  { "word": "פילל", "interpretation": "האמין, צפה, העלה על הדעת." },
  { "word": "פילנטרופ", "interpretation": "נדבן, תורם לצדקה." },
  { "word": "פימה", "interpretation": "סנטר כפול." },
  { "word": "פיס", "interpretation": "גורל, הגרלה, פור, גד." },
  { "word": "פיסח", "interpretation": "צולע, נכה, חיגר." },
  { "word": "פיק", "interpretation": "רעד, חלחלה, חיל, פלצות." },
  { "word": "פיקה", "interpretation": "בליטה, זיז." },
  { "word": "פיקח", "interpretation": "1. חכם, נבון 2. שאינו עיוור 3. שאינו חירש." },
  { "word": "פיקטיבי", "interpretation": "לא אמיתי, מדומה, בדוי." },
  { "word": "פיר", "interpretation": "חור, גומה, חפירה." },
  { "word": "פירוש דחוק", "interpretation": "פירוש לא סביר." },
  { "word": "פישפש", "interpretation": "דלת קטנה." },
  { "word": "פיתום", "interpretation": "אדם המדבר מהבטן." },
  { "word": "פך", "interpretation": "כלי קטן לנוזלים." },
  { "word": "פכים קטנים", "interpretation": "דברים חסרי ערך." },
  { "word": "פכסום", "interpretation": "גריסה, קולות נגיסה באוכל יבש." },
  { "word": "פכסם", "interpretation": "טוסט, צנים, קלי." },
  { "word": "פכפוך", "interpretation": "נביעה, זרימה." },
  { "word": "פכר", "interpretation": "מעך, לחץ בחוזקה." },
  { "word": "פלאח", "interpretation": "איכר, עובד אדמה." },
  { "word": "פלבאי", "interpretation": "נחות מעמד." },
  { "word": "פלבל", "interpretation": "גלגל את עיניו." },
  { "word": "פלג", "interpretation": "חלק." },
  { "word": "פלגיאט", "interpretation": "גניבה ספרותית." },
  { "word": "פלגמטי", "interpretation": "עצלן." },
  { "word": "פלוגתא", "interpretation": "ריב, מחלוקת, פולמוס." },
  { "word": "פלוני", "interpretation": "אלמוני." },
  { "word": "פלורליזם", "interpretation": "ריבוי דעות." },
  { "word": "פלוש", "interpretation": "מסדרון, אכסדרה, פרוזדור." },
  { "word": "פלחה", "interpretation": "ענף חקלאות של תבואת השדה." },
  { "word": "פליה", "interpretation": "שליפה של כינים או פשפשים משיער." },
  { "word": "פלך", "interpretation": "1. אזור, מחוז 2. כישור." },
  { "word": "פלנטה", "interpretation": "כוכב לכת." },
  { "word": "פלס", "interpretation": "מכשיר שנועד לקבוע שדבר מה הוא אופקי." },
  { "word": "פלסתר", "interpretation": "רמאות, זיוף, הונאה." },
  { "word": "פלצור", "interpretation": "לאסו, חבל שבקצהו לולאה ללכידת חיות." },
  { "word": "פלצות", "interpretation": "פחד ותדהמה." },
  { "word": "פמיניזם", "interpretation": "תנועה לשוויון זכויות האישה." },
  { "word": "פמליה", "interpretation": "חבורת בני לוויה." },
  { "word": "פן", "interpretation": "כדי שלא, שמא." },
  { "word": "פן", "interpretation": "צורה, אופן." },
  { "word": "פנומנלי", "interpretation": "בלתי רגיל, גאוני." },
  { "word": "פנטי", "interpretation": "קיצוני באמונתו, קנאי." },
  { "word": "פניאומטי", "interpretation": "עובד על לחץ אוויר." },
  { "word": "פני הדור כפני כלב", "interpretation": "הדור מושחת ביותר." },
  { "word": "פניו רעים", "interpretation": "נרגז." },
  { "word": "פניקה", "interpretation": "בהלה, אימה, יראה, בעתה." },
  { "word": "פנכה", "interpretation": "קערה, צלחת, מגש, טס." },
  { "word": "פס", "interpretation": "עבר, חלף, נעלם." },
  { "word": "פסבדונים", "interpretation": "שם בדוי לסופר." },
  { "word": "פסוקת", "interpretation": "שביל בשיער הראש." },
  { "word": "פסח על שני הסעיפים", "interpretation": "התלבט, היסס." },
  { "word": "פסטורלי", "interpretation": "של תיאורי טבע, אידילי." },
  { "word": "פסיבי", "interpretation": "בלתי פעיל, נטול יוזמה." },
  { "word": "פסיחה", "interpretation": "דילוג." },
  { "word": "פסיכופט", "interpretation": "לא שפוי." },
  { "word": "פסימי", "interpretation": "ספקני, רואה שחורות." },
  { "word": "פסע", "interpretation": "צעד, שעל, פעם." },
  { "word": "פסקנות", "interpretation": "החלטיות." },
  { "word": "פעה", "interpretation": "צעק, נאנק, געה." },
  { "word": "פעם", "interpretation": "צעד, פסע, שעל." },
  { "word": "פפיון", "interpretation": "עניבת פרפר." },
  { "word": "פציפיסט", "interpretation": "שוחר שלום." },
  { "word": "פקד", "interpretation": "1. ציווה 2. ספר, מנה 3. זכר לטובה או לרעה 4. בא לביקור." },
  { "word": "פקולטטיבי", "interpretation": "חופשי." },
  { "word": "פקטור", "interpretation": "גורם." },
  { "word": "פקיעה", "interpretation": "1. הישברות 2. סיום התוקף." },
  { "word": "פקיר", "interpretation": "נזיר החי חיי דלות." },
  { "word": "פרברי העיר", "interpretation": "שכונות בקצה העיר, פאתי העיר, עיבורה של עיר." },
  { "word": "פרגוד", "interpretation": "וילון." },
  { "word": "פרגול", "interpretation": "שוט, מגלב, שבט." },
  { "word": "פרגית", "interpretation": "תרנגולת צעירה." },
  { "word": "פרגמטי", "interpretation": "מעשי, שימושי." },
  { "word": "פרגמנטציה", "interpretation": "קיטוע." },
  { "word": "פרד", "interpretation": "מספר אי זוגי." },
  { "word": "פרודה", "interpretation": "חלקיק, מולקולה." },
  { "word": "פרדוקס", "interpretation": "סתירה לוגית." },
  { "word": "פרובוקציה", "interpretation": "התגרות, שיסוי." },
  { "word": "פרוביזורי", "interpretation": "זמני." },
  { "word": "פרובינציה", "interpretation": "אזור מרוחק מהמרכז, פרבר." },
  { "word": "פרודוקטיבי", "interpretation": "יצרני, מועיל, פורה." },
  { "word": "פרודיה", "interpretation": "חיקוי לעגני ושנון למצב או אדם." },
  { "word": "פרוון", "interpretation": "יצרן ומוכר פרוות." },
  { "word": "פרוזאי", "interpretation": "ענייני, שגרתי, משעמם." },
  { "word": "פרוזה", "interpretation": "ספרות כתובה ללא משקל וחריזה." },
  { "word": "פרוטוטייפ", "interpretation": "אב טיפוס." },
  { "word": "פרולוג", "interpretation": "הקדמה." },
  { "word": "פרזול", "interpretation": "1. הוספת ועיבוד מתכות 2. חיבור פרסות ברזל לסוס." },
  { "word": "פרי בטן", "interpretation": "צאצא, עובר, ילוד." },
  { "word": "פריסקופ", "interpretation": "אמצעי אופטי המאפשר ראיה מעל למפלס בו נמצא הצופה (נפוץ  בשימוש בצוללות)." },
  { "word": "פרלמנט", "interpretation": "בית נבחרים." },
  { "word": "פרמיירה", "interpretation": "בכורה, הפעם הראשונה בה מועלה מחזה או סרט." },
  { "word": "פרקט", "interpretation": "רצפת לוחות עץ." }
]
