window.raish = [
  { "word": "ראה את הנולד", "interpretation": "צפה את העתיד." },
  { "word": "ראה צל הרים כהרים", "interpretation": "לא ראה דברים כפי שהם." },
  { "word": "ראוותן", "interpretation": "אוהב להראות את עצמו ולהרשים אחרים." },
  { "word": "ראיה", "interpretation": "הוכחה, עדות." },
  { "word": "ראש לשועלים", "interpretation": "ראשון בין חלשים." },
  { "word": "ראשית חכמה", "interpretation": "ראשית כל, כתנאי ראשוני." },
  { "word": "רבב", "interpretation": "1. כתם שמן; 2. פגם; 3. פגם מוסרי." },
  { "word": "רבבה", "interpretation": "עשרת אלפים, ריבוא." },
  { "word": "רבותא", "interpretation": "דבר שיש בו חידוש, יתרון." },
  { "word": "רביב", "interpretation": "גשם, מטר." },
  { "word": "רביד", "interpretation": "תכשיט לצוואר, ענק." },
  { "word": "רביכה", "interpretation": "קמח מעורבב בשמן." },
  { "word": "רבץ לפתחו", "interpretation": "ארב לו." },
  { "word": "רברסבילי", "interpretation": "הפיך." },
  { "word": "רבתי", "interpretation": "גדולה, מורחבת." },
  { "word": "רגב", "interpretation": "גוש עפר." },
  { "word": "רגיונלי", "interpretation": "אזורי." },
  { "word": "רגל", "interpretation": "פעם (שלושה רגלים– שלוש פעמים)." },
  { "word": "רגם", "interpretation": "זרק אבנים, סקל." },
  { "word": "רגן", "interpretation": "התלונן, רטן." },
  { "word": "רגרסיה", "interpretation": "נסיגה לאחור." },
  { "word": "רדוד", "interpretation": "לא עמוק." },
  { "word": "רדוקציה", "interpretation": "הפחתה, צמצום." },
  { "word": "רדיד", "interpretation": "צעיף, מטפחת." },
  { "word": "רדייה", "interpretation": "הוצאה (לרוב דבש מכוורת)." },
  { "word": "רדיקלי", "interpretation": "קיצוני." },
  { "word": "רהב", "interpretation": "גאווה, יוהרה, שחץ, התנשאות." },
  { "word": "רהוט", "interpretation": "שוטף בדיבור, שגור." },
  { "word": "רהוי", "interpretation": "הססן, פחדן, חיישן, רך לב." },
  { "word": "רובד", "interpretation": "שכבה, נדבך, סובסטרט." },
  { "word": "רובץ", "interpretation": "שוכן." },
  { "word": "רודן", "interpretation": "שליט יחיד, עריץ, טירן." },
  { "word": "רווה נחת", "interpretation": "שמח מאוד." },
  { "word": "רווח", "interpretation": "נפוץ, מצוי." },
  { "word": "רוח נכאים", "interpretation": "בעצב." },
  { "word": "רוח עוועים", "interpretation": "טירוף, שיגעון." },
  { "word": "רוח קדים", "interpretation": "רוח חמה." },
  { "word": "רוחב יד", "interpretation": "נדיבות, רוחב לב." },
  { "word": "רום", "interpretation": "גובה." },
  { "word": "רומח", "interpretation": "חנית, כידון." },
  { "word": "רועץ", "interpretation": "מכשול, תקלה, פוקה." },
  { "word": "רופס", "interpretation": "רך, חלוש, רופף." },
  { "word": "רושף", "interpretation": "לוהט, יוקד, מתיז ניצוצות." },
  { "word": "רז", "interpretation": "סוד, תעלומה, צפנת." },
  { "word": "רזוננס", "interpretation": "תהודה." },
  { "word": "רחב גרם", "interpretation": "עב בשר, עבה, שמן." },
  { "word": "רחל", "interpretation": "כבשה בוגרת." },
  { "word": "רחמנא ליצלן", "interpretation": "יצילנו האל." },
  { "word": "רחץ בנקיון כפיו", "interpretation": "התנער מאחריות." },
  { "word": "רחש", "interpretation": "1. מחשבה, הרהור; 2. רשרוש." },
  { "word": "רחשי לב", "interpretation": "הרהורים, רצונות ורגשות כמוסים." },
  { "word": "רטוריקה", "interpretation": "תורת הנאום." },
  { "word": "רטרוספקטיבה", "interpretation": "הסתכלות לעבר." },
  { "word": "ריאלי", "interpretation": "מציאותי, ממשי, מוחשי, מעשי." },
  { "word": "ריבב", "interpretation": "ליכלך." },
  { "word": "ריבה", "interpretation": "נערה, עלמה." },
  { "word": "ריבוא", "interpretation": "עשרת אלפים, רבבה." },
  { "word": "ריבוני", "interpretation": "עצמאי, אוטונומי, סוברני." },
  { "word": "ריבית קצוצה", "interpretation": "ריבית מופרזת." },
  { "word": "רידוד", "interpretation": "השטחה, השטחת בצק (ראה \"מערוך\")." },
  { "word": "ריחיים בצווארו", "interpretation": "נתון תחת עול." },
  { "word": "ריטואל", "interpretation": "טקס, פולחן." },
  { "word": "ריטש", "interpretation": "קרע לגזרים, שיסף, ביתר." },
  { "word": "רימה", "interpretation": "שלב ראשוני בהתפתחות חרקים וזבובים." },
  { "word": "רינן", "interpretation": "1. שר, זימר; 2. הוציא דיבה." },
  { "word": "ריף", "interpretation": "סלע בים, שונית." },
  { "word": "ריצה", "interpretation": "פייס." },
  { "word": "ריצוד", "interpretation": "תנועות מהירות ומקריות לכל עבר." },
  { "word": "ריק", "interpretation": "ואקום." },
  { "word": "ריקא", "interpretation": "פוחז." },
  { "word": "ריקוע", "interpretation": "רידוד, הפיכה לשטוח." },
  { "word": "רישא", "interpretation": "החלק הראשון." },
  { "word": "רך לב", "interpretation": "פחדן, מוג לב, חיישן, רהוי." },
  { "word": "רכב", "interpretation": "האבן העליונה בריחיים." },
  { "word": "רכיב", "interpretation": "חלק, מרכיב." },
  { "word": "רכיכה", "interpretation": "בעל חיים חסר חוליות." },
  { "word": "רכינה", "interpretation": "התכופפות, גהירה, גחינה." },
  { "word": "רכס", "interpretation": "כיפתר, כיבן." },
  { "word": "רם דרג", "interpretation": "רם מעלה, חשוב, נכבד." },
  { "word": "רמה קרנו", "interpretation": "זכה להערכה ולכבוד." },
  { "word": "רמץ", "interpretation": "אפר חם, שיירי גחלים." },
  { "word": "רמש", "interpretation": "שם כולל לחרקים וזוחלים." },
  { "word": "רנדומלי", "interpretation": "אקראי, שרירותי." },
  { "word": "רנטבילי", "interpretation": "רווחי, משתלם." },
  { "word": "רסיטל", "interpretation": "קונצרט של אמן אחד." },
  { "word": "רע", "interpretation": "חבר, ידיד, עמית." },
  { "word": "רעבתן", "interpretation": "זללן, גרגרן." },
  { "word": "רעה בשדות זרים", "interpretation": "פנה לתרבות שונה או לאמונה אחרת." },
  { "word": "רעה חולה", "interpretation": "צרה גדולה." },
  { "word": "רעלה", "interpretation": "צעיף לכיסוי הפנים." },
  { "word": "רעץ", "interpretation": "שבר, פוצץ, רצץ." },
  { "word": "רף", "interpretation": "מדף, איצטבה, נדבך, קורה." },
  { "word": "רפה", "interpretation": "נחלש, כהה." },
  { "word": "רפה שכל", "interpretation": "מוגבל בשכלו." },
  { "word": "רפורמה", "interpretation": "תיקון יסודי, שידוד מערכות." },
  { "word": "רפיון רוח", "interpretation": "חולשה." },
  { "word": "רפרזנטטיבי", "interpretation": "ייצוגי." },
  { "word": "רפרף", "interpretation": "ריחף." },
  { "word": "רפרפת", "interpretation": "פודינג, חביצה." },
  { "word": "רפש", "interpretation": "בוץ, לכלוך, דומן, סחי." },
  { "word": "רץ", "interpretation": "שליח מהיר, בלדר, מלאך, ציר." },
  { "word": "רצען", "interpretation": "1. סנדלר; 2. אומן העובד בעור." },
  { "word": "רצץ", "interpretation": "שבר, ניפץ, רעץ." },
  { "word": "רקבובית", "interpretation": "חומר אורגני שהרקיב." },
  { "word": "רקויאם", "interpretation": "שיר אבל, שיר אשכבה." },
  { "word": "רקח", "interpretation": "ערבב." },
  { "word": "רקיע", "interpretation": "שמים." },
  { "word": "רקיעה", "interpretation": "דריכה בכוח." },
  { "word": "רקיק", "interpretation": "עוגה, אפיפית, צפיחית, פכסם." },
  { "word": "רקק", "interpretation": "ביצה, מקווה מים עכורים." },
  { "word": "רקק", "interpretation": "ירק." },
  { "word": "רש", "interpretation": "עני, דלפון, דל, אביון." },
  { "word": "רשות הרבים", "interpretation": "מקום ציבורי." },
  { "word": "רשף", "interpretation": "גחלת, ניצוץ, שביב." },
  { "word": "רתת", "interpretation": "רעד, רטט." },
  { "word": "רתתן", "interpretation": "הססן" }
]

