window.sameh = [
  { "word": "סאה", "interpretation": "מידה קדומה." },
  { "word": "סאון", "interpretation": "המולה." },
  { "word": "סאטירה", "interpretation": "יצירה ביקורתית ועוקצנית." },
  { "word": "סב", "interpretation": "הסתובב." },
  { "word": "סבא", "interpretation": "שתה לשוכרה, התבסם." },
  { "word": "סבולת", "interpretation": "כוח סבל, כושר עמידה במאמץ." },
  { "word": "סבכה", "interpretation": "מחיצה עשויה רשת." },
  { "word": "סבר פנים", "interpretation": "ארשת פנים, הבעת פנים." },
  { "word": "סברת כרס", "interpretation": "השערה בלתי מבוססת." },
  { "word": "סגה", "interpretation": "רומן המספר תולדות משפחה אחת." },
  { "word": "סגולה", "interpretation": "תכונה טובה." },
  { "word": "סגולי", "interpretation": "ייחודי, ספציפי, נבחר." },
  { "word": "סגידה", "interpretation": "הערצה." },
  { "word": "סגלגל", "interpretation": "אליפטי, בצורת ביצה." },
  { "word": "סגסוגת", "interpretation": "תערובת מתכות, מסג, נתך." },
  { "word": "סגפן", "interpretation": "מתענה, מתנזר, פוריטני, פרוש." },
  { "word": "סגרגציה", "interpretation": "הפרדה." },
  { "word": "סד", "interpretation": "כלי עינויים בו סגרו רגלי אסירים." },
  { "word": "סדן", "interpretation": "1. גוש עץ או מתכת המשמש נפח בעבודתו 2. גדם, גזע עץ כרות." },
  { "word": "סדקית", "interpretation": "שם כולל לחפצים קטנים, ובעיקר כלי תפירה." },
  { "word": "סהר", "interpretation": "ירח." },
  { "word": "סובב אותו בכחש", "interpretation": "שיקר." },
  { "word": "סובטילי", "interpretation": "מעודן." },
  { "word": "סוביודיצה", "interpretation": "איסור פרסום עמדה במהלך דיון משפטי." },
  { "word": "סוביקטיבי", "interpretation": "יחס המבוסס על רגשות אישיים." },
  { "word": "סובך", "interpretation": "(גם סבך) עובי היער, המקום בו עצים וצמחים גדלים בצפיפות." },
  { "word": "סובלימציה", "interpretation": "1. עידון, ריסון רגשות בלתי רצויים 2. המראה, מעבר כימי ממוצק לגז." },
  { "word": "סובסטרט", "interpretation": "שכבה, מצע, בסיס, נדבך." },
  { "word": "סוברני", "interpretation": "עצמאי, ריבוני, אוטונומי." },
  { "word": "סוגיה", "interpretation": "נושא." },
  { "word": "סוגסטיבי", "interpretation": "משפיע, משכנע." },
  { "word": "סוגר", "interpretation": "כלוב." },
  { "word": "סודר", "interpretation": "1. מטפחת 2. אפודה." },
  { "word": "סוור", "interpretation": "סבל בנמל." },
  { "word": "סוכך", "interpretation": "הסתיר, כיסה." },
  { "word": "סולד", "interpretation": "נרתע." },
  { "word": "סולידי", "interpretation": "רציני, מיושב, שקול." },
  { "word": "סולידריות", "interpretation": "הזדהות, שותפות לרגשות האחר." },
  { "word": "סוללה", "interpretation": "תל עפר." },
  { "word": "סולרי", "interpretation": "מופעל באמצעות חום השמש." },
  { "word": "סומא", "interpretation": "עיוור." },
  { "word": "סומטי", "interpretation": "גופני." },
  { "word": "סוס טרויאני", "interpretation": "בגידה, גיס חמישי." },
  { "word": "סופיסטיקציה", "interpretation": "תחכום." },
  { "word": "סופר צללים", "interpretation": "מי שכותב ספר בשמו של אחד אחר." },
  { "word": "סוקר", "interpretation": "מתבונן." },
  { "word": "סוריאליסטי", "interpretation": "על מציאותי." },
  { "word": "סורר ומורה", "interpretation": "מרדן, עקשן." },
  { "word": "סחבה", "interpretation": "סמרטוט, מטלית." },
  { "word": "סחור סחור", "interpretation": "1. סביב סביב 2. בעקיפין ולא במישרין." },
  { "word": "סחי", "interpretation": "אשפה, לכלוך, זוהמה, דומן." },
  { "word": "סחרחרה", "interpretation": "קרוסלה." },
  { "word": "סטאטי", "interpretation": "קבוע במקום." },
  { "word": "סטבילי", "interpretation": "יציב." },
  { "word": "סטקאטו", "interpretation": "מקוטע, קטוע, לא מחובר (במקור מונח מוסיקלי)." },
  { "word": "סטגנציה", "interpretation": "קיפאון." },
  { "word": "סטואי", "interpretation": "יציב, אדיש, כובש את יצרו." },
  { "word": "סטטוס", "interpretation": "מצב, עמדה, מעמד." },
  { "word": "סטטוס קוו", "interpretation": "מצב הקיים ללא שינוי." },
  { "word": "סטרוקטורה", "interpretation": "מבנה." },
  { "word": "סיבר את האוזן", "interpretation": "הסביר באופן ברור." },
  { "word": "סיגים", "interpretation": "פסולת מתכת." },
  { "word": "סיזיפי", "interpretation": "עבודת פרך ללא תועלת, ברכה לבטלה." },
  { "word": "סיטונות", "interpretation": "מסחר בקנה מידה גדול." },
  { "word": "סיטרא אחרא", "interpretation": "סיעת השטן, כוחות האופל." },
  { "word": "סייג", "interpretation": "גבול." },
  { "word": "סיכה", "interpretation": "מריחה, משיחה." },
  { "word": "סיכוך", "interpretation": "כיסוי, חיפוי, קירוי." },
  { "word": "סיכל", "interpretation": "הכשיל, ביטל, הפר, שם לאל." },
  { "word": "סילוגיזם", "interpretation": "הסקת מסקנה מצירוף שתי טענות, היקש." },
  { "word": "סימולציה", "interpretation": "הדמיה." },
  { "word": "סימפוזיון", "interpretation": "כינוס של אנשים שונים לשם החלפת דעות." },
  { "word": "סימפטום", "interpretation": "סימן היכר לתופעה, תסמין." },
  { "word": "סימפתיה", "interpretation": "אהדה, שותפות ברגש הזולת." },
  { "word": "סינכרוני", "interpretation": "המתרחש בעת ובעונה אחת, סימולטני, בד בבד." },
  { "word": "סינרגיה", "interpretation": "שיתוף פעולה." },
  { "word": "סינתזה", "interpretation": "שילוב, הרכבה." },
  { "word": "סיסטמתי", "interpretation": "שיטתי." },
  { "word": "סיף", "interpretation": "חרב, שבריה, פגיון, שלח." },
  { "word": "סיפא", "interpretation": "סוף." },
  { "word": "סיפור בדים", "interpretation": "מעשייה." },
  { "word": "סיפורי בדים", "interpretation": "שקר, בדיה, כזב." },
  { "word": "סיקל", "interpretation": "פינה אבנים." },
  { "word": "סיקרה", "interpretation": "אדום עז, שני, ארגמן, חכלילי." },
  { "word": "סיתת", "interpretation": "הקציע והחליק אבנים." },
  { "word": "סך", "interpretation": "קהל רב, המון, אספסוף, ערב רב." },
  { "word": "סכוי", "interpretation": "שקוף." },
  { "word": "סכוף", "interpretation": "מדוכא, מעונה, דווי, מסוגף." },
  { "word": "סכימה", "interpretation": "סרטוט, תרשים." },
  { "word": "סכל", "interpretation": "טיפש, שוטה, כסיל, אוויל." },
  { "word": "סכר", "interpretation": "סגר, סתם." },
  { "word": "סכר את פיו", "interpretation": "שתק." },
  { "word": "סלידה", "interpretation": "דחייה עמוקה, רתיעה." },
  { "word": "סלנג", "interpretation": "שפה מדוברת בלתי רשמית, עגה." },
  { "word": "סלע המחלוקת", "interpretation": "נושא לחילוקי דעות." },
  { "word": "סלקטיבי", "interpretation": "בררן." },
  { "word": "סלתה ושמנה", "interpretation": "הטובים והנבחרים, אליטה, עילית." },
  { "word": "סמובר", "interpretation": "מיחם." },
  { "word": "סמוכה", "interpretation": "עמוד הנושא משקל של משהו או תומך בו." },
  { "word": "סמור", "interpretation": "זקוף, נוקשה." },
  { "word": "סמך ידו", "interpretation": "נתן את הסכמתו." },
  { "word": "סמנטיקה", "interpretation": "חקר משמעות המילים." },
  { "word": "סנדק", "interpretation": "שושבין, מעניק חסות." },
  { "word": "סנוקרת", "interpretation": "מכת אגרוף." },
  { "word": "סנורים", "interpretation": "עיוורון." },
  { "word": "סנט", "interpretation": "לעג, לגלג, הקניט, קנטר." },
  { "word": "סנטימנטלי", "interpretation": "רגשן." },
  { "word": "סעד", "interpretation": "עזר, תמך, טיפל." },
  { "word": "ספון", "interpretation": "מסוגר." },
  { "word": "ספונטני", "interpretation": "לא מתוכנן." },
  { "word": "ספורדי", "interpretation": "מפוזר, בלתי סדיר, אקראי." },
  { "word": "ספח", "interpretation": "חיבר, צירף, שיתף, ספג." },
  { "word": "ספיח", "interpretation": "נספח לדבר אחר." },
  { "word": "ספין", "interpretation": "ציפוי חלק מהקיר, פנל." },
  { "word": "ספיר", "interpretation": "אבן יקרה." },
  { "word": "ספירה", "interpretation": "1. כדור 2. חוג, היקף, סביבה." },
  { "word": "ספיריטואלי", "interpretation": "רוחני." },
  { "word": "ספציפי", "interpretation": "מסוים." },
  { "word": "ספק", "interpretation": "1. אי וודאות, פקפוק 2. היכה מתוך צער, דפק." },
  { "word": "ספקולציה", "interpretation": "השערה." },
  { "word": "ספקטרום", "interpretation": "מגוון האפשרויות." },
  { "word": "ספר", "interpretation": "גבול, תחום, סייג." },
  { "word": "ספרא וסיפא", "interpretation": "אדם או שיטה המשלבים את הרוחני עם הצבאי." },
  { "word": "ספרטני", "interpretation": "מסתפק במועט, סגפן." },
  { "word": "סקולריזציה", "interpretation": "הפיכה לחילוני." },
  { "word": "סקונדרי", "interpretation": "משני." },
  { "word": "סקטור", "interpretation": "איזור, חלק, תחום, מיגזר." },
  { "word": "סקל", "interpretation": "זרק אבנים, רגם." },
  { "word": "סקנדל", "interpretation": "שערוריה." },
  { "word": "סר", "interpretation": "נרגז, זעף." },
  { "word": "סר", "interpretation": "זז, נע, מש, פנה, נטה." },
  { "word": "סר חינו", "interpretation": "הפסיק למצוא חן, נמאס." },
  { "word": "סר למרות", "interpretation": "ציית." },
  { "word": "סר מרע", "interpretation": "מתרחק מרוע." },
  { "word": "סרהב", "interpretation": "הפציר, עתר." },
  { "word": "סרוח", "interpretation": "שרוע." },
  { "word": "סרח", "interpretation": "חלק עודף, שוליים, שובל." },
  { "word": "סרח", "interpretation": "פשע, בגד." },
  { "word": "סרח עודף", "interpretation": "טפל, תוספת, נספח." },
  { "word": "סריג", "interpretation": "מעשה רשת." },
  { "word": "סרקופג", "interpretation": "ארון קבורה, גלוסקמה." },
  { "word": "סרקזם", "interpretation": "צחוק ארסי, עוקצני, אירוני." },
  { "word": "סתגלן", "interpretation": "מי שמסתגל לכל מצב." },
  { "word": "סתום", "interpretation": "לא ברור, לא מובן." },
  { "word": "סתם את הגולל", "interpretation": "סגר באופן סופי." }
]
