window.shin = [
  { "word": "שאה", "interpretation": "נחרב." },
  { "word": "שאול", "interpretation": "גיהינום, תופת." },
  { "word": "שאון", "interpretation": "רעש, המולה." },
  { "word": "שאור שבעיסה", "interpretation": "החלק העיקרי." },
  { "word": "שאט", "interpretation": "בוז, תיעוב, סלידה." },
  { "word": "שאיה", "interpretation": "חורבן, הרס." },
  { "word": "שאר בשר", "interpretation": "קרוב משפחה." },
  { "word": "שאר רוח", "interpretation": "עומק מחשבה מעבר לעניינים יומיומיים." },
  { "word": "שבב", "interpretation": "רסיס, נתז, שבריר, פלח." },
  { "word": "שבט", "interpretation": "מקל, מטה, שוט, פרגול, מגלב." },
  { "word": "שביב", "interpretation": "ניצוץ, רשף, קרן אור." },
  { "word": "שביל הזהב", "interpretation": "דרך ממוצעת." },
  { "word": "שביל הנחש", "interpretation": "דרך עקלקלה." },
  { "word": "שביס", "interpretation": "כיסוי ראש." },
  { "word": "שבלוני", "interpretation": "שגרתי, מוכר, חסר ייחוד." },
  { "word": "שבע ימים", "interpretation": "קשיש." },
  { "word": "שבעה מדורי גיהינום", "interpretation": "ייסורים קשים." },
  { "word": "שבק", "interpretation": "עזב, נטש." },
  { "word": "שבק חיים לכל חי", "interpretation": "מת, בר מינן." },
  { "word": "שבריה", "interpretation": "חרב קצרה, פגיון, סיף, שלח." },
  { "word": "שבריר", "interpretation": "פלח, רסיס, שבב, נתז." },
  { "word": "שגגה", "interpretation": "טעות, שגיאה, משוגה." },
  { "word": "שגור", "interpretation": "רגיל." },
  { "word": "שגיא", "interpretation": "עצום, כביר, נשגב, שגיב." },
  { "word": "שדוף", "interpretation": "מיובש, נבוב, צפוד, חסר תוכן." },
  { "word": "שדמה", "interpretation": "שדה תבואה או כרם." },
  { "word": "שה תמים", "interpretation": "כינוי לאדם הנראה תמים רק למראית עין." },
  { "word": "שובה", "interpretation": "מתינות, נחת." },
  { "word": "שובה לב", "interpretation": "גורם לרגשות חיבה כלפיו." },
  { "word": "שוביניזם", "interpretation": "התנגדות לשוויון זכויות לנשים." },
  { "word": "שובל", "interpretation": "1. שוליים; 2. עקבות במים או באוויר." },
  { "word": "שווה בנפשך", "interpretation": "תאר לעצמך." },
  { "word": "שווה לכל נפש", "interpretation": "מיועד ומתאים לכל אחד." },
  { "word": "שווה נפש", "interpretation": "אדיש." },
  { "word": "שוזף עינו", "interpretation": "מביט." },
  { "word": "שוחה", "interpretation": "בור, מהמורה, פוקה, דחי, פח." },
  { "word": "שוחר", "interpretation": "חובב." },
  { "word": "שומה", "interpretation": "1. הערכה, אומדן; 2. בליטה בעור." },
  { "word": "שומה עליו", "interpretation": "חובה עליו, צריך." },
  { "word": "שוע", "interpretation": "עשיר, אריסטוקרט." },
  { "word": "שועה", "interpretation": "זעקה, קריאה לעזרה." },
  { "word": "שועט", "interpretation": "דוהר." },
  { "word": "שופי", "interpretation": "נחת." },
  { "word": "שופרא דשופרא", "interpretation": "מיטב, מובחר." },
  { "word": "שוקק חיים", "interpretation": "מלא אנשים ופעילות." },
  { "word": "שוקת", "interpretation": "כלי עמוק להשקיית בהמות." },
  { "word": "שור!", "interpretation": "ראה, הבט, הסתכל." },
  { "word": "שורר", "interpretation": "קיים, מאפיין מקום או מצב." },
  { "word": "שושבין", "interpretation": "חבר, בן לוויה, סנדק." },
  { "word": "שזר", "interpretation": "שילב." },
  { "word": "שח", "interpretation": "התכופף, רכן, גחן, גהר, שחה." },
  { "word": "שחוח", "interpretation": "כפוף." },
  { "word": "שחון", "interpretation": "חם ויבש." },
  { "word": "שחור על גבי לבן", "interpretation": "מפורש." },
  { "word": "שחל", "interpretation": "אריה, כפיר, לביא, ליש." },
  { "word": "שחץ", "interpretation": "גאווה, יהירות, התפארות." },
  { "word": "שחק", "interpretation": "שמיים." },
  { "word": "שחרית", "interpretation": "1. שעת בוקר; 2. תפילת בוקר." },
  { "word": "שטח", "interpretation": "פרס." },
  { "word": "שטח בקשתו בפניו", "interpretation": "ביקש מאוד, התחנן, חילה את פניו." },
  { "word": "שטם", "interpretation": "שנא, צרר." },
  { "word": "שטנה", "interpretation": "דברי גנאי, לעז, עלילה." },
  { "word": "שיבוט", "interpretation": "1. חביטה, רידוד; 2. שכפול גנטי." },
  { "word": "שיג ושיח", "interpretation": "משא ומתן, שקלא וטריא." },
  { "word": "שיגיון", "interpretation": "הרהור, שרעף, עשתון, הגיג." },
  { "word": "שידד", "interpretation": "פורר את הקרקע, תיחח." },
  { "word": "שידה", "interpretation": "ארון נמוך." },
  { "word": "שידוד מערכות", "interpretation": "תיקון דברים מהיסוד." },
  { "word": "שיהוי", "interpretation": "עיכוב, איחור, דיחוי." },
  { "word": "שיווה", "interpretation": "דימה, תיאר, הציג." },
  { "word": "שיווה בנפשו", "interpretation": "תיאר לעצמו, שיער." },
  { "word": "שיחת זמנו לריק", "interpretation": "בזבז זמן." },
  { "word": "שיכוך", "interpretation": "הרגעה." },
  { "word": "שיכול", "interpretation": "הצלבה, החלפה, היפוך." },
  { "word": "שיכול רגלים", "interpretation": "שילוב רגליים, הנחת רגל על רגל." },
  { "word": "שימצה", "interpretation": "חרפה, גנאי." },
  { "word": "שינס", "interpretation": "חגר, אזר." },
  { "word": "שיסה", "interpretation": "הסית, יצר פרובוקציה." },
  { "word": "שיסע", "interpretation": "קרע, ביתק, ביתר, פילח." },
  { "word": "שיסף", "interpretation": "חתך, שיסע, פילח, ריטש." },
  { "word": "שיעור", "interpretation": "מידה, כמות, גודל." },
  { "word": "שיפול", "interpretation": "תחתית, החלק הנמוך בדבר." },
  { "word": "שיפון", "interpretation": "סוג של דגן." },
  { "word": "שיקוץ", "interpretation": "תועבה, דבר מאוס, פיגול." },
  { "word": "שירבוט", "interpretation": "רישום סימנים ללא משמעות, קשקוש." },
  { "word": "שירות דב", "interpretation": "כוונה טובה עם תוצאות מזיקות." },
  { "word": "שירש", "interpretation": "עקר מהשורש." },
  { "word": "שירת הברבור", "interpretation": "פעולה מהוללת אחרונה לפני פרישה." },
  { "word": "שית", "interpretation": "יסוד, בסיס, אושיה." },
  { "word": "שכב", "interpretation": "האבן התחתונה בריחיים." },
  { "word": "שכוי", "interpretation": "תרנגול, גבר." },
  { "word": "שכיב מרע", "interpretation": "גוסס, חולה אנוש." },
  { "word": "שכיה", "interpretation": "קישוט." },
  { "word": "שכיח", "interpretation": "מצוי, רגיל, נפוץ." },
  { "word": "שכך", "interpretation": "נח, שקט, נרגע." },
  { "word": "שכלתן", "interpretation": "רציונליסט, מי שמעדיף שכל על רגש." },
  { "word": "שכם אחד", "interpretation": "בכוחות משותפים." },
  { "word": "שכתוב", "interpretation": "כתיבה מחדש." },
  { "word": "שלג דאשתקד", "interpretation": "דבר שעבר ואינו מעניין עוד, עפרא דארעא, כקליפת השום." },
  { "word": "שלה", "interpretation": "הוציא מהמים, משה." },
  { "word": "שלהי", "interpretation": "סוף." },
  { "word": "שלווה סטואית", "interpretation": "שלווה מושלמת." },
  { "word": "שלח", "interpretation": "חרב קצרה, פגיון, שבריה, סיף." },
  { "word": "שלח ידו", "interpretation": "1. לקח לעצמו, גנב; 2. עסק ב…" },
  { "word": "שלחופה", "interpretation": "צב." },
  { "word": "שליש", "interpretation": "קצין האחראי על פעילות מנהלתית." },
  { "word": "שלמה", "interpretation": "שמלה, בגד רחב." },
  { "word": "שלמונים", "interpretation": "שוחד, בצע." },
  { "word": "שלף", "interpretation": "שדה שנקצר ועוד לא נחרש." },
  { "word": "שלק", "interpretation": "הרתיח במים, בישל, חלט, שפת." },
  { "word": "שם דבר", "interpretation": "מפורסם, שיצא שמו." },
  { "word": "שם לאל", "interpretation": "הכשיל, סיכל, ביטל." },
  { "word": "שם נפשו בכפו", "interpretation": "הסתכן." },
  { "word": "שם פעמיו", "interpretation": "יצא לדרך, הלך לעבר." },
  { "word": "שמורה", "interpretation": "עפעף." },
  { "word": "שמיטה", "interpretation": "עזיבה, ויתור, נטישה." },
  { "word": "שמיר", "interpretation": "אבן קשה וחזקה." },
  { "word": "שמיר ושית", "interpretation": "שממה, עזובה, ישימון." },
  { "word": "שמנה וסלתה", "interpretation": "עילית." },
  { "word": "שמץ", "interpretation": "מעט, קורט, קורטוב, קמצוץ." },
  { "word": "שנה", "interpretation": "לימד, שינן." },
  { "word": "שני", "interpretation": "אדום, ארגמן, סיקרה, חכלילי." },
  { "word": "שניוני", "interpretation": "ממדרגה שניה." },
  { "word": "שנף", "interpretation": "וניל." },
  { "word": "שנץ", "interpretation": "סרט, שרוך." },
  { "word": "שעבוד", "interpretation": "עבדות, כיבוש." },
  { "word": "שעה", "interpretation": "שם לב, נענה, הקשיב." },
  { "word": "(גם) שעון מקולקל מראה את השעה הנכונה פעמיים ביום", "interpretation": "כל אדם, לא יוצלח ככל שיהיה, עשוי להצליח מדי פעם." },
  { "word": "שעטה", "interpretation": "דפיקה בקרקע ברגל, דהרה." },
  { "word": "שעטנז", "interpretation": "ערבוב מין בשאינו מינו." },
  { "word": "שעיר", "interpretation": "תיש, צפיר." },
  { "word": "שעיר לעזאזל", "interpretation": "כינוי למי שנושא בעונש עבור כולם." },
  { "word": "שעל", "interpretation": "צעד, פעם, פסע." },
  { "word": "שערוך", "interpretation": "הערכה מחדש." },
  { "word": "שפאים", "interpretation": "שבבים העפים בשיוף עץ." },
  { "word": "שפוף", "interpretation": "כפוף, גחון, שחוח, רכון." },
  { "word": "שפחה", "interpretation": "משרתת, אמה." },
  { "word": "שפיר", "interpretation": "יפה, נאה, ניחא." },
  { "word": "שפך על פניו קיתונות של בוז", "interpretation": "העליב, השמיץ, גידף, חירף, גינה, ניאץ, קילס." },
  { "word": "שפל המדרגה", "interpretation": "מצב ירוד." },
  { "word": "שפרה", "interpretation": "יופי, חן." },
  { "word": "שפת", "interpretation": "שם על האש, שלק, חלט." },
  { "word": "שצף", "interpretation": "זרם חזק, שטף." },
  { "word": "שקיקה", "interpretation": "תשוקה, להיטות, כמיהה." },
  { "word": "שקלא וטריא", "interpretation": "משא ומתן, שיח ושיג." },
  { "word": "שקעה שמשו", "interpretation": "ירד מגדולתו." },
  { "word": "שרג", "interpretation": "קלע, סיבך, שילב." },
  { "word": "שרות דב", "interpretation": "שרות בעל תוצאות לוואי שליליות." },
  { "word": "שריג", "interpretation": "ענף, בד, זרד, זלזל, נצר, זמורה." },
  { "word": "שרך דרכיו", "interpretation": "סר מדרך הישר." },
  { "word": "שרלטן", "interpretation": "נוכל, מתחזה, נכלולי." },
  { "word": "שרעפים", "interpretation": "מחשבות, הרהורים, עשתונות." },
  { "word": "שרף", "interpretation": "מלאך, כרוב, אראל." },
  { "word": "שררה", "interpretation": "שלטון, ממשל, אדנות, מרות." },
  { "word": "שש", "interpretation": "שמח, עלז, עלץ, דץ, רן." },
  { "word": "שת", "interpretation": "שם, הניח." },
  { "word": "שתום עין", "interpretation": "עיוור בעין אחת." },
  { "word": "שתת", "interpretation": "נזל, זלג, ניגר." }
]
