window.taf = [
  { "word": "תאב", "interpretation": "רוצה, משתוקק, כמה, מתאווה." },
  { "word": "תאוטה", "interpretation": "האטת המהירות." },
  { "word": "תאניה", "interpretation": "בכי." },
  { "word": "תבל", "interpretation": "עולם, יקום, חלד, קוסמוס." },
  { "word": "תברוגת", "interpretation": "מערכת החריצים בברגים ואומים (גם \"תבריג\")." },
  { "word": "תגר", "interpretation": "סוחר, רוכל, תגרן." },
  { "word": "תגרן", "interpretation": "1. סוחר קטן, רוכל 2. מי שמרבה להתווכח." },
  { "word": "תדיר", "interpretation": "לעיתים קרובות, תכוף." },
  { "word": "תהה על קנקנו", "interpretation": "בחן, בדק, עמד על טיבו." },
  { "word": "תהום הנשיה", "interpretation": "שכחה מוחלטת." },
  { "word": "תו לא", "interpretation": "זהו זה." },
  { "word": "תואי", "interpretation": "מסלול, ציר, נתיב." },
  { "word": "תואנה", "interpretation": "אשמת שקר, עלילה." },
  { "word": "תוגה", "interpretation": "עצב, יגון, דכדוך, דאבה." },
  { "word": "תוהו", "interpretation": "שממה, ישימון, בתה, ציה." },
  { "word": "תוחלת", "interpretation": "תקווה, ציפיה, יהב." },
  { "word": "תוכו כברו", "interpretation": "ישר, אמיתי, כן." },
  { "word": "תוכחה", "interpretation": "נזיפה, הטפת מוסר." },
  { "word": "תוכן", "interpretation": "אסטרונום." },
  { "word": "תולדה", "interpretation": "תוצאה, מסקנה, פועל יוצא." },
  { "word": "תולה את יהבו", "interpretation": "מקווה." },
  { "word": "תופין", "interpretation": "עוגה, אפיפית, רקיק, פכסם." },
  { "word": "תופעות טקטוניות", "interpretation": "תופעות בקליפת כדור הארץ." },
  { "word": "תופת", "interpretation": "1. גיהינום, שאול 2. מוקד, שריפה גדולה." },
  { "word": "תור", "interpretation": "תקופה, עידן." },
  { "word": "תור הזהב", "interpretation": "תקופה מוצלחת, ימי זוהר." },
  { "word": "תורפה", "interpretation": "חולשה, רפיון." },
  { "word": "תושיה", "interpretation": "עצה, חוכמה, כושר המצאה." },
  { "word": "תזה", "interpretation": "הנחת יסוד, אקסיומה." },
  { "word": "תזזית", "interpretation": "טירוף, שיגעון, דיבוק, אמוק." },
  { "word": "תחוח", "interpretation": "רך." },
  { "word": "תחולה", "interpretation": "מועד ההתחלה." },
  { "word": "תחום", "interpretation": "מגודר, מוגבל." },
  { "word": "תחח", "interpretation": "פורר." },
  { "word": "תחיבה", "interpretation": "נעיצה, תקיעה, הכנסת דבר לתוך דבר." },
  { "word": "תחינה", "interpretation": "תפילה, בקשת רחמים, עתירה." },
  { "word": "תחלואה", "interpretation": "מחלה." },
  { "word": "תחליב", "interpretation": "תערובת נוזלים, אמולסיה." },
  { "word": "תחריט", "interpretation": "ציור חקוק במתכת." },
  { "word": "תיאולוגיה", "interpretation": "חקר האלוהות." },
  { "word": "תיאוקרטיה", "interpretation": "שלטון שאנשי דת עומדים בראשו." },
  { "word": "תיבת פנדורה", "interpretation": "פרשה הטומנת בחובה צרות." },
  { "word": "תיגר", "interpretation": "ריב, תגרה, קטטה." },
  { "word": "תיכון", "interpretation": "אמצעי, נמצא בתווך." },
  { "word": "תימרות עשן", "interpretation": "עמודי עשן העולים משריפה." },
  { "word": "תינה", "interpretation": "1. סיפר, תיאר 2. קונן, ספד." },
  { "word": "תינה אהבים", "interpretation": "התעלס, התלטף." },
  { "word": "תיעב", "interpretation": "סלד, מאס, קצה נפשו, בחל." },
  { "word": "תיעול", "interpretation": "הפניה לאפיקים הרצויים." },
  { "word": "תיקן", "interpretation": "מקק, ג'וק." },
  { "word": "תירוש", "interpretation": "יין חדש, מיץ ענבים אשר איננו משכר (ראה גם \"נקטר\" ו\"עסיס\")." },
  { "word": "תיתורה", "interpretation": "שוליים, סרח." },
  { "word": "תכונה", "interpretation": "פעילות, התכוננות." },
  { "word": "תככים", "interpretation": "מזימות, סכסכנות." },
  { "word": "תכלית", "interpretation": "מטרה." },
  { "word": "תכריכים", "interpretation": "בדים העוטפים את גופת המת." },
  { "word": "תכתיב", "interpretation": "כפייה לפעול בצורה מסויימת." },
  { "word": "תל", "interpretation": "גבעה מלאכותית, גל, ערמה." },
  { "word": "תלאות", "interpretation": "צרות, ייסורים, תלאובות." },
  { "word": "תלה את הקולר בצווארו", "interpretation": "האשים." },
  { "word": "תלה עצמו באילן גדול", "interpretation": "הסתמך בדבריו על גדולים ממנו." },
  { "word": "תלוי ועומד", "interpretation": "ממתין להכרעה, מוטל בספק." },
  { "word": "תלוי על בלימה", "interpretation": "ללא בסיס." },
  { "word": "תלי", "interpretation": "1. קולב לתליית בדים 2. אשפה, תיק לחיצים." },
  { "word": "תלם", "interpretation": "חריץ שהמחרשה עושה באדמה, מענית." },
  { "word": "תם", "interpretation": "תמים, נאיבי, שלם." },
  { "word": "תם", "interpretation": "נגמר, נשלם." },
  { "word": "תמוכה", "interpretation": "משענת, סמוכה." },
  { "word": "תמורה", "interpretation": "1. תחליף 2. שינוי." },
  { "word": "תמחור", "interpretation": "קביעת מחירו של מוצר או שירות." },
  { "word": "תמימות דעים", "interpretation": "הסכמה, קונצנזוס." },
  { "word": "תמיר", "interpretation": "גבוה, זקוף, רם קומה." },
  { "word": "תמלוגים", "interpretation": "תשלומים הניתנים לבעלי זכויות לאורך זמן." },
  { "word": "תמליל", "interpretation": "טקסט ערוך, גרסה סופית של הטקסט." },
  { "word": "תמסח", "interpretation": "תנין, קרוקודיל." },
  { "word": "תמרור", "interpretation": "צער, יגון, דכדוך, תוגה, דאבה." },
  { "word": "תנובה", "interpretation": "יבול, פרי, תוצרת חקלאית." },
  { "word": "תסכית רדיו", "interpretation": "מחזה המשודר ברדיו." },
  { "word": "תסמין", "interpretation": "סימן היכר, סימפטום." },
  { "word": "(גם) תרנגול עיוור מוצא לעיתים גרגר", "interpretation": "המזל מאיר גם לחסרי היכולת מדי פעם." },
  { "word": "תעה", "interpretation": "חיפש את הדרך, סטה מדרך הישר." },
  { "word": "תעודת עניות", "interpretation": "מעשה המעיד על אוזלת יד ראויה לגנאי." },
  { "word": "תעוקה", "interpretation": "לחץ, מצוקה, מועקה." },
  { "word": "תענית", "interpretation": "צום." },
  { "word": "תעצומה", "interpretation": "כוח, עוצמה, חוסן, עזוז." },
  { "word": "תעצומות נפש", "interpretation": "כוחות נפש, חוסן מנטלי." },
  { "word": "תער", "interpretation": "סכין גילוח." },
  { "word": "תעתוע", "interpretation": "1. בלבול, טירוף 2. הטעיה." },
  { "word": "(ה)תפוח לא נופל רחוק מהעץ", "interpretation": "לצאצא מכנה משותף גדול עם הוריו או משפחתו." },
  { "word": "תפוח רקוב", "interpretation": "סטה מדרך הישר, איננו נוהג כשורה." },
  { "word": "תפוקה", "interpretation": "תוצאת הייצור, יבול, תוצרת." },
  { "word": "תפל", "interpretation": "חסר טעם." },
  { "word": "תפס את השור בקרניו", "interpretation": "ניגש ישר לעניין, נכנס בעובי הקורה." },
  { "word": "תקיעת כף", "interpretation": "הבטחה, התחייבות." },
  { "word": "תקע טריז", "interpretation": "הפריד." },
  { "word": "תקע יתד", "interpretation": "התיישב, התנחל, השתקע." },
  { "word": "תקרובת", "interpretation": "כיבוד, פרפראות, מגדנות." },
  { "word": "תר", "interpretation": "סייר, חיפש, ריגל, חקר." },
  { "word": "תר אחר לבבו", "interpretation": "הלך אחרי יצרו." },
  { "word": "תרבית", "interpretation": "מושבה של חיידקים שגודלו מלאכותית." },
  { "word": "תרגימא", "interpretation": "קינוח, דברי מתיקה, מגדנות." },
  { "word": "תרווד", "interpretation": "כף לבחישה." },
  { "word": "תרומי", "interpretation": "נעלה, מובחר." },
  { "word": "תרחיש", "interpretation": "תסריט, תיאור התרחשות אפשרית." },
  { "word": "תרי עשר", "interpretation": "שנים עשר, תריסר." },
  { "word": "תרעומת", "interpretation": "כעס, תלונה, טענה, טרוניה." },
  { "word": "תרפיה", "interpretation": "טיפול." },
  { "word": "תרשיש", "interpretation": "1. אחת מאבני החושן 2. נכבד, חשוב." },
  { "word": "תרתי דסתרי", "interpretation": "שני הדברים סותרים זה את זה." },
  { "word": "תרתי משמע", "interpretation": "שני מובנים לדבר." },
  { "word": "תש", "interpretation": "נחלש, עייף, רפה, הדלדל." },
  { "word": "תשואה", "interpretation": "רווח מהשקעה." },
  { "word": "תשובה ניצחת", "interpretation": "תשובה מכרעת, סופית." },
  { "word": "תשומה", "interpretation": "כסף ומשאבים המושקעים בדבר." },
  { "word": "תשורה", "interpretation": "מתנה, שי, דורון, מנחה, תשר." },
  { "word": "תשחורת", "interpretation": "נוער, נעורים, עלומים." },
  { "word": "תשליל", "interpretation": "סרט צילום, נגטיב." },
  { "word": "תשקיף", "interpretation": "דו\"ח הנותן תחזית." },
  { "word": "תשר", "interpretation": "טיפ, מתנה, תשורה, דורון, שי." },
  { "word": "תשתית", "interpretation": "יסוד, בסיס, מסד, כן." },
  { "word": "תתרן", "interpretation": "חסר חוש ריח." }
]

