window.tet = [
  { "word": "טאבו", "interpretation": "1. איסור חברתי; 2. שאסור לגעת בו." },
  { "word": "טאבולה ראזה", "interpretation": "מי שאין לו ידע מוקדם, לוח חלק." },
  { "word": "טבין ותקילין", "interpretation": "תשלום מלא." },
  { "word": "טבע", "interpretation": "יצר, נתן צורה." },
  { "word": "טבעת פוליקרטס", "interpretation": "דבר בלתי הפיך." },
  { "word": "טובין", "interpretation": "נכסים, סחורות, מרכולת." },
  { "word": "טובל ושרץ בידו", "interpretation": "צבוע, מתחסד." },
  { "word": "טוגה", "interpretation": "גלימה, חלוק אותו לבשו בעבר." },
  { "word": "טווה", "interpretation": "שזר, ארג." },
  { "word": "טוזיג", "interpretation": "פיקניק." },
  { "word": "טוטלי", "interpretation": "מלא, כוללני, מוחלט." },
  { "word": "טוטליטרי", "interpretation": "רודני, טירני, עריץ." },
  { "word": "טוטם", "interpretation": "פסל אליל, אליל בתרבויות פרימיטיביות." },
  { "word": "טוטפות", "interpretation": "תפילין." },
  { "word": "טול קורה מבין עיניך", "interpretation": "בדוק את עצמך לפני שתבקר אחרים." },
  { "word": "טולרנטי", "interpretation": "סובלני." },
  { "word": "טורבינה", "interpretation": "מתקן ליצור חשמל (ראה גם \"מחולל\" ו\"גנראטור\")." },
  { "word": "טורבן", "interpretation": "מצנפת של גברים מוסלמים." },
  { "word": "טח", "interpretation": "כיסה." },
  { "word": "טחו עיניו מראות", "interpretation": "לא ראה את הדברים באופן נכון." },
  { "word": "טחוב", "interpretation": "לח, רטוב." },
  { "word": "טחן מים", "interpretation": "עשה משהו בחוסר יעילות." },
  { "word": "טיט", "interpretation": "טין, בוץ, חומר, יון, אדמה לחה." },
  { "word": "טיטני", "interpretation": "ענקי, עצום, מונומנטלי." },
  { "word": "טיכס", "interpretation": "סידר." },
  { "word": "טיכס עצה", "interpretation": "התייעץ, תחבל." },
  { "word": "טין", "interpretation": "בוץ, טיט, חומר, יון." },
  { "word": "טינה", "interpretation": "שנאה, קנאה." },
  { "word": "טיפולוגיה", "interpretation": "חלוקה לסוגים." },
  { "word": "טיפין טיפין", "interpretation": "לאט לאט." },
  { "word": "טירן", "interpretation": "רודן, עריץ, דיקטטור, דספוט." },
  { "word": "טלול", "interpretation": "רענן." },
  { "word": "טלית שכולה תכלת", "interpretation": "אדם או דבר טהור וללא פגם." },
  { "word": "טלף", "interpretation": "פרסה." },
  { "word": "טלפתיה", "interpretation": "קריאת והעברת מחשבות." },
  { "word": "טלקינזיס", "interpretation": "הזזת חפצים באמצעות המחשבה." },
  { "word": "טמיעה", "interpretation": "היטמעות, היקלטות בסביבה." },
  { "word": "טמיר", "interpretation": "נסתר, סודי." },
  { "word": "טמן", "interpretation": "הסתיר, החביא, הכמין." },
  { "word": "טמן ידו בצלחת", "interpretation": "התבטל, ישב בחיבוק ידיים." },
  { "word": "טמן מחט באמתחת", "interpretation": "עשה מעשה לא הגיוני." },
  { "word": "טמן ראשו בחול", "interpretation": "התעלם מהמציאות החמורה." },
  { "word": "טמפו", "interpretation": "קצב." },
  { "word": "טנא", "interpretation": "סל קלוע מענפים." },
  { "word": "טס", "interpretation": "מגש." },
  { "word": "טעם לפגם", "interpretation": "שיש בו מגרעת או ליקוי." },
  { "word": "טען רגליו", "interpretation": "הזדרז ללכת." },
  { "word": "טף", "interpretation": "ילדים קטנים, זאטוטים, דרדקים." },
  { "word": "טפח", "interpretation": "דבר קטן ומועט, זוטא." },
  { "word": "טפחות", "interpretation": "קורות המשמשות לבניית הגג." },
  { "word": "טפי", "interpretation": "כלי לטפטוף נוזלים." },
  { "word": "טפיפה", "interpretation": "הליכה בצעדים קטנים." },
  { "word": "טפל", "interpretation": "לא העיקר." },
  { "word": "טפרים", "interpretation": "ציפורני בעל-חיים." },
  { "word": "טרגי", "interpretation": "עצוב, נוגה, מלא ייסורים." },
  { "word": "טרום", "interpretation": "לפני." },
  { "word": "טרומי", "interpretation": "מוקדם, ראשוני." },
  { "word": "טרוניה", "interpretation": "תלונה, טענה, מענה, תרעומת." },
  { "word": "טרוף", "interpretation": "מעורבב, מבולבל." },
  { "word": "טרזני", "interpretation": "גנדרני, קוקטי." },
  { "word": "טרחן", "interpretation": "טרדן, נודניק." },
  { "word": "טריבונה", "interpretation": "בימה, דוכן." },
  { "word": "טריבונל", "interpretation": "בית משפט מיוחד." },
  { "word": "טריוויאלי", "interpretation": "1. נדוש, בנאלי, שגרתי; 2. מובן מאליו." },
  { "word": "טריז", "interpretation": "יתד המשמשת לרוב לביקוע עצים." },
  { "word": "טרמינולוגיה", "interpretation": "מינוח, מערכת מונחים מקצועית." },
  { "word": "טרנספורמציה", "interpretation": "שינוי צורה." },
  { "word": "טרנסצדנטלי", "interpretation": "מה שנמצא מעבר להכרה." },
  { "word": "טרף", "interpretation": "החלק הרחב והשטוח של העלה." },
  { "word": "טרקלין", "interpretation": "סלון, אולם." },
  { "word": "טרשים", "interpretation": "סלעים." },
]
