window.vav = [
  { "word": "והיא שעמדה לנו", "interpretation": "זה מה שמסייע לנו." },
  { "word": "וולגרי", "interpretation": "המוני, גס." },
  { "word": "וולונטרי", "interpretation": "נעשה מרצון, בהתנדבות." },
  { "word": "וולקני", "interpretation": "שמוצאו מהר געש." },
  { "word": "ווקלי", "interpretation": "קשור לקול." },
  { "word": "וטו", "interpretation": "סמכות הנתונה ליחיד לבטל חוק נגד דעת הרוב." },
  { "word": "ויברציה", "interpretation": "רעידה, תנודה מהירה, רטט." },
  { "word": "ויזואלי", "interpretation": "חזותי." },
  { "word": "ויטאלי", "interpretation": "שופע חיים, חיוני." },
  { "word": "וירטואוז", "interpretation": "אמן בעל שליטה מופלאה." },
  { "word": "וישמן ישורון ויבעט", "interpretation": "התנהג בכפיות טובה." },
  { "word": "וכי", "interpretation": "האומנם, שמא, כלום." },
  { "word": "ולא נודע כי בא אל קרבו", "interpretation": "לא ניכר בו כל שינוי." },
  { "word": "ולד", "interpretation": "תינוק, עולל, ינוקא, זאטוט." },
  { "word": "ומפיר", "interpretation": "ערפד." },
  { "word": "ונדטה", "interpretation": "נקמת דם." },
  { "word": "ונדליזם", "interpretation": "ברבריות, פראות." },
  { "word": "וסל", "interpretation": "איכר משועבד, אריס, צמית." },
  { "word": "ועוד ידו נטויה", "interpretation": "לא סיים את מלאכתו." },
  { "word": "ורבאלי", "interpretation": "מילולי." },
  { "word": "וריאציה", "interpretation": "שינוי, נוסח אחר." },
  { "word": "ותו לא", "interpretation": "ולא עוד, גרידא, אך ורק." }
]
