window.yud = [
  { "word": "יאה", "interpretation": "ראוי." },
  { "word": "יבב", "interpretation": "בכה, התייפח, ילל." },
  { "word": "יבום", "interpretation": "נישואי אדם לאלמנת אחיו, שמת ולא הותיר אחריו בנים." },
  { "word": "יבדל\"א", "interpretation": "ראשי התיבות של יבדל לחיים ארוכים." },
  { "word": "יבם", "interpretation": "אחי הבעל, גיס." },
  { "word": "יגון", "interpretation": "צער, אבל, דאבה, דכדוך, תוגה." },
  { "word": "יגיע כפיים", "interpretation": "עבודה קשה." },
  { "word": "יגע", "interpretation": "עייף, לאה, להה, תש כוחו." },
  { "word": "יד", "interpretation": "מצבת זיכרון, אנדרטה, גלעד." },
  { "word": "ידועה בציבור", "interpretation": "אשה החיה עם גבר ללא נישואין." },
  { "word": "יד ימינו", "interpretation": "עוזרו הנאמן, עושה דברו." },
  { "word": "יד רוחצת יד", "interpretation": "עשיית טובה למישהו כדי לקבל ממנו טובה, שמור לי ואשמור לך." },
  { "word": "ידה", "interpretation": "זרק, השליך, ירה." },
  { "word": "ידו היתה במעל", "interpretation": "היה לו חלק במעשה שלילי." },
  { "word": "ידו היתה על העליונה", "interpretation": "ניצח." },
  { "word": "ידוע/ה בציבור", "interpretation": "מצב משפטי בו למרות שבני זוג לא נישאו פורמאלית, יש לקשר ביניהם מעמד מחייב." },
  { "word": "ידעוני", "interpretation": "קוסם, מכשף, מעלה באוב, מג." },
  { "word": "יהב", "interpretation": "תקווה, סיכוי, תוחלת." },
  { "word": "יהיר", "interpretation": "גאוותן, מתנשא, רברבן, זחוח." },
  { "word": "יובל", "interpretation": "תקופה של חמישים שנה." },
  { "word": "יובל", "interpretation": "נחל, פלג." },
  { "word": "יוגב", "interpretation": "איכר, חקלאי, עובד אדמה, פלח." },
  { "word": "יומרנות", "interpretation": "התפארות ביכולות גדולות מכפי שיש באמת, התיימרות." },
  { "word": "יון", "interpretation": "בוץ, טיט, רפש, חומר, טין." },
  { "word": "יוצא חלציו", "interpretation": "בנו או בתו." },
  { "word": "יוצא מן הלב", "interpretation": "אמיתי, כן." },
  { "word": "יוקד", "interpretation": "בוער, דולק, לוהט." },
  { "word": "יורד דומה", "interpretation": "מת, בר מינן." },
  { "word": "יורה", "interpretation": "סיר גדול, דוד, קלחת, קדירה." },
  { "word": "יורידי", "interpretation": "משפטי." },
  { "word": "יושב בחיבוק ידיים", "interpretation": "מתבטל, יושב באפס מעשה, אינו נוקף אצבע." },
  { "word": "יושב על הגדר", "interpretation": "אינו נוקט עמדה." },
  { "word": "יושב על המדוכה", "interpretation": "מתלבט במחשבות." },
  { "word": "יושב קרנות", "interpretation": "בטלן, יושב בחיבוק ידיים." },
  { "word": "יחידי סגולה", "interpretation": "אנשים יוצאי דופן בתכונותיהם." },
  { "word": "יחל", "interpretation": "קיווה, ציפה, נשא עיניו." },
  { "word": "יחסן", "interpretation": "שחצן." },
  { "word": "יחפן", "interpretation": "פרחח, בטלן, ריק, פוחז, פוחח." },
  { "word": "ייחור", "interpretation": "ענף המשמש לשתילה בקרקע או להרכבה." },
  { "word": "יין בן חומץ", "interpretation": "צדיק בן רשע." },
  { "word": "ילק", "interpretation": "אחד ממיני הארבה." },
  { "word": "ימי חלדו", "interpretation": "ימי חייו." },
  { "word": "ינוקא", "interpretation": "תינוק, ולד, זאטוט." },
  { "word": "יסכון", "interpretation": "יועיל, יצלח, יתאים למשהו." },
  { "word": "יען", "interpretation": "בגלל, מפני ש…" },
  { "word": "יעף", "interpretation": "עייף, יגע, לאה, להה, תש כוחו." },
  { "word": "יערה", "interpretation": "חלת דבש." },
  { "word": "יפה נפש", "interpretation": "עדין, אנין, איסטניס." },
  { "word": "יפה שעה אחת קודם", "interpretation": "מוטב להקדים ככל האפשר." },
  { "word": "יפוי כוח", "interpretation": "הרשאה, זכות לעשות דבר- מה בשמו של אחר." },
  { "word": "יפעה", "interpretation": "יופי, נוי, הוד, הדר." },
  { "word": "יצא בשן ועין", "interpretation": "יצא בהפסד." },
  { "word": "יצא המרצע מן השק", "interpretation": "נחשפה האמת שהוסתרה." },
  { "word": "יצא הפסדו בשכרו", "interpretation": "הרוויח יותר משהפסיד." },
  { "word": "יצא ואוזניו מקוטפות", "interpretation": "נחל כישלון." },
  { "word": "יצא חוצץ", "interpretation": "יצא דרוך ומוכן." },
  { "word": "יצא טבעו", "interpretation": "התפרסם." },
  { "word": "יצא ידי חובה", "interpretation": "מילא את המוטל עליו בצורה מינימלית." },
  { "word": "יצא לשוח", "interpretation": "יצא לטייל." },
  { "word": "יצא לתרבות רעה", "interpretation": "סטה מדרך הישר, סרח, התפקר." },
  { "word": "יצא מגדרו", "interpretation": "נהג שלא כדרכו, התפרץ." },
  { "word": "יצא מכליו", "interpretation": "התלהב או התרגז עד שממש איבד שליטה." },
  { "word": "יצא מן הכוח אל הפועל", "interpretation": "בוצע." },
  { "word": "יצא מעורו", "interpretation": "התאמץ לעשות מעשה חיובי." },
  { "word": "יצא נקי מנכסיו", "interpretation": "הפסיד את כל הונו." },
  { "word": "יצא שכרו בהפסדו", "interpretation": "הפסיד יותר משהרוויח." },
  { "word": "יצא שמו", "interpretation": "התפרסם." },
  { "word": "יצא נפשו אל", "interpretation": "רצה מאוד, השתוקק." },
  { "word": "יצהר", "interpretation": "שמן טרי." },
  { "word": "יצול", "interpretation": "מוט בקצה עגלה או מחרשה, שאליו נקשרת הבהמה." },
  { "word": "יצוע", "interpretation": "מיטה, משכב." },
  { "word": "יצק שמן על המדורה", "interpretation": "הגדיל את הרוגז או המהומה." },
  { "word": "יקב", "interpretation": "מקום יצור היין." },
  { "word": "יקוש", "interpretation": "לכוד, נתון במוקש או מלכודת." },
  { "word": "יקיצה", "interpretation": "התעוררות משינה." },
  { "word": "יראה", "interpretation": "פחד, אימה, חרדה, בעתה." },
  { "word": "ירד לטמיון", "interpretation": "אבד." },
  { "word": "ירד לסוף דעתו", "interpretation": "הבין אותו." },
  { "word": "ירד מגדולתו", "interpretation": "חדל להיות חשוב." },
  { "word": "ירד מנכסיו", "interpretation": "התרושש, מטה ידו." },
  { "word": "ירח", "interpretation": "חודש." },
  { "word": "ירט", "interpretation": "אילץ לסטות ממסלולו." },
  { "word": "ירכתיים", "interpretation": "1. קצוות, גבולות; 2. החלק האחורי בספינה." },
  { "word": "יש בליבו עליו", "interpretation": "יש לו טענות כלפיו." },
  { "word": "ישב על האבניים", "interpretation": "עסק וטיפל בדבר, התלבט במחשבות." },
  { "word": "יש דברים בגו", "interpretation": "יש בזה משהו." },
  { "word": "יש לו מהלכים", "interpretation": "יש לו קשרים." },
  { "word": "יש רגליים לדבר", "interpretation": "הדבר מבוסס." },
  { "word": "ישב על האובניים", "interpretation": "עסק וטיפל בדבר." },
  { "word": "ישב תחת גפנו ותחת תאנתו", "interpretation": "ישב בשלום ובשלווה." },
  { "word": "ישוב הדעת", "interpretation": "מחשבה שקולה ומתונה." },
  { "word": "ישות", "interpretation": "קיום, הוויה." },
  { "word": "ישימון", "interpretation": "מדבר, שממה, ציה." },
  { "word": "ישר את ההדורים", "interpretation": "ישב את המחלוקת." },
  { "word": "יתר", "interpretation": "1.שארית, עודף; 2. חבל" },
]
