window.zain = [
  { "word": "זאב בעור כבש", "interpretation": "צבוע, מתחסד." },
  { "word": "זאב זאב", "interpretation": "התרעת שווא או שקר." },
  { "word": "זאטוט", "interpretation": "תינוק, ולד, ינוקא, עולל, ילדון." },
  { "word": "ז'אנר", "interpretation": "סגנון." },
  { "word": "זב", "interpretation": "נטף, נזל." },
  { "word": "זב חוטם", "interpretation": "כינוי מזלזל לאדם חסר ניסיון." },
  { "word": "זבד", "interpretation": "מתנה, שי, דורון, תשורה, מנחה." },
  { "word": "זבדה", "interpretation": "שמנת." },
  { "word": "זבח", "interpretation": "קורבן בהמה או עוף." },
  { "word": "זבן", "interpretation": "מוכר." },
  { "word": "זג", "interpretation": "קליפת ענבים או פירות אחרים." },
  { "word": "זד", "interpretation": "רשע." },
  { "word": "זדון", "interpretation": "רשעות, מזימה, צדייה." },
  { "word": "זה מכבר", "interpretation": "לפני זמן רב, מזמן." },
  { "word": "זוג", "interpretation": "דפנות הפעמון." },
  { "word": "זוהמה", "interpretation": "לכלוך, טינופת, רפש, סחי." },
  { "word": "זוז", "interpretation": "מטבע עתיק." },
  { "word": "זוטא", "interpretation": "קטן, זעיר, לא חשוב." },
  { "word": "זוטות", "interpretation": "עובדות קטנות ובלתי חשובות." },
  { "word": "זוטר", "interpretation": "בעל דרגה נמוכה." },
  { "word": "זולת", "interpretation": "חוץ מן, מלבד." },
  { "word": "זולתן", "interpretation": "מקריב עצמו למען הזולת, אלטרואיסט." },
  { "word": "זורר", "interpretation": "1. התעטש; 2. פיזר, זרה, בזק." },
  { "word": "זח", "interpretation": "זז, זע, מש, נע, נד, סר." },
  { "word": "זחוח", "interpretation": "גאוותן, רברבן, מתנשא, יהיר." },
  { "word": "זחתן", "interpretation": "גאוותן, יהיר." },
  { "word": "זיבה", "interpretation": "נזילה, טפטוף." },
  { "word": "זיבורית", "interpretation": "1. אדמה גרועה; 2. סחורה גרועה." },
  { "word": "זיג", "interpretation": "מעיל עליון." },
  { "word": "זיגוג", "interpretation": "1. התקנת זגוגיות בחלון; 2. שכבת ציפוי." },
  { "word": "זיו", "interpretation": "זוהר." },
  { "word": "זיז", "interpretation": "בליטה." },
  { "word": "זיכוך", "interpretation": "ניקוי, טיהור (גם מוסרי)." },
  { "word": "זילות", "interpretation": "זלזול, בזיון." },
  { "word": "זינוק מטאורי", "interpretation": "קפיצה אדירה קדימה." },
  { "word": "זיע", "interpretation": "רעד, רטט, ויברציה." },
  { "word": "זיק", "interpretation": "ניצוץ אש, שביב." },
  { "word": "זיקה", "interpretation": "קשר, יחס." },
  { "word": "זירה", "interpretation": "1. מגרש לתחרויות ספורט; 2. תחום הפעילות." },
  { "word": "זך", "interpretation": "נקי, טהור, צח, צלול, חף." },
  { "word": "זכה מן ההפקר", "interpretation": "קיבל משהו בלי לעבוד עבורו." },
  { "word": "זכות אבות", "interpretation": "יחס מיוחד שאדם זוכה לו בגלל הוריו או בשל מוצאו." },
  { "word": "זלדקן", "interpretation": "בעל זקן דליל." },
  { "word": "זלזל", "interpretation": "ענף דק, זמורה, זרד, נצר, בד." },
  { "word": "זליגה", "interpretation": "נזילה, זיבה, טפטוף." },
  { "word": "זלעפה", "interpretation": "רעדה, חלחלה, סערה." },
  { "word": "זמורה", "interpretation": "ענף גפן." },
  { "word": "זמם", "interpretation": "חשב להרע, התנכל, תיחבל." },
  { "word": "זמם", "interpretation": "מחסום לפה של חיה." },
  { "word": "זמר", "interpretation": "קצץ ענפים." },
  { "word": "זן", "interpretation": "סוג, מין." },
  { "word": "זן עיניו", "interpretation": "הרבה להסתכל." },
  { "word": "זנב לאריות", "interpretation": "אדם במעמד נחות בתוך חבורה מכובדת." },
  { "word": "זניחה", "interpretation": "עזיבה, נטישה, הפקרה." },
  { "word": "זעום", "interpretation": "מעט, מצומצם, קורט, שמץ." },
  { "word": "זעיר", "interpretation": "קטן מאוד, זוטא, זעום." },
  { "word": "זעם", "interpretation": "כעס, רוגז, מורת רוח, קצף." },
  { "word": "זעק חמס", "interpretation": "התנגד, גינה." },
  { "word": "זעת אפיו", "interpretation": "עמל רב, מאמץ גדול." },
  { "word": "זפיר", "interpretation": "רוח קלה." },
  { "word": "זקיף", "interpretation": "חייל או שוטר העומד על המשמר." },
  { "word": "זרא", "interpretation": "גועל, בחילה, קבס." },
  { "word": "זרבובית", "interpretation": "פיה של כלי." },
  { "word": "ז'רגון", "interpretation": "אוסף מונחים וביטויים ייחודי לקבוצת אנשים מוגדרת, טרמינולוגיה." },
  { "word": "זרד", "interpretation": "ענף רך, זלזל, שריג." },
  { "word": "זרה", "interpretation": "פיזר, הפיץ, בזק, זורר, בידר." },
  { "word": "זרז", "interpretation": "מזרז פעולה, מאיץ, קטליזטור." },
  { "word": "זרזיף", "interpretation": "זרם, שטף, קילוח." },
  { "word": "זריה לרוח", "interpretation": "מעשה לא יעיל." },
  { "word": "זרנוק", "interpretation": "צינור להשקייה או לכיבוי אש." },
  { "word": "זרע מרעים", "interpretation": "בנים רשעים." },
  { "word": "זרק בו מרה", "interpretation": "החמיר אתו, הטיף מוסר." },
  { "word": "זרה חול בעיני האנשים", "interpretation": "רימה, הונה, אחז עיניים, הוליך שולל." }
]
