window.ztadic = [
  { "word": "צבה", "interpretation": "התנפח, תפח." },
  { "word": "צביון", "interpretation": "צורה." },
  { "word": "צביר", "interpretation": "קבוצת חפצים." },
  { "word": "צבר", "interpretation": "ערימה, גל, תל, חשרה." },
  { "word": "צג", "interpretation": "מסך." },
  { "word": "צד את אוזנו", "interpretation": "סיקרן אותו בדברים שהשמיע." },
  { "word": "צדודית", "interpretation": "פרופיל." },
  { "word": "צדה", "interpretation": "ארב, התנכל, התנקש." },
  { "word": "צדיה", "interpretation": "כוונה רעה, זדון, מזימה." },
  { "word": "צדעים", "interpretation": "רקות, צידי הגולגולת." },
  { "word": "צדקנות", "interpretation": "התחסדות, צדיקות לכאורה." },
  { "word": "צהל", "interpretation": "1. סוס שהשמיע קול, צנף 2. השמיע קול שמחה." },
  { "word": "צוארון כחול", "interpretation": "שכבה חברתית העוסקת בעבודות כפיים." },
  { "word": "צוארון לבן", "interpretation": "שכבה חברתית העוסקת במנהל." },
  { "word": "צוהר", "interpretation": "חלון, אשנב, חרך." },
  { "word": "צווחה", "interpretation": "צעקה, זעקה, צריחה." },
  { "word": "צוק העתים", "interpretation": "שעת חירום, ימים טרופים." },
  { "word": "צור", "interpretation": "סלע גדול, צוק." },
  { "word": "צור מחצבתו", "interpretation": "מקורו, מולדתו." },
  { "word": "צורף", "interpretation": "מעצב ויוצר תכשיטי זהב וכסף." },
  { "word": "צורר", "interpretation": "שונא, אויב, צר, קם, רודף." },
  { "word": "צח", "interpretation": "נקי, טהור, זך, בהיר." },
  { "word": "צחור", "interpretation": "לבן." },
  { "word": "צחות לשון", "interpretation": "שימוש בשפה נאה." },
  { "word": "צחיח", "interpretation": "יבש, חרב." },
  { "word": "צחנה", "interpretation": "סירחון, באשה." },
  { "word": "צידד", "interpretation": "1. הפנה לצד 2. תמך." },
  { "word": "ציה", "interpretation": "מדבר, ישימון, שממה, בתה." },
  { "word": "צייקן", "interpretation": "קמצן." },
  { "word": "צילינדר", "interpretation": "מגבעת גבוהה." },
  { "word": "צינה", "interpretation": "1. קור 2. מגן, מחסה." },
  { "word": "צינוק", "interpretation": "בית כלא, מחבוש." },
  { "word": "ציני", "interpretation": "לועג לדעות המקובלות, מזלזל." },
  { "word": "ציניקן", "interpretation": "אדם לא רגיש." },
  { "word": "ציפה", "interpretation": "בשר הפרי." },
  { "word": "ציפורן", "interpretation": "חרט חד לכתיבה וחקיקה." },
  { "word": "ציץ", "interpretation": "עלי הכותרת בפרח." },
  { "word": "ציצית", "interpretation": "קווצת חוטים, גדיל." },
  { "word": "ציקלון", "interpretation": "תרמיל, ילקוט, שק, אמתחת." },
  { "word": "ציקלופים", "interpretation": "ענקים אגדיים." },
  { "word": "ציר", "interpretation": "1. שליח, רץ 2. כאבי לידה, חבל 3. רוטב." },
  { "word": "צלח", "interpretation": "חצה, עבר, ביקע." },
  { "word": "צלח המעשה בידיו", "interpretation": "הצליח לו." },
  { "word": "צליין", "interpretation": "עולה רגל המבקר במקומות הקדושים." },
  { "word": "צלם", "interpretation": "דמות, צורה." },
  { "word": "צלמוות", "interpretation": "חושך, אפלה, אופל, צלמון." },
  { "word": "צלצל", "interpretation": "כידון מחובר לחבל שבו צדים דגים גדולים." },
  { "word": "צמית", "interpretation": "איכר משועבד, אריס, וסל." },
  { "word": "צמצם", "interpretation": "מתקן במכשירים אופטיים לוויסות קרני אור." },
  { "word": "צמרת", "interpretation": "ראש העץ, אמיר." },
  { "word": "צנובר", "interpretation": "איצטרובל." },
  { "word": "צנום", "interpretation": "רזה, כחוש, דק גו." },
  { "word": "צנוף", "interpretation": "עטוף, כרוך, מכורבל, לוט." },
  { "word": "צנטריפוגלי", "interpretation": "מן המרכז החוצה." },
  { "word": "צנין", "interpretation": "קוץ, חוח, דרדר, חרול." },
  { "word": "צניפה", "interpretation": "צהלת הסוס." },
  { "word": "צפוד", "interpretation": "יבש, מצומק, מקומט, שדוף." },
  { "word": "צפון", "interpretation": "חבוי, מוסתר, טמון, נצור." },
  { "word": "צפחה", "interpretation": "מחצב מורכב מחומר ומצורן, המתפצל לשכבות." },
  { "word": "צפחת", "interpretation": "מימיה." },
  { "word": "צפיחית", "interpretation": "עוגה, אפיפית, רקיק, תופין." },
  { "word": "צפיר", "interpretation": "תיש, שעיר." },
  { "word": "צפנת", "interpretation": "סוד, רז." },
  { "word": "צפרא", "interpretation": "בוקר." },
  { "word": "צפריר", "interpretation": "רוח בוקר נעימה." },
  { "word": "צר", "interpretation": "אויב, שונא, קם, רודף, צורר." },
  { "word": "צר אופקים", "interpretation": "מוגבל בראיית עולמו." },
  { "word": "צרדה", "interpretation": "האצבע האמצעית ביד." },
  { "word": "צרוב", "interpretation": "שרוף, נכווה, שזוף." },
  { "word": "צרוף", "interpretation": "טהור, מזוקק." },
  { "word": "צרור", "interpretation": "חבילה, אגודה, אגד." },
  { "word": "צרות עין", "interpretation": "קינאה, טינה." },
  { "word": "צ'רטר", "interpretation": "1. כתב זכויות, הצהרה 2. טיסת שכר." },
  { "word": "צרי", "interpretation": "1. שרף עץ ששימש לריפוי 2. תרופה, גהה, מזור." },
  { "word": "צריח", "interpretation": "מגדל." },
  { "word": "צרימה", "interpretation": "אי התאמה בקולות, דיסוננס." },
  { "word": "צרר", "interpretation": "ארז, קשר, כרך לחבילה." },
]
